CREATE TABLE treido.media_assets (
  id uuid PRIMARY KEY,
  seller_id uuid NOT NULL,
  listing_id uuid NOT NULL,
  created_by uuid NOT NULL REFERENCES treido.users(id),
  request_id uuid NOT NULL,
  input_hash varchar(64) NOT NULL,
  state text NOT NULL DEFAULT 'staged' CHECK(state IN ('staged','processing','ready','failed','detached')),
  expected_bytes integer NOT NULL CHECK(expected_bytes BETWEEN 1 AND 12582912),
  content_type text NOT NULL CHECK(content_type IN ('image/jpeg','image/png','image/webp')),
  expected_checksum varchar(64) NOT NULL CHECK(expected_checksum ~ '^[0-9a-f]{64}$'),
  staging_key varchar(300) NOT NULL UNIQUE,
  immutable_key varchar(300) UNIQUE,
  source_etag varchar(160),
  derivative_key varchar(300) UNIQUE,
  derivative_checksum varchar(64),
  width integer CHECK(width > 0),height integer CHECK(height > 0),
  position integer NOT NULL CHECK(position BETWEEN 0 AND 11),
  revision integer NOT NULL DEFAULT 1 CHECK(revision > 0),
  job_id uuid,
  error_code text CHECK(error_code IN ('invalid_bytes','processing_unavailable')),
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  UNIQUE(seller_id,created_by,request_id),
  UNIQUE(seller_id,id),
  FOREIGN KEY(seller_id,listing_id) REFERENCES treido.listings(seller_id,id),
  FOREIGN KEY(seller_id,job_id) REFERENCES treido.outbox_jobs(seller_id,id),
  CHECK(state NOT IN ('processing','ready') OR (immutable_key IS NOT NULL AND job_id IS NOT NULL AND source_etag IS NOT NULL)),
  CHECK(state <> 'ready' OR (derivative_key IS NOT NULL AND derivative_checksum IS NOT NULL AND width IS NOT NULL AND height IS NOT NULL)),
  CHECK(width IS NULL OR height IS NULL OR width::bigint * height::bigint <= 40000000)
);
CREATE INDEX media_listing ON treido.media_assets(seller_id,listing_id,position,id) WHERE state <> 'detached';
