-- Original finite shipping lifecycle integration; no approval or qualification seed.
ALTER TABLE treido.order_aftercare_lifecycle_policies DROP CONSTRAINT order_aftercare_lifecycle_policies_version_check;
ALTER TABLE treido.order_aftercare_lifecycle_policies ADD CONSTRAINT order_aftercare_lifecycle_policies_version_check CHECK(version IN('order-aftercare-v1','order-aftercare-shipping-v2'));
CREATE TABLE treido.order_shipping_integration_qualifications(
 id uuid PRIMARY KEY,policy_id uuid NOT NULL REFERENCES treido.order_shipping_policies(id),policy_hash text NOT NULL CHECK(policy_hash~'^[a-f0-9]{64}$'),version text NOT NULL CHECK(version='original-shipping-integration-v1'),
 canonical_ledger_hash text NOT NULL CHECK(canonical_ledger_hash~'^[a-f0-9]{64}$'),source_manifest_hash text NOT NULL CHECK(source_manifest_hash~'^[a-f0-9]{64}$'),native_receipt_hash text NOT NULL CHECK(native_receipt_hash~'^[a-f0-9]{64}$'),compiler_receipt_hash text NOT NULL CHECK(compiler_receipt_hash~'^[a-f0-9]{64}$'),
 registered_kinds jsonb NOT NULL CHECK(registered_kinds='["shipping.input-expiry","shipping.recipient-expiry"]'::jsonb),quote_components_reviewed boolean NOT NULL CHECK(quote_components_reviewed),refund_components_reviewed boolean NOT NULL CHECK(refund_components_reviewed),signed_expiry_reviewed boolean NOT NULL CHECK(signed_expiry_reviewed),closure_aggregation_reviewed boolean NOT NULL CHECK(closure_aggregation_reviewed),
 audit_result text NOT NULL CHECK(audit_result IN('passed','owner_accepted')),audit_review_reference text NOT NULL CHECK(length(audit_review_reference) BETWEEN 1 AND 200),approved_at timestamptz NOT NULL,approval_reference text NOT NULL CHECK(length(approval_reference) BETWEEN 1 AND 200),revoked_at timestamptz,CHECK(revoked_at IS NULL OR revoked_at>=approved_at)
);
CREATE TRIGGER shipping_qualification_immutable BEFORE UPDATE OR DELETE ON treido.order_shipping_integration_qualifications FOR EACH ROW EXECUTE FUNCTION treido.guard_order_aftercare_registry();
CREATE FUNCTION treido.order_shipping_retention_ready(policy uuid,env text,app text) RETURNS boolean LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,treido AS $$
BEGIN
 IF policy IS NULL OR env IS NULL OR app IS NULL THEN RETURN false; END IF;
 RETURN EXISTS(SELECT 1 FROM treido.order_shipping_policies p JOIN treido.order_shipping_retention_approvals r ON r.policy_id=p.id AND r.policy_hash=p.terms_hash AND r.platform_account=p.platform_account AND r.livemode=p.livemode AND r.environment=p.environment AND r.application_id=p.application_id
 JOIN treido.order_shipping_integration_qualifications qualified ON qualified.policy_id=p.id AND qualified.policy_hash=p.terms_hash AND qualified.version='original-shipping-integration-v1'
 JOIN treido.order_aftercare_lifecycle_policies life ON life.version=r.aftercare_lifecycle_version AND life.environment=r.environment AND life.application_id=r.clerk_instance_id
 JOIN treido.account_lifecycle_bindings binding ON binding.environment=life.environment AND binding.application_id=life.application_id AND binding.clerk_instance_id=r.clerk_instance_id AND binding.clerk_mode=r.clerk_mode AND binding.stripe_account=r.platform_account AND binding.stripe_livemode=r.livemode AND binding.stripe_application_id=r.application_id AND binding.aftercare_lifecycle_version=life.version
 WHERE p.id=policy AND p.environment=env AND p.application_id=app AND p.approved_at<=clock_timestamp() AND p.revoked_at IS NULL AND r.approved_at<=clock_timestamp() AND r.revoked_at IS NULL AND r.deletes_due_unbound AND r.deletes_due_accepted AND r.preserves_accepted_history AND r.requires_zero_obligations AND r.legal_holds_reviewed AND life.preserves_accepted_evidence AND life.legal_holds_reviewed AND life.approved_at<=clock_timestamp() AND life.revoked_at IS NULL AND binding.closure_enabled AND binding.approved_at<=clock_timestamp() AND binding.revoked_at IS NULL AND qualified.approved_at<=clock_timestamp() AND qualified.revoked_at IS NULL
 AND qualified.canonical_ledger_hash=(SELECT encode(sha256(convert_to(string_agg(version||':'||checksum,E'\n' ORDER BY version),'UTF8')),'hex') FROM public.treido_schema_migrations)
 AND to_regprocedure('treido.order_shipping_expire_input(uuid,uuid,uuid,integer,uuid,text,text,text,text,text)') IS NOT NULL AND to_regprocedure('treido.order_shipping_validate_recipient_job(uuid,uuid,uuid,integer,uuid,text,text,text,text,text)') IS NOT NULL AND to_regprocedure('treido.order_shipping_clear_accepted_recipient(uuid,uuid,uuid,integer,uuid,text,text,text,text,text)') IS NOT NULL AND to_regprocedure('treido.order_shipping_authorize_job(uuid,uuid,uuid,text,integer,uuid,text,text,text,text,text)') IS NOT NULL AND to_regprocedure('treido.order_shipping_enqueue_maintenance(integer)') IS NOT NULL AND to_regprocedure('treido.order_shipping_closure_facts(uuid)') IS NOT NULL);
END $$;
CREATE FUNCTION treido.order_shipping_quote_ready(policy uuid,env text,app text) RETURNS boolean LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,treido AS $$
BEGIN
 RETURN treido.order_shipping_retention_ready(policy,env,app) AND EXISTS(SELECT 1 FROM treido.order_shipping_policies p JOIN treido.order_financial_policies f ON f.id=p.financial_policy_id AND f.base_policy_id=p.base_policy_id AND f.platform_account=p.platform_account AND f.livemode=p.livemode AND f.environment=p.environment AND f.application_id=p.application_id WHERE p.id=policy AND p.environment=env AND p.application_id=app AND p.payload->>'taxBasis'='inclusive_unspecified' AND f.method='shipping' AND f.refund_contract='bounded_partial_v2' AND f.tax_basis='inclusive_unspecified' AND f.reverse_transfer AND f.refund_application_fee AND f.approved_at<=clock_timestamp() AND f.revoked_at IS NULL) AND to_regclass('treido.order_refund_shipping_components') IS NOT NULL AND EXISTS(SELECT 1 FROM pg_trigger WHERE tgrelid='treido.order_refund_shipping_components'::regclass AND tgname='shipping_refund_budget' AND tgenabled='O') AND EXISTS(SELECT 1 FROM pg_trigger WHERE tgrelid='treido.payable_quotes'::regclass AND tgname='payable_quote_check' AND tgenabled='O');
END $$;
ALTER TABLE treido.outbox_jobs DROP CONSTRAINT outbox_jobs_kind_check;
ALTER TABLE treido.outbox_jobs ADD CONSTRAINT outbox_jobs_kind_check CHECK(kind IN('media.process','system.probe','catalogue.import','team.invitation','payment.reconcile','payment.refund','buyer.saved-search','billing.reconcile','promotion.reconcile','payment.aftercare','assistant.media-expiry','assistant.run-expiry','assistant.usage','account.closure','shipping.input-expiry','shipping.recipient-expiry'));
ALTER TABLE treido.outbox_jobs DROP CONSTRAINT outbox_jobs_authority_check;
ALTER TABLE treido.outbox_jobs ADD CONSTRAINT outbox_jobs_authority_check CHECK(authority IN('member','service','buyer','assistant','closure','shipping'));
ALTER TABLE treido.outbox_jobs DROP CONSTRAINT outbox_actor_authority;
ALTER TABLE treido.outbox_jobs ADD CONSTRAINT outbox_actor_authority CHECK((authority='member' AND actor_id IS NOT NULL) OR (authority='service' AND actor_id IS NULL) OR (authority='buyer' AND actor_id IS NOT NULL AND actor_id=buyer_id) OR (authority IN('assistant','closure','shipping') AND actor_id IS NULL));
ALTER TABLE treido.outbox_jobs DROP CONSTRAINT outbox_owner_scope;
ALTER TABLE treido.outbox_jobs ADD CONSTRAINT outbox_owner_scope CHECK(
 (kind='buyer.saved-search' AND seller_id IS NULL AND buyer_id IS NOT NULL AND actor_id=buyer_id AND authority='buyer') OR
 (kind IN('assistant.media-expiry','assistant.run-expiry','assistant.usage') AND seller_id IS NULL AND buyer_id IS NOT NULL AND actor_id IS NULL AND authority='assistant' AND operation_key=resource_id) OR
 (kind IN('shipping.input-expiry','shipping.recipient-expiry') AND seller_id IS NULL AND buyer_id IS NOT NULL AND actor_id IS NULL AND authority='shipping' AND operation_key=resource_id) OR
 (kind='account.closure' AND seller_id IS NULL AND buyer_id IS NOT NULL AND actor_id IS NULL AND authority='closure') OR
 (kind NOT IN('buyer.saved-search','assistant.media-expiry','assistant.run-expiry','assistant.usage','account.closure','shipping.input-expiry','shipping.recipient-expiry') AND seller_id IS NOT NULL AND buyer_id IS NULL AND authority IN('member','service')));


CREATE FUNCTION treido.guard_order_shipping_outbox() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,treido AS $$
DECLARE c treido.order_shipping_choices; private treido.order_shipping_recipients; p treido.order_shipping_policies;
BEGIN
 IF TG_OP='UPDATE' AND OLD.kind IN('shipping.input-expiry','shipping.recipient-expiry') THEN
 IF (to_jsonb(NEW)-ARRAY['state','generation','attempts','available_at','dispatch_token','dispatch_until','executor_event_id','accepted_at','progress_at','completed_at','last_error']) IS DISTINCT FROM (to_jsonb(OLD)-ARRAY['state','generation','attempts','available_at','dispatch_token','dispatch_until','executor_event_id','accepted_at','progress_at','completed_at','last_error']) OR NEW.generation<OLD.generation OR NEW.generation>OLD.generation+1 OR (NEW.generation<>OLD.generation AND NOT EXISTS(SELECT 1 FROM treido.job_redrives d WHERE d.job_id=OLD.id AND d.from_generation=OLD.generation AND d.to_generation=NEW.generation)) OR (OLD.state='completed' AND NEW.state<>'completed') THEN RAISE EXCEPTION 'Original shipping expiry job is immutable' USING ERRCODE='23514'; END IF;RETURN NEW;END IF;
 IF NEW.kind NOT IN('shipping.input-expiry','shipping.recipient-expiry') THEN RETURN NEW;END IF;
 IF TG_OP<>'INSERT' OR NEW.authority<>'shipping' OR NEW.buyer_id IS NULL OR NEW.seller_id IS NOT NULL OR NEW.actor_id IS NOT NULL OR NEW.operation_key<>NEW.resource_id OR NEW.intent_hash IS DISTINCT FROM (CASE NEW.kind WHEN 'shipping.input-expiry' THEN treido.order_shipping_input_intent_hash(NEW.buyer_id,NEW.resource_id) ELSE treido.order_shipping_retention_intent_hash(NEW.buyer_id,NEW.resource_id) END) THEN RAISE EXCEPTION 'Original shipping expiry intent mismatch' USING ERRCODE='23514'; END IF;
 PERFORM 1 FROM treido.users WHERE id=NEW.buyer_id FOR UPDATE;
 SELECT * INTO c FROM treido.order_shipping_choices WHERE id=NEW.resource_id AND buyer_id=NEW.buyer_id;
 SELECT * INTO private FROM treido.order_shipping_recipients WHERE choice_id=c.id AND buyer_id=c.buyer_id;
 SELECT * INTO p FROM treido.order_shipping_policies WHERE id=(c.snapshot->'option'->'policy'->>'id')::uuid AND terms_hash=c.snapshot->'option'->'policy'->>'termsHash';
 IF c.id IS NULL OR private.choice_id IS NULL OR private.value IS NULL OR private.retain_until>clock_timestamp() OR NOT treido.order_shipping_retention_ready(p.id,p.environment,p.application_id) OR (NEW.kind='shipping.input-expiry' AND (c.quote_id IS NOT NULL OR c.expires_at>clock_timestamp())) OR (NEW.kind='shipping.recipient-expiry' AND (c.state<>'bound' OR NOT treido.order_shipping_recipient_obligations_clear(c.id))) THEN RAISE EXCEPTION 'Original due shipping artifact unavailable' USING ERRCODE='55000'; END IF;RETURN NEW;
END $$;
CREATE TRIGGER shipping_outbox_original BEFORE INSERT OR UPDATE ON treido.outbox_jobs FOR EACH ROW EXECUTE FUNCTION treido.guard_order_shipping_outbox();
CREATE OR REPLACE FUNCTION treido.queue_original_lifecycle(k text,u uuid,r uuid,o uuid,next_at timestamptz) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,treido AS $$
DECLARE original treido.outbox_jobs; effect treido.job_effects; new_id uuid; hash text;
BEGIN
 IF k NOT IN('assistant.media-expiry','assistant.run-expiry','assistant.usage','account.closure','shipping.input-expiry','shipping.recipient-expiry') OR u IS NULL OR r IS NULL OR o IS NULL OR next_at IS NULL THEN RAISE EXCEPTION 'Invalid lifecycle queue scope' USING ERRCODE='23514'; END IF;
 hash:=CASE WHEN k='shipping.input-expiry' THEN treido.order_shipping_input_intent_hash(u,r) WHEN k='shipping.recipient-expiry' THEN treido.order_shipping_retention_intent_hash(u,r) ELSE treido.lifecycle_intent_hash(k,u,r,o) END;new_id:=gen_random_uuid();
 INSERT INTO treido.outbox_jobs(id,kind,seller_id,buyer_id,resource_id,operation_key,actor_id,authority,intent_hash,available_at) VALUES(new_id,k,NULL,u,r,o,NULL,CASE WHEN k='account.closure' THEN 'closure' WHEN k IN('shipping.input-expiry','shipping.recipient-expiry') THEN 'shipping' ELSE 'assistant' END,hash,greatest(clock_timestamp(),next_at)) ON CONFLICT(kind,operation_key) DO NOTHING;
 SELECT * INTO original FROM treido.outbox_jobs WHERE kind=k AND operation_key=o FOR UPDATE;
 IF original.intent_hash IS DISTINCT FROM hash OR original.resource_id<>r OR original.buyer_id<>u THEN RAISE EXCEPTION 'Original lifecycle queue conflict' USING ERRCODE='23514'; END IF;
 INSERT INTO treido.job_effects(job_id,kind,operation_key) VALUES(original.id,k,o) ON CONFLICT(job_id) DO NOTHING;
 SELECT * INTO effect FROM treido.job_effects WHERE job_id=original.id FOR UPDATE;
 IF original.state IN('completed','cancelled') OR effect.state IN('completed','cancelled') OR original.dispatch_until>clock_timestamp() OR effect.execution_until>clock_timestamp() THEN RETURN original.id; END IF;
 IF original.state='dead' THEN
  INSERT INTO treido.job_redrives(id,job_id,service_id,reason,from_generation,to_generation) VALUES(gen_random_uuid(),original.id,'accepted-lifecycle-repair-v1','Read or expire the exact original accepted lifecycle artifact; immutable financial/provider keys retained.',original.generation,original.generation+1);
  UPDATE treido.outbox_jobs SET state='pending',generation=generation+1,attempts=0,available_at=greatest(clock_timestamp(),next_at),progress_at=clock_timestamp(),dispatch_token=NULL,dispatch_until=NULL,executor_event_id=NULL,accepted_at=NULL,last_error=NULL WHERE id=original.id;
  UPDATE treido.job_effects SET state='pending',execution_token=NULL,execution_until=NULL WHERE job_id=original.id AND state IN('pending','running');
 END IF;
 RETURN original.id;
END $$;

CREATE FUNCTION treido.order_shipping_authorize_job(j uuid,u uuid,c uuid,k text,g integer,t uuid,executor_app text,executor_env text,backend_env text,clerk_app text,clerk_mode_value text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,treido AS $$
DECLARE choice treido.order_shipping_choices; private treido.order_shipping_recipients; p treido.order_shipping_policies; actual treido.outbox_jobs; allocation uuid; original_order uuid;
BEGIN
 IF j IS NULL OR u IS NULL OR c IS NULL OR k IS NULL OR k NOT IN('shipping.input-expiry','shipping.recipient-expiry') OR g IS NULL OR g<1 OR executor_app IS NULL OR executor_env IS NULL OR backend_env IS NULL OR clerk_app IS NULL OR clerk_mode_value IS NULL THEN RAISE EXCEPTION 'Shipping authority scope missing' USING ERRCODE='23514'; END IF;
 PERFORM 1 FROM treido.users WHERE id=u FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'Shipping artifact owner missing' USING ERRCODE='23514';END IF;
 SELECT q.allocation_id,o.id INTO allocation,original_order FROM treido.order_shipping_choices c JOIN treido.payable_quotes q ON q.id=c.quote_id LEFT JOIN treido.paid_orders o ON o.quote_id=q.id WHERE c.id=$3 AND c.buyer_id=u;
 IF allocation IS NOT NULL THEN PERFORM 1 FROM treido.inventory_allocations WHERE id=allocation FOR UPDATE;END IF;IF original_order IS NOT NULL THEN PERFORM 1 FROM treido.paid_orders WHERE id=original_order FOR UPDATE;END IF;
 SELECT * INTO choice FROM treido.order_shipping_choices WHERE id=c AND buyer_id=u FOR UPDATE;SELECT * INTO private FROM treido.order_shipping_recipients WHERE choice_id=c AND buyer_id=u FOR UPDATE;
 SELECT * INTO p FROM treido.order_shipping_policies WHERE id=(choice.snapshot->'option'->'policy'->>'id')::uuid AND terms_hash=choice.snapshot->'option'->'policy'->>'termsHash' AND environment=backend_env;
 SELECT * INTO actual FROM treido.outbox_jobs WHERE id=j;
 IF choice.id IS NULL OR private.choice_id IS NULL OR p.id IS NULL OR actual.id IS NULL OR actual.kind<>k OR actual.authority<>'shipping' OR actual.buyer_id<>u OR actual.seller_id IS NOT NULL OR actual.actor_id IS NOT NULL OR actual.resource_id<>c OR actual.operation_key<>c OR actual.generation<>g OR actual.intent_hash IS DISTINCT FROM (CASE k WHEN 'shipping.input-expiry' THEN treido.order_shipping_input_intent_hash(u,c) ELSE treido.order_shipping_retention_intent_hash(u,c) END) OR NOT treido.order_shipping_retention_ready(p.id,p.environment,p.application_id) THEN RAISE EXCEPTION 'Original shipping authority unavailable' USING ERRCODE='55000'; END IF;
 PERFORM 1 FROM treido.order_shipping_retention_approvals r WHERE r.policy_id=p.id AND r.policy_hash=p.terms_hash AND r.platform_account=p.platform_account AND r.livemode=p.livemode AND r.environment=backend_env AND r.application_id=p.application_id AND r.executor_application_id=executor_app AND r.executor_environment=executor_env AND r.clerk_instance_id=clerk_app AND r.clerk_mode=clerk_mode_value AND r.approved_at<=clock_timestamp() AND r.revoked_at IS NULL FOR SHARE;IF NOT FOUND THEN RAISE EXCEPTION 'Current shipping executor namespace unavailable' USING ERRCODE='55000'; END IF;
 IF EXISTS(SELECT 1 FROM treido.order_aftercare_legal_holds h WHERE h.approved_at<=clock_timestamp() AND h.revoked_at IS NULL AND (h.user_id=u OR h.order_id=original_order) AND ((h.environment=backend_env AND h.application_id=clerk_app) OR (h.environment=p.environment AND h.application_id=p.application_id))) THEN RAISE EXCEPTION 'Shipping original evidence legally held' USING ERRCODE='55000';END IF;
 IF t IS NULL AND actual.state='completed' AND private.value IS NULL AND private.cleared_at IS NOT NULL AND EXISTS(SELECT 1 FROM treido.job_effects e WHERE e.job_id=j AND e.kind=k AND e.operation_key=c AND e.state='completed' AND e.result_id=c) THEN RETURN; END IF;
 IF private.retain_until>clock_timestamp() OR (k='shipping.input-expiry' AND (choice.quote_id IS NOT NULL OR choice.expires_at>clock_timestamp())) OR (k='shipping.recipient-expiry' AND (choice.state<>'bound' OR NOT treido.order_shipping_recipient_obligations_clear(c))) THEN RAISE EXCEPTION 'Original shipping artifact remains held' USING ERRCODE='55000'; END IF;
 IF t IS NOT NULL THEN IF k='shipping.recipient-expiry' THEN PERFORM treido.order_shipping_validate_recipient_job(j,u,c,g,t,executor_app,executor_env,backend_env,clerk_app,clerk_mode_value);ELSE IF NOT EXISTS(SELECT 1 FROM treido.job_effects e WHERE e.job_id=j AND e.kind=k AND e.operation_key=c AND e.state='running' AND e.execution_token=t AND e.execution_until>clock_timestamp()) OR actual.state NOT IN('pending','accepted') THEN RAISE EXCEPTION 'Original shipping execution lease denied' USING ERRCODE='23514'; END IF;END IF;END IF;
END $$;
CREATE FUNCTION treido.order_shipping_enqueue_maintenance(batch integer) RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,treido AS $$
DECLARE item record; queued integer:=0;
BEGIN
 IF batch IS NULL OR batch<1 OR batch>20 THEN RAISE EXCEPTION 'Invalid original shipping maintenance bound' USING ERRCODE='23514';END IF;
 FOR item IN SELECT c.id,c.buyer_id,CASE WHEN c.quote_id IS NULL THEN 'shipping.input-expiry' ELSE 'shipping.recipient-expiry' END AS kind FROM treido.order_shipping_choices c JOIN treido.order_shipping_recipients r ON r.choice_id=c.id AND r.buyer_id=c.buyer_id JOIN treido.order_shipping_policies p ON p.id=(c.snapshot->'option'->'policy'->>'id')::uuid WHERE r.value IS NOT NULL AND r.retain_until<=clock_timestamp() AND ((c.quote_id IS NULL AND c.expires_at<=clock_timestamp()) OR (c.state='bound' AND treido.order_shipping_recipient_obligations_clear(c.id))) AND treido.order_shipping_retention_ready(p.id,p.environment,p.application_id) AND NOT EXISTS(SELECT 1 FROM treido.outbox_jobs j JOIN treido.job_effects e ON e.job_id=j.id WHERE j.kind=CASE WHEN c.quote_id IS NULL THEN 'shipping.input-expiry' ELSE 'shipping.recipient-expiry' END AND j.operation_key=c.id AND (j.state IN('pending','accepted','completed','cancelled') OR j.dispatch_until>clock_timestamp() OR e.execution_until>clock_timestamp())) ORDER BY r.retain_until,c.id LIMIT batch LOOP
 PERFORM 1 FROM treido.users WHERE id=item.buyer_id FOR UPDATE;PERFORM treido.queue_original_lifecycle(item.kind,item.buyer_id,item.id,item.id,clock_timestamp());queued:=queued+1;END LOOP;RETURN queued;
END $$;
CREATE FUNCTION treido.order_shipping_closure_facts(u uuid) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,treido AS $$
DECLARE v_policy_scope record; inputs bigint; recipients bigint; outstanding bigint;
BEGIN
 FOR v_policy_scope IN SELECT DISTINCT p.id,p.environment,p.application_id FROM treido.order_shipping_policies p JOIN treido.order_shipping_choices c ON c.snapshot->'option'->'policy'->>'id'=p.id::text WHERE c.buyer_id=u OR EXISTS(SELECT 1 FROM treido.personal_seller_owners po WHERE po.user_id=u AND po.seller_id=c.seller_id) OR EXISTS(SELECT 1 FROM treido.seller_memberships m WHERE m.user_id=u AND m.seller_id=c.seller_id AND m.status='active' AND m.role='owner') LOOP IF NOT treido.order_shipping_retention_ready(v_policy_scope.id,v_policy_scope.environment,v_policy_scope.application_id) THEN RAISE EXCEPTION 'Original shipping closure integration unavailable' USING ERRCODE='55000';END IF;END LOOP;
 SELECT count(*) FILTER(WHERE c.quote_id IS NULL),count(*) FILTER(WHERE c.quote_id IS NOT NULL) INTO inputs,recipients FROM treido.order_shipping_recipients r JOIN treido.order_shipping_choices c ON c.id=r.choice_id WHERE r.buyer_id=u AND r.value IS NOT NULL;
 WITH owned AS(SELECT seller_id FROM treido.personal_seller_owners WHERE user_id=u UNION SELECT seller_id FROM treido.seller_memberships WHERE user_id=u AND status='active' AND role='owner') SELECT count(*) INTO outstanding FROM treido.order_shipping_choices c JOIN treido.paid_orders o ON o.quote_id=c.quote_id WHERE (c.buyer_id=u OR c.seller_id IN(SELECT seller_id FROM owned)) AND NOT treido.order_shipping_recipient_obligations_clear(c.id);
 RETURN jsonb_build_object('unboundShippingPrivateInputs',inputs,'retainedShippingRecipients',recipients,'shippingOutstanding',outstanding);
END $$;
REVOKE ALL ON treido.order_shipping_integration_qualifications FROM PUBLIC;
REVOKE ALL ON FUNCTION treido.order_shipping_retention_ready(uuid,text,text),treido.order_shipping_quote_ready(uuid,text,text),treido.guard_order_shipping_outbox(),treido.order_shipping_authorize_job(uuid,uuid,uuid,text,integer,uuid,text,text,text,text,text),treido.order_shipping_enqueue_maintenance(integer),treido.order_shipping_closure_facts(uuid) FROM PUBLIC;
CREATE OR REPLACE FUNCTION treido.order_aftercare_closure_facts(u uuid) RETURNS jsonb LANGUAGE plpgsql STABLE SET search_path=pg_catalog,treido AS $$
DECLARE policy treido.order_aftercare_lifecycle_policies%ROWTYPE; n integer; cases bigint; refunds bigint; shipping bigint; holds bigint; restore boolean; extra jsonb; private_count bigint:=0;
BEGIN
 IF NOT EXISTS(SELECT 1 FROM treido.users WHERE id=u) THEN RAISE EXCEPTION 'Unknown aftercare owner' USING ERRCODE='23514'; END IF;
 SELECT count(*) INTO n FROM treido.order_aftercare_lifecycle_policies p WHERE p.approved_at<=clock_timestamp() AND p.revoked_at IS NULL AND p.legal_holds_reviewed AND p.preserves_accepted_evidence AND EXISTS(SELECT 1 FROM treido.account_lifecycle_bindings b WHERE b.environment=p.environment AND b.application_id=p.application_id AND b.aftercare_lifecycle_version=p.version AND b.closure_enabled AND b.approved_at<=clock_timestamp() AND b.revoked_at IS NULL);
 IF n<>1 THEN RAISE EXCEPTION 'Reviewed aftercare lifecycle unavailable' USING ERRCODE='55000'; END IF;
 SELECT p.* INTO policy FROM treido.order_aftercare_lifecycle_policies p WHERE p.approved_at<=clock_timestamp() AND p.revoked_at IS NULL AND p.legal_holds_reviewed AND p.preserves_accepted_evidence AND EXISTS(SELECT 1 FROM treido.account_lifecycle_bindings b WHERE b.environment=p.environment AND b.application_id=p.application_id AND b.aftercare_lifecycle_version=p.version AND b.closure_enabled AND b.approved_at<=clock_timestamp() AND b.revoked_at IS NULL);
 WITH owned AS(SELECT seller_id FROM treido.personal_seller_owners WHERE user_id=u UNION SELECT seller_id FROM treido.seller_memberships WHERE user_id=u AND status='active' AND role='owner')
 SELECT (SELECT count(*) FROM treido.order_cases c WHERE (c.buyer_id=u OR c.seller_id IN(SELECT seller_id FROM owned)) AND c.state<>'resolved'),
 (SELECT count(*) FROM treido.order_refund_intents r WHERE (r.buyer_id=u OR r.actor_id=u OR r.seller_id IN(SELECT seller_id FROM owned)) AND r.state<>'expired' AND (r.state<>'succeeded' OR r.settlement_state<>'verified')),
 (SELECT count(*) FROM treido.order_fulfilments f JOIN treido.paid_orders o ON o.id=f.order_id WHERE (o.buyer_id=u OR o.seller_id IN(SELECT seller_id FROM owned)) AND f.method='shipping' AND f.state<>'buyer_confirmed_delivery'),
 (SELECT count(DISTINCT h.id) FROM treido.order_aftercare_legal_holds h WHERE h.approved_at<=clock_timestamp() AND h.revoked_at IS NULL AND (h.user_id=u OR EXISTS(SELECT 1 FROM treido.paid_orders o WHERE o.id=h.order_id AND (o.buyer_id=u OR o.seller_id IN(SELECT seller_id FROM owned)))) AND ((h.environment=policy.environment AND h.application_id=policy.application_id) OR EXISTS(SELECT 1 FROM treido.order_shipping_choices c JOIN treido.order_shipping_policies sp ON sp.id=(c.snapshot->'option'->'policy'->>'id')::uuid AND sp.terms_hash=c.snapshot->'option'->'policy'->>'termsHash' JOIN treido.order_shipping_retention_approvals mapped ON mapped.policy_id=sp.id AND mapped.policy_hash=sp.terms_hash AND mapped.platform_account=sp.platform_account AND mapped.livemode=sp.livemode AND mapped.environment=sp.environment AND mapped.application_id=sp.application_id WHERE h.environment=sp.environment AND h.application_id=sp.application_id AND mapped.environment=policy.environment AND mapped.clerk_instance_id=policy.application_id AND mapped.aftercare_lifecycle_version=policy.version AND mapped.approved_at<=clock_timestamp() AND mapped.revoked_at IS NULL AND treido.order_shipping_retention_ready(sp.id,sp.environment,sp.application_id) AND (c.buyer_id=u OR c.seller_id IN(SELECT seller_id FROM owned)) AND (h.user_id=u OR EXISTS(SELECT 1 FROM treido.paid_orders original_order JOIN treido.payable_quotes original_quote ON original_quote.id=original_order.quote_id AND original_quote.buyer_id=c.buyer_id AND original_quote.seller_id=c.seller_id AND original_quote.platform_account=sp.platform_account AND original_quote.livemode=sp.livemode JOIN treido.payment_policies original_policy ON original_policy.id=original_quote.policy_id AND original_policy.id=sp.base_policy_id AND original_policy.platform_account=original_quote.platform_account AND original_policy.livemode=original_quote.livemode AND original_policy.environment=sp.environment AND original_policy.application_id=sp.application_id WHERE original_order.id=h.order_id AND original_order.quote_id=c.quote_id AND original_order.buyer_id=c.buyer_id AND original_order.seller_id=c.seller_id))))) INTO cases,refunds,shipping,holds;
 IF EXISTS(SELECT 1 FROM treido.order_shipping_choices c WHERE c.buyer_id=u OR EXISTS(SELECT 1 FROM treido.personal_seller_owners po WHERE po.user_id=u AND po.seller_id=c.seller_id) OR EXISTS(SELECT 1 FROM treido.seller_memberships m WHERE m.user_id=u AND m.seller_id=c.seller_id AND m.status='active' AND m.role='owner')) THEN
 IF policy.version<>'order-aftercare-shipping-v2' THEN RAISE EXCEPTION 'Shipping requires reviewed lifecycle v2' USING ERRCODE='55000';END IF;
 extra:=treido.order_shipping_closure_facts(u);private_count:=(extra->>'unboundShippingPrivateInputs')::bigint+(extra->>'retainedShippingRecipients')::bigint;
 -- New original shipping replaces only its old unconfirmed count; preserved legacy aftercare stays in the original aggregation.
 WITH owned AS(SELECT seller_id FROM treido.personal_seller_owners WHERE user_id=u UNION SELECT seller_id FROM treido.seller_memberships WHERE user_id=u AND status='active' AND role='owner') SELECT count(*) INTO shipping FROM treido.order_fulfilments f JOIN treido.paid_orders o ON o.id=f.order_id WHERE (o.buyer_id=u OR o.seller_id IN(SELECT seller_id FROM owned)) AND f.method='shipping' AND f.state<>'buyer_confirmed_delivery' AND NOT EXISTS(SELECT 1 FROM treido.order_shipping_choices c WHERE c.quote_id=o.quote_id);
 shipping:=shipping+(extra->>'shippingOutstanding')::bigint;
 END IF;
 restore:=policy.allow_restore_restriction AND holds=0 AND cases+refunds+shipping+private_count=0 AND EXISTS(SELECT 1 FROM treido.users human JOIN LATERAL(SELECT * FROM treido.account_lifecycle_status_events e WHERE e.user_id=human.id ORDER BY e.id DESC LIMIT 1) event ON true JOIN treido.account_execution_plans plan ON plan.id=event.plan_id AND plan.user_id=human.id WHERE human.id=u AND human.status='restricted' AND event.cause='closure_claim' AND event.previous_status='active' AND event.next_status='restricted' AND plan.state IN('accepted','processing','blocked','reconciling') AND plan.first_effect_at IS NULL);
 RETURN jsonb_build_object('aftercareCases',cases+refunds+shipping+private_count,'aftercareRefunds',refunds,'unconfirmedShipping',shipping,'legalHolds',holds,'aftercareLifecycleVersion',policy.version,'mayRestoreClosureRestriction',restore,'shippingPrivatePayloads',private_count);
END $$;

-- Adapt only original core order obligations; frozen T65 source and all other original facts remain exact.
CREATE OR REPLACE FUNCTION treido.account_closure_obligations(u uuid) RETURNS jsonb LANGUAGE plpgsql STABLE SET search_path=pg_catalog,treido AS $$
DECLARE x jsonb; f jsonb;
BEGIN
 x:=treido.account_closure_extension_facts(u);
 IF x IS NULL OR NOT(x ?& ARRAY['assistantRuns','aftercareCases','legalHolds']) OR EXISTS(SELECT 1 FROM jsonb_each_text(x) p WHERE p.key IN('assistantRuns','aftercareCases','legalHolds') AND (p.value IS NULL OR p.value !~ '^[0-9]+$')) THEN RAISE EXCEPTION 'Closure lifecycle extension unavailable' USING ERRCODE='55000'; END IF;
 WITH scope AS (SELECT seller_id FROM treido.personal_seller_owners WHERE user_id=u UNION SELECT seller_id FROM treido.seller_memberships WHERE user_id=u AND status='active' AND role='owner')
 SELECT jsonb_build_object(
 'soleBusinessOwners',(SELECT count(*) FROM treido.seller_memberships m WHERE m.user_id=u AND m.status='active' AND m.role='owner' AND NOT EXISTS(SELECT 1 FROM treido.seller_memberships o WHERE o.seller_id=m.seller_id AND o.user_id<>u AND o.role='owner' AND o.status='active')),
 'allocations',(SELECT count(*) FROM treido.inventory_allocations WHERE (buyer_id=u OR seller_id IN(SELECT seller_id FROM scope)) AND state IN('active','reconciliation')),
 'offers',(SELECT count(*) FROM treido.listing_offers WHERE (buyer_id=u OR seller_id IN(SELECT seller_id FROM scope)) AND state IN('pending','accepted')),
 'payments',(SELECT count(*) FROM treido.payment_attempts a JOIN treido.payable_quotes q ON q.id=a.quote_id AND q.seller_id=a.seller_id WHERE (q.buyer_id=u OR a.seller_id IN(SELECT seller_id FROM scope)) AND a.state NOT IN('cancelled','paid')),
 'orders',(SELECT count(*) FROM treido.paid_orders o JOIN treido.payable_quotes q ON q.id=o.quote_id JOIN treido.payment_policies original_policy ON original_policy.id=q.policy_id WHERE (o.buyer_id=u OR o.seller_id IN(SELECT seller_id FROM scope)) AND (o.payment_state IN('refund_pending','disputed','reconciliation') OR o.settlement_state='reconciliation' OR (CASE WHEN q.terms_snapshot->>'handover'='shipping' THEN NOT EXISTS(SELECT 1 FROM treido.order_shipping_choices c JOIN treido.order_shipping_policies sp ON sp.id=(c.snapshot->'option'->'policy'->>'id')::uuid AND sp.terms_hash=c.snapshot->'option'->'policy'->>'termsHash' AND sp.platform_account=q.platform_account AND sp.livemode=q.livemode AND sp.base_policy_id=original_policy.id AND sp.environment=original_policy.environment AND sp.application_id=original_policy.application_id WHERE c.quote_id=q.id AND c.buyer_id=o.buyer_id AND c.seller_id=o.seller_id AND c.state='bound' AND treido.order_shipping_quote_ready(sp.id,sp.environment,sp.application_id) AND treido.order_shipping_recipient_obligations_clear(c.id)) ELSE (o.payment_state<>'refunded' AND o.fulfilment_state<>'collected') END))),
 'refunds',(SELECT count(*) FROM treido.payment_refunds r JOIN treido.paid_orders o ON o.id=r.order_id AND o.seller_id=r.seller_id WHERE (o.buyer_id=u OR r.seller_id IN(SELECT seller_id FROM scope)) AND r.state NOT IN('succeeded','failed')),
 'cases',(SELECT count(*) FROM treido.reports r WHERE r.state='open' AND (r.reporter_id=u OR (r.resource_kind='listing' AND EXISTS(SELECT 1 FROM treido.listings l WHERE l.id=r.resource_id AND l.seller_id IN(SELECT seller_id FROM scope))) OR (r.resource_kind='message' AND EXISTS(SELECT 1 FROM treido.messages m WHERE m.id=r.resource_id AND m.author_id=u))))+(SELECT count(*) FROM treido.moderation_appeals a JOIN treido.moderation_actions action ON action.id=a.action_id JOIN treido.listings l ON l.id=action.listing_id WHERE (a.actor_id=u OR l.seller_id IN(SELECT seller_id FROM scope)) AND NOT EXISTS(SELECT 1 FROM treido.trust_case_decisions d WHERE d.appeal_id=a.id))+(x->>'aftercareCases')::bigint,
 'billingIntents',(SELECT count(*) FROM treido.billing_intents WHERE (actor_id=u OR seller_id IN(SELECT seller_id FROM scope)) AND operation IN('checkout','change','cancel') AND state IN('prepared','creating','reconciling','ready')),
 'billingInvoices',(SELECT count(*) FROM (SELECT DISTINCT ON(i.subscription_id,i.provider_id) i.status,i.paid FROM treido.billing_invoice_observations i JOIN treido.billing_subscriptions s ON s.id=i.subscription_id WHERE s.seller_id IN(SELECT seller_id FROM scope) ORDER BY i.subscription_id,i.provider_id,i.observed_at DESC,i.id DESC) latest WHERE NOT paid AND status NOT IN('void','uncollectible')),
 'promotionAttempts',(SELECT count(*) FROM treido.promotion_attempts WHERE seller_id IN(SELECT seller_id FROM scope) AND state IN('prepared','creating','reconciling','pending','quarantined')),
 'promotionReservations',(SELECT count(*) FROM treido.promotion_reservations r JOIN treido.promotion_campaigns c ON c.id=r.campaign_id WHERE c.seller_id IN(SELECT seller_id FROM scope) AND r.status<>'released'),
 'promotionRemedies',(SELECT count(*) FROM treido.promotion_remedy_reviews r JOIN treido.promotion_campaigns c ON c.id=r.campaign_id WHERE c.seller_id IN(SELECT seller_id FROM scope)),
 'mediaWriters',(SELECT count(*) FROM treido.media_storage_objects o JOIN treido.personal_seller_owners p ON p.seller_id=o.seller_id WHERE p.user_id=u AND o.state<>'deleted' AND (o.write_until>clock_timestamp() OR o.state='deleting')),
 'assistantRuns',(x->>'assistantRuns')::bigint,'sessionEffects',(SELECT count(*) FROM treido.account_lifecycle_effects WHERE user_id=u AND plan_id IS NULL AND state<>'confirmed'),'legalHolds',(x->>'legalHolds')::bigint) INTO f;
 RETURN f;
END $$;
