export const assistantCopy = {
  en: {
    compatibility: "Compatibility",
    sellHelper: "Sell Helper",
    hub: "Shopping tools",
    compatibilityIntro:
      "Check up to four current listings against the facts you enter about your equipment. Review declared agreements, disagreements and unknowns.",
    compatibilityLimit:
      "These are checks of declared fields, not a fit or safety guarantee. Text similarity is not evidence. Dimensions keep their declared axis order; no rotation or SKU fit is inferred.",
    sellerSource:
      "Source: seller-provided structured fields in the accepted listing publication. A declared manufacturer/catalogue source has not been independently verified.",
    helperIntro:
      "Choose an authorised seller and an existing draft. Review missing facts, edit a proposal, then deliberately apply it to that draft.",
    helperLimit:
      "The helper uses supplied facts and category validation. You confirm every edit. Price, stock, condition, defects, warranty, delivery and publication remain in the ordinary seller review.",
    loading: "Checking current access…",
    guest: "Sign in to keep private checks and proposals.",
    signIn: "Sign in",
    unavailable:
      "This tool is unavailable. Your input and original pending request are retained.",
    denied: "Current account or seller access could not be confirmed.",
    retry: "Retry original request",
    reload: "Reload current state",
    pending:
      "A request has an unknown outcome. Recover this exact request before starting another.",
    storage:
      "Browser recovery storage is unavailable. A new command cannot be submitted until its original request can be retained.",
    saved:
      "The request was acknowledged. Reloaded facts show the current state; an acknowledgement can refer to an earlier revision.",
    CONFLICT:
      "The draft, requirements or listing facts changed. Reload and review a new request.",
    INVALID_INPUT:
      "Review the category, values, units and required confirmations.",
    QUOTA_EXCEEDED:
      "The bounded allowance is exhausted: 20 combined helper/check runs in 24 hours, up to four selections and five proposals per seller.",
    NOT_FOUND: "This item or proposal is no longer available.",
    NOT_AVAILABLE:
      "The service or current facts are unavailable. Retry the retained original request.",
    FORBIDDEN: "Current access to this resource is denied.",
    UNAUTHENTICATED:
      "The session changed. Sign in again with the same account to recover your request.",
    category: "Requirement category",
    requirements: "Equipment requirements",
    use: "Check this field",
    equal: "Exactly declared",
    at_least: "At least",
    at_most: "At most",
    choose: "Choose…",
    yes: "Yes",
    no: "No",
    width: "Width",
    height: "Height",
    depth: "Depth",
    unit: "Unit",
    selectItems: "Select listings",
    listingId: "Listing ID",
    lookup: "Read current listing",
    add: "Select for this check",
    remove: "Remove from next check",
    viewSaved: "Choose saved items",
    emptySaved: "No saved candidates on this page.",
    nextSaved: "More saved items",
    check: "Save reviewed check",
    refresh: "Review and refresh saved evidence",
    clear: "Clear saved requirements and evidence",
    confirmClear: "Clear this saved check?",
    confirmCheck: "I reviewed the requirements and selected current facts.",
    observed: "Saved evidence",
    current: "Current facts",
    changed:
      "Material facts changed. Saved evidence remains observed; review the current facts and explicitly refresh.",
    retired: "The listing is unavailable; saved factual content is hidden.",
    agreement: "Declared agreement",
    disagreement: "Declared disagreement",
    missing: "Not declared",
    incomparable: "Incomparable field",
    unknown: "Unknown",
    declared: "Seller declaration",
    required: "Your requirement",
    checked: "Checked",
    publication: "Publication revision",
    sku: "Representative SKU",
    noSku: "No available representative SKU",
    variantNote:
      "SKU options are shown separately. Listing attributes do not establish that a particular variant fits.",
    reviewRefresh: "Review all current evidence before refreshing",
    confirmRefresh: "Replace observed evidence with these current facts",
    details: "Listing details",
    store: "Seller page",
    cart: "Cart",
    addCart: "Add current SKU to cart",
    saveItem: "Save item",
    actions: "Review ordinary actions",
    noCheck: "No saved check yet. Opening this page does not create one.",
    noSelection:
      "Choose at least one current listing and one supported requirement.",
    seller: "Operating seller",
    draft: "Existing draft",
    loadDraft: "Read selected draft",
    noSellers:
      "No currently authorised seller can edit listings. Open the seller workspace to set one up.",
    noDrafts:
      "No existing drafts in this seller. Create a draft through the ordinary selling flow.",
    workspace: "Seller workspace",
    editor: "Open ordinary draft editor",
    review: "Ordinary publication review",
    title: "Proposed title",
    description: "Proposed description",
    proposedCategory: "Proposed leaf category",
    prepare: "Save editable proposal",
    suggest: "Use supplied facts",
    confirmFacts: "These edits are my accurate seller-provided facts.",
    issues: "Facts to review",
    missingFact: "Missing required fact",
    invalidFact: "Unsupported value",
    confirm_at_review: "Confirm through ordinary seller review",
    before: "Current draft at preparation",
    after: "Proposed edit",
    proposals: "Saved private proposals",
    noProposals: "No private proposal saved for this seller.",
    stale:
      "This proposal was prepared against an older draft. Reopen the current draft and prepare a new proposal.",
    editProposal: "Edit saved proposal",
    useCurrentDraft: "Use current draft as the new edit base",
    accept: "Apply reviewed proposal to draft",
    confirmAccept:
      "I reviewed the exact proposal and confirm this draft edit. This does not publish the item.",
    discard: "Discard private proposal",
    applied: "The original draft save was acknowledged at revision",
    prepared: "Proposal saved; the listing draft has not changed.",
    discarded: "Private proposal discarded; the draft is unchanged.",
    rejected:
      "The original proposal could not be applied because the draft changed. Reopen it for review.",
    priceMinor: "Price",
    locality: "Locality",
    condition: "Condition",
    categoryId: "Leaf category",
    defects: "Known defects",
    handover: "Handover and delivery",
    warranty: "Warranty claims",
    stock: "Inventory and quantity",
    photoRights: "Photo rights and ownership",
    asking: "Observed comparable asking amounts",
    askingNote:
      "Current eligible listings with the same declared brand/model, category and condition. Up to four observations from a bounded result page; amounts are asking prices, not sale values or a suggested price. Shipping remains unknown.",
    insufficient:
      "Insufficient comparable declarations or eligible observations.",
    askingUnavailable: "Comparable asking evidence is unavailable.",
    confirmDiscard: "Discard this private proposal?",
    draftPublished:
      "Published snapshots cannot be edited here. Use ordinary withdrawal/review first.",
  },
  bg: {
    compatibility: "Съвместимост",
    sellHelper: "Помощник за продажба",
    hub: "Инструменти за пазаруване",
    compatibilityIntro:
      "Проверете до четири актуални обяви спрямо въведените данни за вашето оборудване. Разгледайте заявените съвпадения, разминавания и неизвестни данни.",
    compatibilityLimit:
      "Това е проверка на заявени полета, без гаранция за пасване или безопасност. Текстовата прилика не е доказателство. Размерите запазват заявения ред на осите; не се предполага завъртане или пасване на вариант.",
    sellerSource:
      "Източник: структурирани данни от продавача в приетата публикация. Заявеният източник производител/каталог не е независимо проверен.",
    helperIntro:
      "Изберете продавач с текущ достъп и съществуваща чернова. Прегледайте липсите, редактирайте предложение и го приложете изрично към черновата.",
    helperLimit:
      "Помощникът използва предоставени факти и проверка на категорията. Вие потвърждавате редакциите. Цена, наличност, състояние, дефекти, гаранция, доставка и публикуване остават в обичайния преглед за продажба.",
    loading: "Проверяваме текущия достъп…",
    guest: "Влезте, за да запазите лични проверки и предложения.",
    signIn: "Вход",
    unavailable:
      "Инструментът е недостъпен. Въведеното и първоначалната чакаща заявка се запазват.",
    denied: "Текущият профил или достъпът до продавача не е потвърден.",
    retry: "Повтори първоначалната заявка",
    reload: "Зареди текущото състояние",
    pending:
      "Резултатът от заявка е неизвестен. Възстановете точно нея, преди да започнете друга.",
    storage:
      "Паметта на браузъра за възстановяване е недостъпна. Нова команда може да се изпрати само след запазване на първоначалната заявка.",
    saved:
      "Заявката е потвърдена. Заредените данни показват текущото състояние; потвърждението може да е за по-ранна версия.",
    CONFLICT:
      "Черновата, изискванията или данните на обявата са променени. Заредете и прегледайте нова заявка.",
    INVALID_INPUT:
      "Проверете категорията, стойностите, мерните единици и задължителните потвърждения.",
    QUOTA_EXCEEDED:
      "Ограничението е достигнато: общо 20 проверки/предложения за 24 часа, до четири обяви и пет предложения на продавач.",
    NOT_FOUND: "Обявата или предложението вече е недостъпно.",
    NOT_AVAILABLE:
      "Услугата или текущите данни са недостъпни. Повторете запазената първоначална заявка.",
    FORBIDDEN: "Текущият достъп до този ресурс е отказан.",
    UNAUTHENTICATED:
      "Сесията е променена. Влезте отново със същия профил, за да възстановите заявката.",
    category: "Категория на изискванията",
    requirements: "Изисквания за оборудването",
    use: "Провери това поле",
    equal: "Точно заявено",
    at_least: "Поне",
    at_most: "Най-много",
    choose: "Изберете…",
    yes: "Да",
    no: "Не",
    width: "Ширина",
    height: "Височина",
    depth: "Дълбочина",
    unit: "Мерна единица",
    selectItems: "Избор на обяви",
    listingId: "Идентификатор на обява",
    lookup: "Прочети актуална обява",
    add: "Избери за проверката",
    remove: "Премахни от следващата проверка",
    viewSaved: "Избери запазени обяви",
    emptySaved: "Няма запазени обяви на тази страница.",
    nextSaved: "Още запазени обяви",
    check: "Запази прегледаната проверка",
    refresh: "Прегледай и обнови запазените данни",
    clear: "Изчисти запазените изисквания и данни",
    confirmClear: "Да изчистим ли тази запазена проверка?",
    confirmCheck: "Прегледах изискванията и избраните актуални данни.",
    observed: "Запазени данни",
    current: "Текущи данни",
    changed:
      "Има съществена промяна. Запазените данни са предишно наблюдение; прегледайте текущите и ги обновете изрично.",
    retired: "Обявата е недостъпна; запазеното фактическо съдържание е скрито.",
    agreement: "Заявено съвпадение",
    disagreement: "Заявено разминаване",
    missing: "Не е заявено",
    incomparable: "Несъпоставимо поле",
    unknown: "Неизвестно",
    declared: "Заявено от продавача",
    required: "Вашето изискване",
    checked: "Проверено",
    publication: "Версия на публикацията",
    sku: "Представителен вариант",
    noSku: "Няма наличен представителен вариант",
    variantNote:
      "Данните на варианта са отделни. Атрибутите на обявата не доказват, че конкретен вариант пасва.",
    reviewRefresh: "Прегледайте всички текущи данни преди обновяване",
    confirmRefresh: "Замени наблюдението с тези текущи данни",
    details: "Детайли на обявата",
    store: "Страница на продавача",
    cart: "Количка",
    addCart: "Добави актуалния вариант в количката",
    saveItem: "Запази обявата",
    actions: "Прегледай обичайните действия",
    noCheck:
      "Още няма запазена проверка. Отварянето на страницата не създава такава.",
    noSelection:
      "Изберете поне една актуална обява и едно поддържано изискване.",
    seller: "Оперативен продавач",
    draft: "Съществуваща чернова",
    loadDraft: "Прочети избраната чернова",
    noSellers:
      "Няма продавач с текущо право за редакция на обяви. Отворете работното пространство за настройка.",
    noDrafts:
      "Няма съществуващи чернови за този продавач. Създайте чернова чрез обичайния процес за продажба.",
    workspace: "Пространство на продавача",
    editor: "Отвори обичайния редактор",
    review: "Обичаен преглед за публикуване",
    title: "Предложено заглавие",
    description: "Предложено описание",
    proposedCategory: "Предложена крайна категория",
    prepare: "Запази редактируемо предложение",
    suggest: "Използвай предоставените факти",
    confirmFacts: "Тези редакции са мои точни факти като продавач.",
    issues: "Данни за преглед",
    missingFact: "Липсва задължителен факт",
    invalidFact: "Неподдържана стойност",
    confirm_at_review: "Потвърдете в обичайния преглед за продажба",
    before: "Чернова при подготовката",
    after: "Предложена редакция",
    proposals: "Запазени лични предложения",
    noProposals: "Няма запазено лично предложение за този продавач.",
    stale:
      "Предложението е за по-стара чернова. Отворете текущата и подгответе ново предложение.",
    editProposal: "Редактирай запазеното предложение",
    useCurrentDraft: "Използвай текущата чернова като нова основа",
    accept: "Приложи прегледаното предложение към черновата",
    confirmAccept:
      "Прегледах точното предложение и потвърждавам редакцията на черновата. Това не публикува обявата.",
    discard: "Отхвърли личното предложение",
    applied: "Първоначалното запазване на черновата е потвърдено с версия",
    prepared: "Предложението е запазено; черновата на обявата не е променена.",
    discarded: "Личното предложение е отхвърлено; черновата е непроменена.",
    rejected:
      "Първоначалното предложение не е приложено, защото черновата е променена. Отворете я за преглед.",
    priceMinor: "Цена",
    locality: "Населено място",
    condition: "Състояние",
    categoryId: "Крайна категория",
    defects: "Известни дефекти",
    handover: "Предаване и доставка",
    warranty: "Заявени гаранции",
    stock: "Наличност и количество",
    photoRights: "Права върху снимките и собственост",
    asking: "Наблюдавани сравними обявени цени",
    askingNote:
      "Текущи допустими обяви със същите заявени марка/модел, категория и състояние. До четири наблюдения от ограничена страница; това са обявени цени, а не продажни стойности или предложена цена. Доставката остава неизвестна.",
    insufficient: "Недостатъчни сравними декларации или допустими наблюдения.",
    askingUnavailable: "Сравнимите обявени цени са недостъпни.",
    confirmDiscard: "Да отхвърлим ли личното предложение?",
    draftPublished:
      "Публикуваните обяви не могат да се редактират тук. Използвайте обичайното оттегляне и преглед.",
  },
} as const;
export type AssistantLocale = keyof typeof assistantCopy;
export type AssistantCopy = typeof assistantCopy.en | typeof assistantCopy.bg;
