/** Observed report labels. These entries describe unavailable analytics, not sample data. */
export const additionalReportPresets = [
  [
    "conversion-time",
    "Conversion rate over time",
    "Реализации във времето",
    "Behavior",
  ],
  [
    "recommendation-conversion",
    "Product recommendation conversions over time",
    "Реализации от препоръки за продукти",
    "Behavior",
  ],
  [
    "recommendation-low",
    "Product recommendations with low engagement",
    "Препоръки за продукти с ниска ангажираност",
    "Behavior",
  ],
  [
    "search-conversion",
    "Search conversions over time",
    "Реализации от търсене във времето",
    "Behavior",
  ],
  [
    "search-query",
    "Searches by search query",
    "Търсения по заявка",
    "Behavior",
  ],
  [
    "search-no-clicks",
    "Searches with no clicks",
    "Търсения без кликвания",
    "Behavior",
  ],
  [
    "search-no-results",
    "Searches with no results",
    "Търсения без резултати",
    "Behavior",
  ],
  [
    "sessions-device",
    "Sessions by device type",
    "Сесии по вид устройство",
    "Behavior",
  ],
  [
    "sessions-landing",
    "Sessions by landing page",
    "Сесии по начална страница",
    "Behavior",
  ],
  [
    "campaign-roas",
    "Campaign return on ad spend",
    "Възвръщаемост на разходите за реклама",
    "Behavior",
  ],
  [
    "agent-sessions",
    "Storefront agent assisted sessions",
    "Сесии с помощ от агент на магазина",
    "Behavior",
  ],
  [
    "agent-feedback",
    "Storefront agent conversations and feedback",
    "Разговори и отзиви за агента на магазина",
    "Behavior",
  ],
  [
    "customer-cohort",
    "Customer cohort analysis",
    "Анализ на клиентски групи",
    "Customers",
  ],
  [
    "customer-location",
    "Customers by location",
    "Клиенти по местоположение",
    "Customers",
  ],
  [
    "new-customer-sales",
    "New customer sales over time",
    "Продажби на нови клиенти във времето",
    "Customers",
  ],
  [
    "new-customers-time",
    "New customers over time",
    "Нови клиенти във времето",
    "Customers",
  ],
  [
    "new-returning",
    "New vs returning customers",
    "Нови и завръщащи се клиенти",
    "Customers",
  ],
  [
    "one-time-customers",
    "One-time customers",
    "Еднократни клиенти",
    "Customers",
  ],
  [
    "predicted-spend",
    "Predicted spend tiers",
    "Прогнозни нива на разходите",
    "Customers",
  ],
  [
    "returning-rate",
    "Returning customer rate over time",
    "Дял на завръщащи се клиенти във времето",
    "Customers",
  ],
  [
    "returning-customers",
    "Returning customers",
    "Завръщащи се клиенти",
    "Customers",
  ],
  [
    "rfm-analysis",
    "RFM customer analysis",
    "RFM анализ на клиентите",
    "Customers",
  ],
  ["rfm-list", "RFM customer list", "RFM списък с клиенти", "Customers"],
  [
    "chargeback-rate",
    "Chargeback rate",
    "Дял на оспорени плащания",
    "Finances",
  ],
  [
    "cost-by-order",
    "Cost of goods sold by order",
    "Себестойност на продадените стоки по поръчка",
    "Finances",
  ],
  ["discounts-order", "Discounts by order", "Отстъпки по поръчка", "Finances"],
  ["finance-summary", "Finance summary", "Финансово обобщение", "Finances"],
  [
    "gross-provider",
    "Gross payments from payment provider",
    "Брутни плащания от доставчика",
    "Finances",
  ],
  [
    "gross-profit-breakdown",
    "Gross profit breakdown",
    "Разпределение на брутната печалба",
    "Finances",
  ],
  [
    "gross-profit-order",
    "Gross profit by order",
    "Брутна печалба по поръчка",
    "Finances",
  ],
  [
    "gross-sales-order",
    "Gross sales by order",
    "Брутни продажби по поръчка",
    "Finances",
  ],
  [
    "market-taxes",
    "Managed market taxes",
    "Данъци за управлявани пазари",
    "Finances",
  ],
  [
    "net-payments-gateway",
    "Net payments by gateway",
    "Нетни плащания по доставчик",
    "Finances",
  ],
  [
    "net-payments-method",
    "Net payments by method",
    "Нетни плащания по метод",
    "Finances",
  ],
  [
    "net-payments-order",
    "Net payments by order",
    "Нетни плащания по поръчка",
    "Finances",
  ],
  [
    "net-payments-time",
    "Net payments over time",
    "Нетни плащания във времето",
    "Finances",
  ],
  [
    "net-sales-order",
    "Net sales by order",
    "Нетни продажби по поръчка",
    "Finances",
  ],
  [
    "net-gift-sales",
    "Net sales from gift cards",
    "Нетни продажби от подаръчни карти",
    "Finances",
  ],
  [
    "net-sales-cost",
    "Net sales with cost by order",
    "Нетни продажби със себестойност по поръчка",
    "Finances",
  ],
] as const;

/** Remaining observed directory pages; provider labels are adapted to Treido. */
export const remainingReportPresets = [
  [
    "finances-net-sales-without-cost-by-order",
    "Net sales without cost by order",
    "Нетни продажби без себестойност по поръчка",
    "Finances",
  ],
  [
    "finances-outstanding-gift-card-balance",
    "Outstanding gift card balance",
    "Остатък по подаръчни карти",
    "Finances",
  ],
  [
    "finances-outstanding-store-credit-balance",
    "Outstanding store credit balance",
    "Остатък по кредит в магазина",
    "Finances",
  ],
  [
    "finances-payments-by-gateway-summary",
    "Payments by gateway summary",
    "Обобщение на плащанията по доставчик",
    "Finances",
  ],
  [
    "finances-payouts-over-time",
    "Payouts over time",
    "Изплащания във времето",
    "Finances",
  ],
  [
    "finances-referral-orders",
    "Referral orders",
    "Поръчки от препоръки",
    "Finances",
  ],
  [
    "finances-referral-sales",
    "Referral sales",
    "Продажби от препоръки",
    "Finances",
  ],
  [
    "finances-shipping-by-order",
    "Shipping by order",
    "Доставка по поръчка",
    "Finances",
  ],
  [
    "finances-shop-channel-orders",
    "Storefront channel orders",
    "Поръчки от канала на магазина",
    "Finances",
  ],
  [
    "finances-shop-pay-payments",
    "Wallet payments",
    "Плащания с портфейл",
    "Finances",
  ],
  [
    "finances-shop-pay-transactions",
    "Wallet transactions",
    "Транзакции с портфейл",
    "Finances",
  ],
  [
    "finances-shop-payments-by-type",
    "Storefront payments by type",
    "Плащания на магазина по вид",
    "Finances",
  ],
  [
    "finances-store-credit-transactions",
    "Store credit transactions",
    "Транзакции с кредит в магазина",
    "Finances",
  ],
  ["finances-taxes", "Taxes", "Данъци", "Finances"],
  [
    "finances-tips-by-staff-member",
    "Tips by staff member",
    "Бакшиши по служител",
    "Finances",
  ],
  [
    "finances-total-sales-breakdown",
    "Total sales breakdown",
    "Разпределение на общите продажби",
    "Finances",
  ],
  [
    "finances-total-sales-by-order",
    "Total sales by order",
    "Общи продажби по поръчка",
    "Finances",
  ],
  [
    "finances-total-sales-reversals-by-order",
    "Total sales reversals by order",
    "Общи сторнирания по поръчка",
    "Finances",
  ],
  [
    "fraud-acceptance-rate",
    "Acceptance rate",
    "Дял на приетите поръчки",
    "Fraud",
  ],
  [
    "fraud-canceled-due-to-fraud",
    "Canceled due to fraud",
    "Отменени заради измама",
    "Fraud",
  ],
  [
    "fraud-chargeback-amount-fraud",
    "Chargeback amount (fraud)",
    "Сума на оспорванията за измама",
    "Fraud",
  ],
  [
    "fraud-chargeback-rate-fraud",
    "Chargeback rate (fraud)",
    "Дял на оспорванията за измама",
    "Fraud",
  ],
  [
    "fraud-high-risk-orders-rate",
    "High risk orders rate",
    "Дял на поръчките с висок риск",
    "Fraud",
  ],
  [
    "fraud-orders-covered-by-shopify-protect",
    "Orders covered by provider protection",
    "Поръчки с покритие от доставчика",
    "Fraud",
  ],
  [
    "fraud-orders-protected-by-shopify-protect",
    "Orders protected by provider protection",
    "Поръчки със защита от доставчика",
    "Fraud",
  ],
  [
    "inventory-abc-product-analysis",
    "ABC product analysis",
    "ABC анализ на продуктите",
    "Inventory",
  ],
  [
    "inventory-acceptance-rate",
    "Acceptance rate",
    "Дял на приетите прехвърляния",
    "Inventory",
  ],
  [
    "inventory-inventory-adjustment-changes",
    "Inventory adjustment changes",
    "Промени в корекциите на наличността",
    "Inventory",
  ],
  [
    "inventory-inventory-adjustments-by-count",
    "Inventory adjustments by count",
    "Корекции на наличността по брой",
    "Inventory",
  ],
  [
    "inventory-inventory-sold-daily-by-product",
    "Inventory sold daily by product",
    "Продадена наличност на ден по продукт",
    "Inventory",
  ],
  [
    "inventory-inventory-transfer-orders-and-shipments",
    "Inventory transfer orders and shipments",
    "Поръчки и пратки за прехвърляне",
    "Inventory",
  ],
  [
    "inventory-inventory-transfers",
    "Inventory transfers",
    "Прехвърляния на наличност",
    "Inventory",
  ],
  [
    "inventory-month-end-inventory-snapshot",
    "Month-end inventory snapshot",
    "Наличност в края на месеца",
    "Inventory",
  ],
  [
    "inventory-month-end-inventory-value",
    "Month-end inventory value",
    "Стойност на наличността в края на месеца",
    "Inventory",
  ],
  [
    "inventory-products-by-days-of-inventory-remaining",
    "Products by days of inventory remaining",
    "Продукти по дни оставаща наличност",
    "Inventory",
  ],
  [
    "inventory-products-by-percentage-sold",
    "Products by percentage sold",
    "Продукти по продаден процент",
    "Inventory",
  ],
  [
    "inventory-products-by-sell-through-rate",
    "Products by sell-through rate",
    "Продукти по дял на реализирана наличност",
    "Inventory",
  ],
  ["inventory-total-ordered", "Total ordered", "Общо поръчано", "Inventory"],
  ["inventory-total-received", "Total received", "Общо получено", "Inventory"],
  ["inventory-total-shipped", "Total shipped", "Общо изпратено", "Inventory"],
  [
    "inventory-transfers-received-items",
    "Transfers received items",
    "Получени артикули от прехвърляния",
    "Inventory",
  ],
  ["inventory-unique-skus", "Unique SKUs", "Уникални SKU", "Inventory"],
  [
    "marketing-performance-by-autopilot-marketing-activities",
    "Performance by Autopilot Marketing Activities",
    "Представяне на автоматичните маркетингови дейности",
    "Marketing",
  ],
  [
    "marketing-performance-by-marketing-campaign",
    "Performance by marketing campaign",
    "Представяне по маркетингова кампания",
    "Marketing",
  ],
  [
    "marketing-performance-by-marketing-channel",
    "Performance by marketing channel",
    "Представяне по маркетингов канал",
    "Marketing",
  ],
  [
    "marketing-shop-channel-product-impressions",
    "Storefront channel product impressions",
    "Показвания на продукти в канала на магазина",
    "Marketing",
  ],
  [
    "orders-delivery-predictability",
    "Delivery predictability",
    "Предвидимост на доставката",
    "Orders",
  ],
  [
    "orders-fulfillment-to-delivery-time",
    "Fulfillment to delivery time",
    "Време от изпълнение до доставка",
    "Orders",
  ],
  [
    "orders-items-bought-together",
    "Items bought together",
    "Продукти, купувани заедно",
    "Orders",
  ],
  [
    "orders-items-ordered-over-time",
    "Items ordered over time",
    "Поръчани артикули във времето",
    "Orders",
  ],
  [
    "orders-items-reversed-by-product",
    "Items reversed by product",
    "Сторнирани артикули по продукт",
    "Orders",
  ],
  [
    "orders-median-fulfillment-duration-by-order-hour",
    "Median fulfillment duration by order hour",
    "Медианно време за изпълнение по час на поръчката",
    "Orders",
  ],
  [
    "orders-on-time-delivery-by-carrier",
    "On-time delivery by carrier",
    "Навременна доставка по превозвач",
    "Orders",
  ],
  [
    "orders-order-to-fulfillment-time",
    "Order to fulfillment time",
    "Време от поръчка до изпълнение",
    "Orders",
  ],
  [
    "orders-order-to-shipping-time",
    "Order-to-shipping time",
    "Време от поръчка до изпращане",
    "Orders",
  ],
  [
    "orders-orders-and-reversed-quantity-by-product",
    "Orders and reversed quantity by product",
    "Поръчки и сторнирано количество по продукт",
    "Orders",
  ],
  [
    "orders-orders-delivered-over-time",
    "Orders delivered over time",
    "Доставени поръчки във времето",
    "Orders",
  ],
  [
    "orders-orders-fulfilled-over-time",
    "Orders fulfilled over time",
    "Изпълнени поръчки във времето",
    "Orders",
  ],
  [
    "orders-orders-over-time",
    "Orders over time",
    "Поръчки във времето",
    "Orders",
  ],
  [
    "orders-orders-with-tracking-included",
    "Orders with tracking included",
    "Поръчки с проследяване",
    "Orders",
  ],
  [
    "orders-reversed-quantity-over-time",
    "Reversed quantity over time",
    "Сторнирано количество във времето",
    "Orders",
  ],
  [
    "orders-reversed-quantity-rate-over-time",
    "Reversed quantity rate over time",
    "Дял на сторнираното количество във времето",
    "Orders",
  ],
  [
    "orders-shipments-with-predictable-delivery",
    "Shipments with predictable delivery",
    "Пратки с предвидима доставка",
    "Orders",
  ],
  [
    "orders-shipping-and-delivery-performance",
    "Shipping and delivery performance",
    "Представяне на изпращането и доставката",
    "Orders",
  ],
  [
    "orders-shipping-labels-by-order",
    "Shipping labels by order",
    "Етикети за доставка по поръчка",
    "Orders",
  ],
  [
    "orders-shipping-labels-over-time",
    "Shipping labels over time",
    "Етикети за доставка във времето",
    "Orders",
  ],
  [
    "orders-shop-promise-coverage-by-product-category",
    "Delivery promise coverage by product category",
    "Покритие на обещаната доставка по категория",
    "Orders",
  ],
  [
    "orders-shop-promise-eligibility-by-product-subcategory",
    "Delivery promise eligibility by product subcategory",
    "Допустимост за обещана доставка по подкатегория",
    "Orders",
  ],
  [
    "orders-shop-promise-tracking-readiness",
    "Delivery promise tracking readiness",
    "Готовност за проследяване на обещаната доставка",
    "Orders",
  ],
  [
    "orders-top-returned-products-with-reasons",
    "Top returned products with reasons",
    "Най-връщани продукти с причини",
    "Orders",
  ],
  [
    "performance-cumulative-layout-shift-cls-over-time",
    "Cumulative Layout Shift (CLS): Over Time",
    "Изместване на оформлението (CLS) във времето",
    "Performance",
  ],
  [
    "performance-cumulative-layout-shift-cls-page-type",
    "Cumulative Layout Shift (CLS): Page Type",
    "Изместване на оформлението (CLS) по вид страница",
    "Performance",
  ],
  [
    "performance-cumulative-layout-shift-cls-page-url",
    "Cumulative Layout Shift (CLS): Page URL",
    "Изместване на оформлението (CLS) по URL",
    "Performance",
  ],
  [
    "performance-interaction-to-next-paint-inp-over-time",
    "Interaction to Next Paint (INP): Over Time",
    "Отзивчивост при взаимодействие (INP) във времето",
    "Performance",
  ],
  [
    "performance-interaction-to-next-paint-inp-page-type",
    "Interaction to Next Paint (INP): Page Type",
    "Отзивчивост при взаимодействие (INP) по вид страница",
    "Performance",
  ],
  [
    "performance-interaction-to-next-paint-inp-page-url",
    "Interaction to Next Paint (INP): Page URL",
    "Отзивчивост при взаимодействие (INP) по URL",
    "Performance",
  ],
  [
    "performance-largest-contentful-paint-lcp-over-time",
    "Largest Contentful Paint (LCP): Over Time",
    "Зареждане на основното съдържание (LCP) във времето",
    "Performance",
  ],
  [
    "performance-largest-contentful-paint-lcp-page-type",
    "Largest Contentful Paint (LCP): Page Type",
    "Зареждане на основното съдържание (LCP) по вид страница",
    "Performance",
  ],
  [
    "performance-largest-contentful-paint-lcp-page-url",
    "Largest Contentful Paint (LCP): Page URL",
    "Зареждане на основното съдържание (LCP) по URL",
    "Performance",
  ],
  [
    "profit-margin-gross-profit-by-pos-location",
    "Gross profit by POS location",
    "Брутна печалба по POS локация",
    "Profit Margin",
  ],
  [
    "profit-margin-gross-profit-by-product",
    "Gross profit by product",
    "Брутна печалба по продукт",
    "Profit Margin",
  ],
  [
    "profit-margin-gross-profit-by-product-variant",
    "Gross profit by product variant",
    "Брутна печалба по вариант на продукт",
    "Profit Margin",
  ],
  [
    "retail-sales-pos-staff-daily-sales-total",
    "POS staff daily sales total",
    "Общи дневни POS продажби по служител",
    "Retail Sales",
  ],
  [
    "retail-sales-pos-staff-sales-total",
    "POS staff sales total",
    "Общи POS продажби по служител",
    "Retail Sales",
  ],
  [
    "retail-sales-pos-total-sales-by-product",
    "POS total sales by product",
    "Общи POS продажби по продукт",
    "Retail Sales",
  ],
  [
    "retail-sales-pos-total-sales-by-product-type",
    "POS total sales by product type",
    "Общи POS продажби по вид продукт",
    "Retail Sales",
  ],
  [
    "retail-sales-pos-total-sales-by-product-variant",
    "POS total sales by product variant",
    "Общи POS продажби по вариант",
    "Retail Sales",
  ],
  [
    "retail-sales-pos-total-sales-by-staff-member",
    "POS total sales by staff member",
    "Общи POS продажби по служител",
    "Retail Sales",
  ],
  [
    "retail-sales-pos-total-sales-by-vendor",
    "POS total sales by vendor",
    "Общи POS продажби по доставчик",
    "Retail Sales",
  ],
  [
    "retail-sales-total-sales-by-pos-location",
    "Total sales by POS location",
    "Общи продажби по POS локация",
    "Retail Sales",
  ],
  [
    "sales-active-subscriptions-over-time",
    "Active subscriptions over time",
    "Активни абонаменти във времето",
    "Sales",
  ],
  [
    "sales-agentic-total-sales-by-referring-channel",
    "Agentic total sales by referring channel",
    "Общи AI продажби по препращащ канал",
    "Sales",
  ],
  [
    "sales-agentic-total-sales-over-time",
    "Agentic total sales over time",
    "Общи AI продажби във времето",
    "Sales",
  ],
  [
    "sales-average-order-quantity-over-time",
    "Average order quantity over time",
    "Средно количество в поръчка във времето",
    "Sales",
  ],
  [
    "sales-average-order-value-over-time",
    "Average order value over time",
    "Средна стойност на поръчка във времето",
    "Sales",
  ],
  [
    "sales-average-profit-margin-by-market",
    "Average profit margin by market",
    "Среден марж на печалба по пазар",
    "Sales",
  ],
  [
    "sales-bundle-item-versus-non-bundle-sales",
    "Bundle item versus non-bundle sales",
    "Продажби на комплекти спрямо отделни артикули",
    "Sales",
  ],
  [
    "sales-bundle-total-sales-over-time",
    "Bundle total sales over time",
    "Общи продажби на комплекти във времето",
    "Sales",
  ],
  [
    "sales-canceled-subscriptions-over-time",
    "Canceled subscriptions over time",
    "Отменени абонаменти във времето",
    "Sales",
  ],
  [
    "sales-gross-sales-by-sales-channel",
    "Gross sales by sales channel",
    "Брутни продажби по канал",
    "Sales",
  ],
  [
    "sales-gross-sales-over-time",
    "Gross sales over time",
    "Брутни продажби във времето",
    "Sales",
  ],
  [
    "sales-items-sold-by-referrer",
    "Items sold by referrer",
    "Продадени артикули по източник",
    "Sales",
  ],
  [
    "sales-net-sales-by-sales-channel",
    "Net sales by sales channel",
    "Нетни продажби по канал",
    "Sales",
  ],
  [
    "sales-net-sales-over-time",
    "Net sales over time",
    "Нетни продажби във времето",
    "Sales",
  ],
  [
    "sales-new-subscriptions-over-time",
    "New subscriptions over time",
    "Нови абонаменти във времето",
    "Sales",
  ],
  [
    "sales-new-vs-returning-customer-sales",
    "New vs returning customer sales",
    "Продажби на нови и завръщащи се клиенти",
    "Sales",
  ],
  [
    "sales-new-vs-returning-customers-over-time",
    "New vs returning customers over time",
    "Нови и завръщащи се клиенти във времето",
    "Sales",
  ],
  [
    "sales-pos-staff-orders-total",
    "POS staff orders total",
    "Общи поръчки по POS служител",
    "Sales",
  ],
  [
    "sales-profit-margin-by-order",
    "Profit margin by order",
    "Марж на печалба по поръчка",
    "Sales",
  ],
  [
    "sales-sales-by-customer-name",
    "Sales by customer name",
    "Продажби по име на клиент",
    "Sales",
  ],
  [
    "sales-sales-by-discount-codes",
    "Sales by discount codes",
    "Продажби по код за отстъпка",
    "Sales",
  ],
  [
    "sales-sales-reversals-over-time",
    "Sales reversals over time",
    "Сторнирани продажби във времето",
    "Sales",
  ],
  [
    "sales-subscription-vs-one-time-sales",
    "Subscription vs one-time sales",
    "Абонаментни спрямо еднократни продажби",
    "Sales",
  ],
  [
    "sales-subscriptions-sales-over-time",
    "Subscriptions sales over time",
    "Абонаментни продажби във времето",
    "Sales",
  ],
  [
    "sales-top-product-variants-by-units-sold",
    "Top product variants by units sold",
    "Най-продавани варианти по брой",
    "Sales",
  ],
  [
    "sales-total-sales-by-billing-location",
    "Total sales by billing location",
    "Общи продажби по адрес за фактуриране",
    "Sales",
  ],
  [
    "sales-total-sales-by-bundle",
    "Total sales by bundle",
    "Общи продажби по комплект",
    "Sales",
  ],
  [
    "sales-total-sales-by-bundle-component",
    "Total sales by bundle component",
    "Общи продажби по част от комплект",
    "Sales",
  ],
  [
    "sales-total-sales-by-currency",
    "Total sales by currency",
    "Общи продажби по валута",
    "Sales",
  ],
  [
    "sales-total-sales-by-product",
    "Total sales by product",
    "Общи продажби по продукт",
    "Sales",
  ],
  [
    "sales-total-sales-by-product-variant",
    "Total sales by product variant",
    "Общи продажби по вариант на продукт",
    "Sales",
  ],
  [
    "sales-total-sales-by-referrer",
    "Total sales by referrer",
    "Общи продажби по източник",
    "Sales",
  ],
  [
    "sales-total-sales-by-sales-channel",
    "Total sales by sales channel",
    "Общи продажби по канал",
    "Sales",
  ],
  [
    "sales-total-sales-by-social-referrer",
    "Total sales by social referrer",
    "Общи продажби по социален източник",
    "Sales",
  ],
  [
    "sales-total-sales-by-vendor",
    "Total sales by vendor",
    "Общи продажби по доставчик",
    "Sales",
  ],
  [
    "sales-total-sales-over-time",
    "Total sales over time",
    "Общи продажби във времето",
    "Sales",
  ],
  [
    "sales-total-sales-reversals-over-time",
    "Total sales reversals over time",
    "Общи сторнирания във времето",
    "Sales",
  ],
  [
    "sales-weekly-sales-patterns",
    "Weekly sales patterns",
    "Седмични модели на продажбите",
    "Sales",
  ],
] as const;
