/** English metric names observed in the authorized Shopify reference. Unsupported metrics stay unavailable. */
export const reportMetricReference = [
  {
    category: "App Events",
    labels: ["Last app event date", "Total app events"],
  },
  {
    category: "Customers",
    labels: [
      "Days since last order",
      "New customer records",
      "Percent of customers",
      "Total amount spent",
      "Total amount spent per order",
      "Total number of orders",
    ],
  },
  {
    category: "Finance and payments",
    labels: [
      "Adjusted gift card value",
      "Average foreign exchange fees",
      "Average international fees",
      "Average Managed Markets fees",
      "Average payment processing fees",
      "Cash rounding",
      "Chargeback amount",
      "Chargeback rate",
      "Chargebacks",
      "Credited store credit",
      "Debited store credit",
      "Disabled gift card value",
      "Ending gift card balance",
      "Ending store credit balance",
      "Expired store credit",
      "Failed payment attempts",
      "Foreign exchange fees",
      "Gift card balance net change",
      "Gift cards adjusted",
      "Gift cards disabled",
      "Gift cards issued",
      "Gross amount",
      "Gross payments",
      "Included tax amount",
      "International fees",
      "Issued gift card balance",
      "Managed Markets fees",
      "Managed Markets taxes",
      "Net amount",
      "Net payments",
      "Net payments excluding gift cards",
      "Orders with transactions",
      "Payment authorization rate",
      "Payment authorization rate (raw)",
      "Payment processing fees",
      "Payout amount",
      "Payout amount in payout currency",
      "Pricing adjustment value",
      "Redeemed gift card value",
      "Refunded gift card value",
      "Refunded payments",
      "Rounded net payments",
      "Sales taxes",
      "Sold gift card balance",
      "Starting gift card balance",
      "Starting store credit balance",
      "Store credit balance net change",
      "Successful payments",
      "Total payment attempts",
      "Transaction amount",
      "Transaction count",
      "Transactions",
      "Unique payment attempts",
    ],
  },
  {
    category: "Fraud prevention",
    labels: [
      "Acceptable fraud risk rate",
      "Checkout impact rate",
      "Checkouts impacted decision rules",
      "Fraudulent chargeback rate",
      "Fraudulent chargebacks",
      "High fraud risk rate",
      "Successful transactions",
      "Value impacted by decision rules",
    ],
  },
  {
    category: "Inventory",
    labels: [
      "Acceptance rate",
      "Accepted quantity",
      "Days in inventory",
      "Days in inventory (at location)",
      "Days in stock",
      "Days in stock (at location)",
      "Days of inventory remaining",
      "Days of inventory remaining (at location)",
      "Days out of stock",
      "Days out of stock (at location)",
      "Ending inventory retail value",
      "Ending inventory retail value (at location)",
      "Ending inventory units",
      "Ending inventory units (at location)",
      "Ending inventory value",
      "Ending inventory value (at location)",
      "First day in inventory",
      "First day in inventory (at location)",
      "Inventory adjustment change",
      "Inventory adjustment count",
      "Inventory units net change (at location)",
      "Inventory units sold",
      "Inventory units sold per day",
      "Last day in inventory",
      "Last day in inventory (at location)",
      "Ordered quantity",
      "Percent of inventory sold",
      "Received item quantity",
      "Received items",
      "Received quantity",
      "Rejected quantity",
      "Rejection rate",
      "Sell-through rate",
      "Shipments",
      "Shipped quantity",
      "Starting inventory units",
      "Starting inventory units (at location)",
      "Transfer line items",
      "Transfers",
      "Unique items shipped",
      "Unique items transferred",
    ],
  },
  {
    category: "Marketing",
    labels: [
      "Ad impressions",
      "Ad spend",
      "Average customer acquisition cost",
      "Clicks",
      "Commissions",
      "Delivery failures",
      "First-time customers (reported)",
      "Impressions",
      "Network purchases",
      "Orders (reported)",
      "Page views with ads",
      "Product network clicks",
      "Returning customers (reported)",
      "Sales (reported)",
      "Sends",
      "Shop Campaign ad spend",
      "Shop Campaign average order value",
      "Shop campaign credits earned",
      "Shop Campaign customers",
      "Shop Campaign orders",
      "Shop Campaign return on ad spend",
      "Shop Campaign sales",
      "Spam complaints",
      "Unique clicks",
      "Unique views",
      "Unsubscribes",
    ],
  },
  {
    category: "Orders",
    labels: [
      "Assisted orders",
      "Average cost of goods sold",
      "Average customer duties and import taxes",
      "Average customer price adjustments",
      "Average customer shipping charges",
      "Average duty and import tax adjustment costs",
      "Average profit at delivery (before returns)",
      "Average revenue (before returns)",
      "Average sale after discounts",
      "Average sales taxes",
      "Average shipping label adjustment costs",
      "Average shipping label cost",
      "Average store costs (before returns)",
      "Average store duties and import taxes",
      "Average store shipping costs",
      "Collective orders",
      "Collective orders fulfilled",
      "Collective orders received",
      "Delivery predictability",
      "First click average order quantity",
      "First click net items sold",
      "First click order count",
      "First click total average order value",
      "First click total sales",
      "Fulfillments for Shop Promise evaluation",
      "Last click average order quantity",
      "Last click net items sold",
      "Last click order count",
      "Last click total average order value",
      "Last click total sales",
      "Last non-direct click average order quantity",
      "Last non-direct click net items sold",
      "Last non-direct click order count",
      "Last non-direct click total average order value",
      "Last non-direct click total sales",
      "Linear average order quantity",
      "Linear net items sold",
      "Linear order count",
      "Linear total average order value",
      "Linear total sales",
      "Median days fulfillment to shipping",
      "Median days order to delivery",
      "Median days order to fulfillment",
      "Median days order to shipping",
      "Median days shipping to delivery",
      "Median fulfillment duration by order hour",
      "Median hours fulfillment to shipping",
      "Median hours order to delivery",
      "Median hours order to shipping",
      "Median hours shipping to delivery",
      "Median time to fulfillment",
      "On-time delivery rate",
      "On-time shipments",
      "Orders",
      "Orders delivered",
      "Orders fulfilled",
      "Orders in window",
      "Orders shipped",
      "Shipments delivered",
      "Shipments in window",
      "Shipments with a delivery prediction",
      "Shipping label costs",
      "Shipping labels",
      "Shop Promise tracking readiness",
      "Tracked orders",
      "Tracking included rate",
      "Tracking readiness rate",
    ],
  },
  {
    category: "Products",
    labels: [
      "Collective clicks",
      "Collective impressions",
      "Delivery range",
      "Products",
      "Shop Promise coverage rate",
      "Status",
      "Target delivery range",
    ],
  },
  {
    category: "Sales revenue",
    labels: [
      "Active subscriptions",
      "Additional fees",
      "Additional product and order discounts",
      "Additional shipping discounts",
      "Amount spent per customer",
      "Applied discounts",
      "Average order value",
      "Bundles ordered",
      "Collective earnings",
      "Collective gross profit",
      "Collective total sales",
      "Cost of goods sold",
      "Customers",
      "Discounted orders",
      "Discount reversals",
      "Discounts",
      "Duties",
      "Gift card discounts",
      "Gift card gross sales",
      "Gift card net sales",
      "Gift card taxes",
      "Gross margin",
      "Gross profit",
      "Gross sales",
      "Gross sales reversals",
      "Gross shipping charges",
      "Line item discounts",
      "Net items sold",
      "Net sales",
      "Net sales reversals",
      "Net sales with cost recorded",
      "Net sales without cost recorded",
      "New customers",
      "Number of orders per customer",
      "Order-level discounts",
      "Order sale agreements",
      "Orders (first-time)",
      "Orders (returning)",
      "Product and order discounts",
      "Product and order discounts from apps",
      "Quantity ordered",
      "Quantity ordered per order",
      "Rate of staff-assisted sales",
      "Returned quantity",
      "Return fees",
      "Returning customer rate",
      "Returning customers",
      "Reversed quantity",
      "Reversed quantity rate",
      "Sales reversals",
      "Shipping charge discounts",
      "Shipping charges",
      "Shipping charge taxes",
      "Shipping discounts",
      "Shipping discounts from apps",
      "Shipping reversals",
      "Shop Mini orders",
      "Shop Mini sales",
      "Shop post-purchase orders",
      "Shop post-purchase sales",
      "Subscriptions added",
      "Subscriptions canceled",
      "Taxes",
      "Taxes excluding gift cards",
      "Tax reversals",
      "Tips",
      "Total sales",
      "Total sales (first-time)",
      "Total sales (returning)",
      "Total sales reversals",
      "Total shipping charges",
    ],
  },
  {
    category: "Sessions and behavior",
    labels: [
      "Added to cart rate",
      "Assisted sessions",
      "Average session duration",
      "Bounce rate",
      "Bounces",
      "Campaign added to cart rate",
      "Campaign-associated store pageviews per session",
      "Campaign average session duration",
      "Campaign bounce rate",
      "Campaign bounces",
      "Campaign checkout conversion rate",
      "Campaign completed checkout rate",
      "Campaign conversion rate",
      "Campaign online store visitors",
      "Campaign pageviews",
      "Campaign reached checkout rate",
      "Campaign sessions",
      "Campaign sessions that completed checkout",
      "Campaign sessions that reached and completed checkout",
      "Campaign sessions that reached checkout",
      "Campaign sessions with cart additions",
      "Checkout conversion rate",
      "CLS distribution",
      "CLS good view count",
      "CLS okay view count",
      "CLS P50",
      "CLS P75",
      "CLS P90",
      "CLS P99",
      "CLS poor view count",
      "Collections viewed",
      "Completed checkout rate",
      "Conversations",
      "Conversion rate",
      "FCP distribution",
      "FCP good view count",
      "FCP okay view count",
      "FCP P50",
      "FCP P75",
      "FCP P90",
      "FCP P99",
      "FCP poor view count",
      "Form conversion rate",
      "Form submissions",
      "Form views",
      "Global search requests",
      "INP distribution",
      "INP good view count",
      "INP okay view count",
      "INP P50",
      "INP P75",
      "INP P90",
      "INP P99",
      "INP poor view count",
      "LCP distribution",
      "LCP good view count",
      "LCP okay view count",
      "LCP P50",
      "LCP P75",
      "LCP P90",
      "LCP P99",
      "LCP poor view count",
      "Online store visitors",
      "Orders",
      "Page loads",
      "Pageviews",
      "Pageviews per session",
      "Percent of page loads",
      "Product recommendation added to cart rate",
      "Product recommendation click rate",
      "Product recommendation conversion rate",
      "Product recommendation low click rate",
      "Product recommendation performance gap",
      "Product recommendation sessions that completed checkout",
      "Product recommendation sessions with cart additions",
      "Product recommendation sessions with clicks",
      "Products added to cart",
      "Products in started checkouts",
      "Products purchased",
      "Products removed from cart",
      "Products viewed",
      "Reached checkout rate",
      "Search added to cart rate",
      "Search click rate",
      "Search conversion rate",
      "Searches",
      "Searches submitted",
      "Search queries",
      "Search queries with clicks",
      "Search sessions that completed checkout",
      "Search sessions with cart additions",
      "Search sessions with clicks",
      "Sessions",
      "Sessions that completed checkout",
      "Sessions that reached and completed checkout",
      "Sessions that reached checkout",
      "Sessions with cart additions",
      "Sessions with product recommendations",
      "Sessions with searches",
      "Shop Mini opens",
      "Shop post-purchase offers",
      "Shop product impressions",
      "Shop review conversion rate",
      "Time to first add to cart",
      "Time to first checkout",
      "Time to first purchase",
      "TTFB distribution",
      "TTFB good view count",
      "TTFB okay view count",
      "TTFB P50",
      "TTFB P75",
      "TTFB P90",
      "TTFB P99",
      "TTFB poor view count",
    ],
  },
  {
    category: "Stores",
    labels: [
      "Avg. response time",
      "Conversation turns",
      "Negative feedback",
      "Positive feedback",
    ],
  },
  {
    category: "Time",
    labels: ["Evaluation window end", "Evaluation window start"],
  },
] as const;
