// Canonical stored option values remain unchanged when labels are translated.
export const settingsOptionKeys = {
  "Skip to content": "skipToContent",
  "Main navigation": "mainNavigation",
  "Treido home": "treidoHome",
  "Search settings": "searchSettings",
  "Shop settings menu": "shopSettingsMenu",
  "No matching settings": "noMatchingSettings",
  "Back to admin": "backToAdmin",
  "Settings menu": "settingsMenu",
  "Settings section": "settingsSection",
  "Mobile settings": "mobileSettings",
  "Check the store name, contact email and shipping amounts.":
    "checkTheStoreNameContactEmailAndShippingAmounts",
  "Settings saved in this frontend preview.":
    "settingsSavedInThisFrontendPreview",
  Save: "save",
  "Business details": "businessDetails",
  "Business information used for markets, apps and store operations":
    "businessInformationUsedForMarketsAppsAndStoreOperations",
  Bulgaria: "bulgaria",
  "— business": "business",
  "Edit business details": "editBusinessDetails",
  "Store contact details": "storeContactDetails",
  "Edit store contact details": "editStoreContactDetails",
  "Store address": "storeAddress",
  "Edit store address": "editStoreAddress",
  "Store defaults": "storeDefaults",
  "Currency display": "currencyDisplay",
  "Manage the currencies customers see in Markets.":
    "manageTheCurrenciesCustomersSeeInMarkets",
  "Manage currencies": "manageCurrencies",
  "Backup region": "backupRegion",
  Greece: "greece",
  Romania: "romania",
  Germany: "germany",
  "Unit system": "unitSystem",
  "Metric system": "metricSystem",
  "Imperial system": "imperialSystem",
  "Default weight unit": "defaultWeightUnit",
  "Kilogram (kg)": "kilogramKg",
  "Gram (g)": "gramG",
  "Time zone": "timeZone",
  "Sets the time for order and report display in this preview.":
    "setsTheTimeForOrderAndReportDisplayInThisPreview",
  "Order ID format": "orderIdFormat",
  Prefix: "prefix",
  Suffix: "suffix",
  "Your order IDs will appear as": "yourOrderIdsWillAppearAs",
  "Order processing": "orderProcessing",
  "Require a confirmation step": "requireAConfirmationStep",
  "After an order has been paid": "afterAnOrderHasBeenPaid",
  "Do not fulfill automatically": "doNotFulfillAutomatically",
  "Automatically fulfill items": "automaticallyFulfillItems",
  "Automatically archive completed orders":
    "automaticallyArchiveCompletedOrders",
  "Store assets": "storeAssets",
  Brand: "brand",
  "Manage brand": "manageBrand",
  "Custom content": "customContent",
  "Manage content": "manageContent",
  Done: "done",
  Address: "address",
  City: "city",
  "Postal code": "postalCode",
  Country: "country",
  "Store name": "storeName",
  "Contact email": "contactEmail",
  "Phone number": "phoneNumber",
  "Save General settings to keep these changes.":
    "saveGeneralSettingsToKeepTheseChanges",
  "Current plan": "currentPlan",
  "Preview selection": "previewSelection",
  "Review the plan choice. Prices and entitlements will be configured with the backend.":
    "reviewThePlanChoicePricesAndEntitlementsWillBeConfiguredWithTheBackend",
  "Billing profile": "billingProfile",
  "Business name": "businessName",
  "Billing email": "billingEmail",
  "Billing address": "billingAddress",
  "VAT number": "vatNumber",
  Invoices: "invoices",
  "No invoices exist in the frontend preview.":
    "noInvoicesExistInTheFrontendPreview",
  "Billing overview": "billingOverview",
  "Payment providers": "paymentProviders",
  "Not connected": "notConnected",
  "Select the payment flow to review in the frontend. No provider is activated.":
    "selectThePaymentFlowToReviewInTheFrontendNoProviderIsActivated",
  "Payment method": "paymentMethod",
  "Card payment (preview)": "cardPaymentPreview",
  "Manual payment": "manualPayment",
  "Cash on delivery": "cashOnDelivery",
  "Payment instructions": "paymentInstructions",
  "Payment capture": "paymentCapture",
  "Capture method": "captureMethod",
  "Automatically at checkout": "automaticallyAtCheckout",
  "Manually after review": "manuallyAfterReview",
  "The server and payment provider will enforce capture rules after integration.":
    "theServerAndPaymentProviderWillEnforceCaptureRulesAfterIntegration",
  "Customer contact method": "customerContactMethod",
  "Customers can check out using": "customersCanCheckOutUsing",
  Email: "email",
  "Phone number or email": "phoneNumberOrEmail",
  "Show a tracking link after purchase": "showATrackingLinkAfterPurchase",
  "Customer information": "customerInformation",
  "Full name": "fullName",
  "Require first and last name": "requireFirstAndLastName",
  "Last name only": "lastNameOnly",
  "Company name": "companyName",
  "Do not include": "doNotInclude",
  Optional: "optional",
  Required: "required",
  "Address line 2": "addressLine2",
  "Shipping phone number": "shippingPhoneNumber",
  "Display email marketing preference": "displayEmailMarketingPreference",
  "Order note label": "orderNoteLabel",
  "Customer accounts": "customerAccounts",
  "Account experience": "accountExperience",
  "Optional account": "optionalAccount",
  "Account required": "accountRequired",
  "Guest checkout": "guestCheckout",
  "Show account links": "showAccountLinks",
  "These are frontend choices. Customer authentication will be integrated later.":
    "theseAreFrontendChoicesCustomerAuthenticationWillBeIntegratedLater",
  "Account pages": "accountPages",
  "Review customer profiles": "reviewCustomerProfiles",
  "Customer privacy": "customerPrivacy",
  Shipping: "shipping",
  "General shipping profile": "generalShippingProfile",
  "Apply the default profile to your physical products.":
    "applyTheDefaultProfileToYourPhysicalProducts",
  "Delivery options": "deliveryOptions",
  "Shipping and local pickup": "shippingAndLocalPickup",
  "Shipping only": "shippingOnly",
  "Local pickup only": "localPickupOnly",
  "Shipping rate (EUR)": "shippingRateEur",
  "Free shipping above (EUR)": "freeShippingAboveEur",
  "Countries in this shipping zone": "countriesInThisShippingZone",
  "Dispatch time": "dispatchTime",
  "1–2 business days": "label12BusinessDays",
  "3–5 business days": "label35BusinessDays",
  "Custom arrangement": "customArrangement",
  "Local pickup": "localPickup",
  "Enable local pickup in the preview": "enableLocalPickupInThePreview",
  "Pickup city": "pickupCity",
  "Pickup instructions": "pickupInstructions",
  "Delivery notes": "deliveryNotes",
  "Customer delivery information": "customerDeliveryInformation",
  "Tax display": "taxDisplay",
  "Include tax in displayed prices": "includeTaxInDisplayedPrices",
  "Default display rate (%)": "defaultDisplayRate",
  "Preview display preferences only. Rates and collection require a verified tax adapter.":
    "previewDisplayPreferencesOnlyRatesAndCollectionRequireAVerifiedTaxAdapter",
  "Business registration": "businessRegistration",
  "Registered business name": "registeredBusinessName",
  "Review markets": "reviewMarkets",
  "Primary location": "primaryLocation",
  "Location name": "locationName",
  "Use this location for fulfillment": "useThisLocationForFulfillment",
  Inventory: "inventory",
  "Manage quantities": "manageQuantities",
  "Regional markets": "regionalMarkets",
  "Set up the regions where your store will operate.":
    "setUpTheRegionsWhereYourStoreWillOperate",
  Manage: "manage",
  "Create market": "createMarket",
  Integrations: "integrations",
  "Prepare integration preferences before connecting providers.":
    "prepareIntegrationPreferencesBeforeConnectingProviders",
  "Preferred shipping integration": "preferredShippingIntegration",
  "Not selected": "notSelected",
  "Carrier integration": "carrierIntegration",
  "Preferred payment integration": "preferredPaymentIntegration",
  "Card processor": "cardProcessor",
  "Include analytics integration in setup":
    "includeAnalyticsIntegrationInSetup",
  "Connection status": "connectionStatus",
  "Frontend preview": "frontendPreview",
  "No third-party accounts or services are connected through this screen.":
    "noThirdPartyAccountsOrServicesAreConnectedThroughThisScreen",
  "Store domain": "storeDomain",
  Preview: "preview",
  "Store handle": "storeHandle",
  "Custom domain": "customDomain",
  "Enter a domain to review the configuration flow.":
    "enterADomainToReviewTheConfigurationFlow",
  "Domain configuration": "domainConfiguration",
  "Redirect to primary domain": "redirectToPrimaryDomain",
  "DNS, certificates and domain verification will be connected later.":
    "dnsCertificatesAndDomainVerificationWillBeConnectedLater",
  "Customer events": "customerEvents",
  "Page view events": "pageViewEvents",
  "Product view events": "productViewEvents",
  "Checkout events": "checkoutEvents",
  "This records preferences only. No tracking scripts are installed.":
    "thisRecordsPreferencesOnlyNoTrackingScriptsAreInstalled",
  "Event privacy": "eventPrivacy",
  "Manage privacy preferences": "managePrivacyPreferences",
  "Customer notifications": "customerNotifications",
  "Order confirmation": "orderConfirmation",
  "Shipping updates": "shippingUpdates",
  "Marketing updates": "marketingUpdates",
  "Notification language": "notificationLanguage",
  English: "english",
  Bulgarian: "bulgarian",
  "Edit template": "editTemplate",
  "Staff notifications": "staffNotifications",
  "New customer messages": "newCustomerMessages",
  "Low stock alerts": "lowStockAlerts",
  "Notification recipient": "notificationRecipient",
  "Metafield definitions": "metafieldDefinitions",
  "Add structured fields for product and store content.":
    "addStructuredFieldsForProductAndStoreContent",
  "Add definition": "addDefinition",
  "Content definitions": "contentDefinitions",
  Edit: "edit",
  "Manage definitions": "manageDefinitions",
  "Store language": "storeLanguage",
  "Default language": "defaultLanguage",
  "Include Bulgarian storefront copy": "includeBulgarianStorefrontCopy",
  "Include English storefront copy": "includeEnglishStorefrontCopy",
  "Admin language": "adminLanguage",
  "Choose the preview language for menus and navigation.":
    "chooseThePreviewLanguageForMenusAndNavigation",
  "Display a cookie preference banner": "displayACookiePreferenceBanner",
  "Require analytics consent": "requireAnalyticsConsent",
  "Require marketing consent": "requireMarketingConsent",
  "Privacy contact email": "privacyContactEmail",
  "Privacy policy": "privacyPolicy",
  "Policy text": "policyText",
  "Written return and refund policy": "writtenReturnAndRefundPolicy",
  "Return window (days)": "returnWindowDays",
  "Return and refund policy": "returnAndRefundPolicy",
  "Privacy policy text": "privacyPolicyText",
  "Terms of service": "termsOfService",
  "Terms of service text": "termsOfServiceText",
  "Shipping policy": "shippingPolicy",
  "Shipping policy text": "shippingPolicyText",
  "Email body": "emailBody",
  "Save Notifications to keep this template. No email is sent.":
    "saveNotificationsToKeepThisTemplateNoEmailIsSent",
  "No phone number": "noPhoneNumber",
  "Euro (EUR €)": "euroEur",
  "Start with personal selling and a simple catalog.":
    "startWithPersonalSellingAndASimpleCatalog",
  "A workspace for a growing business catalog.":
    "aWorkspaceForAGrowingBusinessCatalog",
  "Team tools, reports and store management.":
    "teamToolsReportsAndStoreManagement",
  Selected: "selected",
  "Choose plan": "choosePlan",
  "Shipping update": "shippingUpdate",
  "Refund confirmation": "refundConfirmation",
} as const;
