export const studioStateKeys = {
  All: "all",
  Active: "active",
  Paid: "paid",
  Fulfilled: "fulfilled",
  Visible: "visible",
  Owner: "owner",
  Pending: "pending",
  Unfulfilled: "unfulfilled",
  Draft: "draft",
  Invited: "invited",
  Archived: "archived",
  Refunded: "refunded",
  Cancelled: "cancelled",
  Scheduled: "scheduled",
  Expired: "expired",
  Enabled: "enabled",
  Disabled: "disabled",
} as const;
