const en = {
  title: "Saved searches",
  save: "Save search",
  manage: "Manage saved searches",
  intro:
    "Keep reviewed criteria and choose whether Treido checks for in-app matches.",
  name: "Search name",
  frequency: "Matching frequency",
  updateFrequency: "Apply interval and keep matching enabled",
  hourly: "About once an hour",
  daily: "About once a day",
  enableConsent: "Enable optional in-app matching for these reviewed criteria",
  consentNote:
    "Saving without this choice keeps matching paused. Opening a link or signing in does not save or enable a search.",
  cadenceNote:
    "These are scheduling intervals. Execution may be delayed; there is no delivery or availability guarantee.",
  paused: "Paused",
  enabled: "Matching enabled",
  enable: "Enable matching",
  pause: "Pause matching",
  remove: "Remove subscription",
  removeNote:
    "Remove this saved search and its criteria, observations and in-app match history? Minimal command acknowledgments remain for retry safety.",
  cancel: "Cancel",
  confirm: "Confirm removal",
  rename: "Save name",
  edit: "Review changed criteria",
  saveCriteria: "Save reviewed criteria",
  reopen: "Open current results",
  criteria: "Retained criteria",
  previousCriteria: "This update belongs to an earlier criteria version.",
  needsReview:
    "These criteria need review against the current category registry. Matching cannot run until valid criteria are saved.",
  empty: "No saved searches yet",
  emptyNote: "Review Find or Deal Finder criteria, then choose Save search.",
  find: "Find for me",
  deal: "Deal Finder",
  notifications: "Open notifications",
  updates: "Saved-search updates",
  updatesEmpty: "No observed matches or changes in this view yet.",
  updatesNote:
    "Only eligible catalogue facts actually observed by bounded work appear here. This is not a complete scan or an email/push delivery.",
  new_publication: "Newly observed matching publication",
  price_changed: "Observed item price changed",
  stock_changed: "Observed stock state changed",
  unavailable: "This result is no longer available under the saved criteria",
  unavailableItem: "Current item details unavailable",
  observed: "Observed facts",
  current: "Current item price",
  priorPrice: "Previously observed item price",
  observedPrice: "Item price at observation",
  variantNote:
    "Prices use the representative available variant. A different variant is not a comparable-item discount.",
  currentNote:
    "Open or review the current item before contacting the seller or adding to cart. Observed facts are not a quote or stock guarantee.",
  openProduct: "Open current product",
  actions: "Review current contact/cart actions",
  markRead: "Mark this update as read",
  unread: "Unread",
  read: "Read",
  older: "Older search updates",
  latest: "Latest search updates",
  allUpdates: "All search updates",
  unreadUpdates: "Unread search updates",
  priorStock: "Previously observed stock",
  observedStock: "Observed stock",
  stock_unknown: "Unknown",
  stock_available: "Available when checked",
  stock_reserved: "Reserved when checked",
  stock_out_of_stock: "Out of stock when checked",
  checking: "Checking current account and storage…",
  guest: "Sign in to save or manage searches",
  noAutomatic: "Signing in does not execute a saved-search command.",
  retry: "Reload current state",
  retryOriginal: "Retry original request",
  pending:
    "No confirmed outcome yet. The exact original request is retained; retry it before making another change.",
  saving: "Saving…",
  saved: "Command acknowledged",
  replayed: "Original command acknowledgment recovered",
  revision: "Accepted revision",
  currentRevision: "Current workspace revision",
  conflict:
    "The state changed. Reload and review the current version before sending a new command.",
  quota: "This account reached the saved-search or command limit.",
  denied:
    "Current account access is unavailable. The original request is retained.",
  storageUnavailable:
    "Saved-search storage is unavailable. No subscription or matching success is claimed.",
  invalid:
    "Review the criteria and input. Unsupported filters are not relaxed.",
  notFound:
    "This saved search or update is no longer available to the current account.",
  recoveryStorage:
    "The original request could not be stored safely for recovery. New commands are blocked; keep this tab open.",
  recoveryInvalid:
    "Recovery data cannot be read safely. No replacement command has been sent.",
  check: "Request a bounded check / retry stalled work",
  running: "Matching work is queued or continuing",
  bounded: "This check reached its catalogue budget",
  finished: "This bounded check finished",
  cancelled: "This matching run was cancelled",
  failed:
    "Matching work stalled after its retry budget; request a new bounded check",
  scopeNote:
    "At most 200 publications and 200 retained observations per search are considered per check. Not every matching listing is guaranteed to be observed.",
  checked: "Candidate checks",
  retained: "New observations retained",
  consentAt: "Explicit matching consent recorded",
  lastCheck: "Latest bounded check",
  noCheck: "No completed check is recorded yet.",
  version: "Criteria version",
  reviewReady:
    "Changed criteria are ready below. Saving versions them and cancels old matching work.",
  seller: "Seller scope",
  all: "All sellers",
  personal: "Personal sellers",
  business: "Businesses",
  condition: "Condition",
  location: "Locality",
  budget: "Item-price budget",
  category: "Category",
  handover: "Handover",
  any: "Any / unspecified",
  pickup: "Pickup",
  shipping: "Shipping",
  availability: "Stock criterion",
  known: "Known available stock",
  query: "Keywords",
  attribute: "Category filter",
  unknown: "Not specified",
  clearEdit: "Cancel criteria edit",
} as const;
const bg: Record<keyof typeof en, string> = {
  title: "Запазени търсения",
  save: "Запази търсенето",
  manage: "Управлявай запазените търсения",
  intro:
    "Запази прегледаните критерии и избери дали Treido да проверява за съвпадения в приложението.",
  name: "Име на търсенето",
  frequency: "Честота на проверките",
  updateFrequency: "Приложи интервала и продължи проверките",
  hourly: "Приблизително веднъж на час",
  daily: "Приблизително веднъж на ден",
  enableConsent:
    "Включи незадължителни известия в приложението по тези прегледани критерии",
  consentNote:
    "Без този избор проверките остават спрени. Отварянето на връзка или входът не запазват и не включват търсене.",
  cadenceNote:
    "Това са интервали за планиране. Изпълнението може да се забави; няма гаранция за доставка на известие или наличност.",
  paused: "Спряно",
  enabled: "Проверките са включени",
  enable: "Включи проверките",
  pause: "Спри проверките",
  remove: "Премахни абонамента",
  removeNote:
    "Да премахнем ли това търсене, критериите, наблюденията и историята на съвпаденията? Остават минимални потвърждения за безопасно повторение на заявките.",
  cancel: "Откажи",
  confirm: "Потвърди премахването",
  rename: "Запази името",
  edit: "Прегледай нови критерии",
  saveCriteria: "Запази прегледаните критерии",
  reopen: "Отвори текущите резултати",
  criteria: "Запазени критерии",
  previousCriteria: "Тази промяна е по предишна версия на критериите.",
  needsReview:
    "Критериите изискват преглед според текущите категории. Проверки няма да се изпълняват, докато не запазиш валидни критерии.",
  empty: "Още няма запазени търсения",
  emptyNote:
    "Прегледай критериите в „Намери за мен“ или „Търсач на оферти“, после избери „Запази търсенето“.",
  find: "Намери за мен",
  deal: "Търсач на оферти",
  notifications: "Отвори известията",
  updates: "Промени по запазени търсения",
  updatesEmpty: "Още няма наблюдавани съвпадения или промени в този изглед.",
  updatesNote:
    "Тук се показват само допустими факти от каталога, наблюдавани при ограничени проверки. Това не е пълно обхождане или доставка по имейл/push.",
  new_publication: "Ново наблюдавано съвпадение",
  price_changed: "Наблюдаваната цена се е променила",
  stock_changed: "Наблюдаваната наличност се е променила",
  unavailable: "Резултатът вече не е наличен по запазените критерии",
  unavailableItem: "Текущите данни за артикула са недостъпни",
  observed: "Наблюдавани факти",
  current: "Текуща цена на артикула",
  priorPrice: "Предишна наблюдавана цена",
  observedPrice: "Цена при наблюдението",
  variantNote:
    "Цените са за представителния наличен вариант. Друг вариант не е намаление на същия артикул.",
  currentNote:
    "Прегледай текущия артикул преди контакт с продавача или добавяне в количката. Наблюденията не са оферта или гаранция за наличност.",
  openProduct: "Отвори текущия артикул",
  actions: "Прегледай текущите действия за контакт/количка",
  markRead: "Отбележи тази промяна като прочетена",
  unread: "Непрочетено",
  read: "Прочетено",
  older: "По-стари промени",
  latest: "Последни промени",
  allUpdates: "Всички промени по търсения",
  unreadUpdates: "Непрочетени промени по търсения",
  priorStock: "Предишна наблюдавана наличност",
  observedStock: "Наличност при наблюдението",
  stock_unknown: "Неизвестна",
  stock_available: "Наличен при проверката",
  stock_reserved: "Резервиран при проверката",
  stock_out_of_stock: "Изчерпан при проверката",
  checking: "Проверяваме текущия акаунт и съхранението…",
  guest: "Влез, за да запазваш и управляваш търсения",
  noAutomatic: "Входът не изпълнява команда за запазено търсене.",
  retry: "Зареди текущото състояние",
  retryOriginal: "Повтори първоначалната заявка",
  pending:
    "Още няма потвърден резултат. Точната първоначална заявка е запазена; повтори я преди друга промяна.",
  saving: "Запазваме…",
  saved: "Командата е потвърдена",
  replayed: "Възстановено е първоначалното потвърждение",
  revision: "Приета ревизия",
  currentRevision: "Текуща ревизия",
  conflict:
    "Състоянието се е променило. Зареди и прегледай текущата версия преди нова команда.",
  quota: "Достигнат е лимитът за запазени търсения или команди.",
  denied: "Текущият акаунт няма достъп. Първоначалната заявка е запазена.",
  storageUnavailable:
    "Съхранението на търсения е недостъпно. Не твърдим успешно запазване или проверка.",
  invalid:
    "Прегледай критериите и въведените данни. Неподдържаните филтри не се премахват.",
  notFound: "Това търсене или известие вече не е достъпно за текущия акаунт.",
  recoveryStorage:
    "Първоначалната заявка не може да се съхрани безопасно. Нови команди са блокирани; запази раздела отворен.",
  recoveryInvalid:
    "Данните за възстановяване не могат да се прочетат безопасно. Няма изпратена заместваща команда.",
  check: "Заяви ограничена проверка / повтори спряла работа",
  running: "Проверката е чакаща или продължава",
  bounded: "Проверката достигна лимита за каталога",
  finished: "Ограничената проверка завърши",
  cancelled: "Проверката е отменена",
  failed:
    "Работата е спряла след лимита за повторения; заяви нова ограничена проверка",
  scopeNote:
    "Една проверка разглежда най-много 200 публикации и 200 запазени наблюдения. Няма гаранция, че всеки съвпадащ артикул ще бъде наблюдаван.",
  checked: "Проверки на кандидати",
  retained: "Нови запазени наблюдения",
  consentAt: "Записано изрично съгласие за проверки",
  lastCheck: "Последна ограничена проверка",
  noCheck: "Още няма записана завършила проверка.",
  version: "Версия на критериите",
  reviewReady:
    "Новите критерии са готови за преглед по-долу. Запазването създава версия и отменя старата работа.",
  seller: "Обхват на продавачите",
  all: "Всички продавачи",
  personal: "Лични продавачи",
  business: "Бизнеси",
  condition: "Състояние",
  location: "Населено място",
  budget: "Бюджет за артикула",
  category: "Категория",
  handover: "Предаване",
  any: "Всичко / неуточнено",
  pickup: "Лично предаване",
  shipping: "Изпращане",
  availability: "Критерий за наличност",
  known: "Известна наличност",
  query: "Ключови думи",
  attribute: "Филтър по категория",
  unknown: "Не е уточнено",
  clearEdit: "Откажи промяната на критерии",
};
export const searchCopy = { en, bg };
export type SearchCopyKey = keyof typeof en;
