export const declarationMessages = {
  en: {
    title: "Trader declarations",
    detail: "Review trader declaration",
    reports: "Reports",
    back: "Back to declarations",
    note: "Review the submitted trader details and record the reason for accepting them or requesting correction. Verification claims, commercial warranties and payment readiness are assessed separately.",
    search: "Business name",
    state: "State",
    filter: "Apply",
    all: "All states",
    review_required: "Review requested",
    accepted: "Accepted",
    rejected: "Needs correction",
    draft: "Draft",
    empty: "No declarations match these criteria.",
    next: "Older declarations",
    first: "Newest declarations",
    open: "Open declaration",
    legalName: "Legal name",
    registrationNumber: "Registration number",
    contactEmail: "Private contact email",
    contactAddress: "Private contact address",
    country: "Country",
    accurate: "Seller confirmed accuracy",
    yes: "Yes",
    no: "No",
    revision: "Declaration revision",
    setupRevision: "Setup revision",
    requirement: "Requirement version",
    submitted: "Submitted",
    unknown: "Not submitted",
    current: "Current declaration",
    older:
      "This declaration has been superseded. Open the current declaration before recording another decision.",
    openCurrent: "Open current declaration",
    readOnly:
      "This declaration cannot be reviewed with your current permissions, its state or its current requirements. The submitted facts remain unchanged.",
    decision: "Decision",
    reason: "Reason for the seller",
    reasonNote:
      "Describe the reviewed facts or the correction needed. Keep unrelated private information out of the reason.",
    prepare: "Review decision",
    confirm: "Confirm decision",
    cancel: "Back to editing",
    confirmation: "Confirm declaration review",
    confirmNote:
      "This records your decision for the exact declaration and setup revisions shown. Submitted facts are retained in the history.",
    saved: "Declaration decision recorded.",
    conflict:
      "The declaration or setup has changed. Read the current state before preparing a new decision.",
    pending:
      "This decision has an unconfirmed outcome. Retry the same request to recover its receipt.",
    retry: "Retry this decision",
    reload: "Reload current state",
    resume: "Keep reason and review current state",
    denied: "Current operator access is required.",
    checking: "Checking current access…",
    failed:
      "Declaration review is temporarily unavailable. Your input is retained.",
    saving: "Recording decision…",
    invalidRecovery:
      "The saved review input is invalid. Discard it before preparing another decision.",
    discard: "Discard invalid input",
    storageFailed:
      "Review recovery could not be saved in this browser. Retry before confirming a decision.",
    history: "Declaration review history",
    reasonHistory: "Recorded reason",
    privateNote: "Trader contact details stay private in this review.",
  },
  bg: {
    title: "Декларации на търговци",
    detail: "Преглед на декларация",
    reports: "Сигнали",
    back: "Назад към декларациите",
    note: "Прегледайте подадените данни за търговеца и запишете основанието за приемане или за нужната корекция. Верификацията, търговските гаранции и готовността за плащания се оценяват отделно.",
    search: "Име на бизнеса",
    state: "Състояние",
    filter: "Приложи",
    all: "Всички състояния",
    review_required: "Заявена проверка",
    accepted: "Приета",
    rejected: "Нужна корекция",
    draft: "Чернова",
    empty: "Няма декларации по тези критерии.",
    next: "По-стари декларации",
    first: "Най-нови декларации",
    open: "Отвори декларацията",
    legalName: "Юридическо наименование",
    registrationNumber: "Регистрационен номер",
    contactEmail: "Личен имейл за контакт",
    contactAddress: "Личен адрес за контакт",
    country: "Държава",
    accurate: "Търговецът потвърди точността",
    yes: "Да",
    no: "Не",
    revision: "Версия на декларацията",
    setupRevision: "Версия на настройките",
    requirement: "Версия на изискванията",
    submitted: "Подадена",
    unknown: "Не е подадена",
    current: "Текуща декларация",
    older:
      "Има по-нова декларация. Отворете я преди да запишете друго решение.",
    openCurrent: "Отвори текущата декларация",
    readOnly:
      "Тази декларация не може да бъде прегледана с текущите ви разрешения, състоянието ѝ или настоящите изисквания. Подадените данни остават непроменени.",
    decision: "Решение",
    reason: "Основание за търговеца",
    reasonNote:
      "Опишете прегледаните факти или нужната корекция. Не включвайте чужда лична информация.",
    prepare: "Прегледай решението",
    confirm: "Потвърди решението",
    cancel: "Към редактиране",
    confirmation: "Потвърди прегледа",
    confirmNote:
      "Решението се записва за показаните версии на декларацията и настройките. Подадените данни се запазват в историята.",
    saved: "Решението за декларацията е записано.",
    conflict:
      "Декларацията или настройките са променени. Прочетете текущото състояние преди ново решение.",
    pending:
      "Резултатът от това решение не е потвърден. Повторете същата заявка, за да получите потвърждението.",
    retry: "Повтори това решение",
    reload: "Зареди текущото състояние",
    resume: "Запази основанието и прегледай текущото състояние",
    denied: "Нужен е текущ достъп за оператор.",
    checking: "Проверка на текущия достъп…",
    failed: "Прегледът временно не е достъпен. Въведеното е запазено.",
    saving: "Записване на решението…",
    invalidRecovery:
      "Запазеното решение е невалидно. Изтрийте го преди да подготвите друго.",
    discard: "Изтрий невалидното въведено",
    storageFailed:
      "Данните за възстановяване не можаха да се запазят в този браузър. Опитайте отново преди потвърждение.",
    history: "История на прегледите",
    reasonHistory: "Записано основание",
    privateNote:
      "Данните за контакт на търговеца остават лични в този преглед.",
  },
} as const;
