export const copy = {
  en: {
    closure: "Close your account",
    preferences: "Account preferences",
    security: "Account security",
    intro:
      "Review the approved handling of your data and any open obligations before confirming account closure.",
    unavailable: "This account service is currently unavailable.",
    policyMissing:
      "A reviewed retention policy and verified account configuration are required before closure can start.",
    request: "First create a closure request in Personal data.",
    data: "Personal data",
    refresh: "Check current account",
    checking: "Checking your account…",
    recent: "Verify your identity to continue",
    review: "Prepare closure review",
    confirm: "Confirm account closure",
    ack: "I have read the handling of retained and removed data. I understand that access will stop and cancellation is unavailable once effects begin.",
    cancel: "Cancel before effects begin",
    recheck: "Check progress",
    retained: "Retained",
    removed: "Removed",
    purpose: "Purpose",
    deadline: "Handling",
    holds: "Open obligations",
    state: "Status",
    saved: "Saved preferences",
    language: "Language",
    scope: "Default seller scope",
    all: "All sellers",
    personal: "Personal sellers",
    business: "Business sellers",
    save: "Save preferences",
    search: "Open Search with my saved preferences",
    preferenceNotice:
      "These defaults do not change existing search links, seller account permissions, subscription or notification consent.",
    sessionNotice:
      "Only your own active sessions are shown. Revocation requires recent authentication. Ending this session signs you out; an uncertain result remains pending until checked.",
    end: "End this session",
    current: "Current session",
    limited:
      "This list is limited. Closure review requires a complete bounded session inventory.",
    recover: "Recover original request",
    retry: "Retry original request",
    pending:
      "An earlier request has an unresolved acknowledgment. Recover it before starting another.",
    conflict:
      "Your account changed. Check current state before making a new choice.",
    forbidden: "Sign in with the current account to continue.",
    held: "Open obligations or business ownership prevent closure. Resolve them through the appropriate account workflow.",
    irreversible: "Effects have begun. Cancellation is unavailable.",
    unknown:
      "The outcome is still uncertain. Check the original request; no new provider mutation is sent automatically.",
    storage:
      "Browser recovery storage is unavailable. New actions are paused; check current account state.",
    expired: "This review expired. Prepare a fresh review.",
    history: "Only the latest account records are shown.",
    active: "Active",
    restricted: "Closing / access restricted",
    closed: "Closed",
    signIn: "Sign in",
    bg: "Bulgarian",
    en: "English",
  },
  bg: {
    closure: "Закриване на профила",
    preferences: "Предпочитания на профила",
    security: "Сигурност на профила",
    intro:
      "Прегледайте одобрените правила за данните и текущите задължения, преди да потвърдите закриването.",
    unavailable: "Услугата за профила временно не е достъпна.",
    policyMissing:
      "Необходими са прегледани правила за съхранение и потвърдена конфигурация, преди закриването да започне.",
    request: "Първо създайте заявка за закриване в Лични данни.",
    data: "Лични данни",
    refresh: "Проверка на профила",
    checking: "Проверка на профила…",
    recent: "Потвърдете самоличността си",
    review: "Подготовка на преглед",
    confirm: "Потвърждавам закриването",
    ack: "Прочетох как се запазват и премахват данните. Разбирам, че достъпът ще бъде спрян и отказът е недостъпен след започване на действията.",
    cancel: "Отказ преди започване на действията",
    recheck: "Проверка на напредъка",
    retained: "Запазват се",
    removed: "Премахват се",
    purpose: "Цел",
    deadline: "Обработка",
    holds: "Текущи задължения",
    state: "Състояние",
    saved: "Запазени предпочитания",
    language: "Език",
    scope: "Продавачи по подразбиране",
    all: "Всички продавачи",
    personal: "Лични продавачи",
    business: "Бизнес продавачи",
    save: "Запазване",
    search: "Търсене със запазените предпочитания",
    preferenceNotice:
      "Тези настройки не променят съществуващи връзки за търсене, права за продавач, абонамент или съгласие за известия.",
    sessionNotice:
      "Показват се само Вашите активни сесии. Прекратяването изисква скорошно потвърждение на самоличността. Прекратяването на тази сесия Ви отписва; неизвестният резултат остава чакащ до проверка.",
    end: "Прекратяване на сесията",
    current: "Текуща сесия",
    limited:
      "Списъкът е ограничен. За закриване е необходим пълен списък в допустимия размер.",
    recover: "Възстановяване на първоначалната заявка",
    retry: "Повторение на първоначалната заявка",
    pending:
      "Резултатът от предишна заявка е неизвестен. Възстановете я, преди да започнете друга.",
    conflict:
      "Профилът е променен. Проверете текущото състояние преди нов избор.",
    forbidden: "Влезте с текущия профил, за да продължите.",
    held: "Текущи задължения или собственост върху бизнес възпрепятстват закриването. Разрешете ги чрез съответните действия за профила.",
    irreversible: "Действията са започнали. Отказът вече е недостъпен.",
    unknown:
      "Резултатът остава неизвестен. Проверете първоначалната заявка; ново действие при доставчик не се изпраща автоматично.",
    storage:
      "Паметта за възстановяване в браузъра е недостъпна. Новите действия са спрени; проверете текущото състояние на профила.",
    expired: "Прегледът е изтекъл. Подгответе нов преглед.",
    history: "Показват се само последните записи за профила.",
    active: "Активен",
    restricted: "Закриване / ограничен достъп",
    closed: "Закрит",
    signIn: "Вход",
    bg: "Български",
    en: "Английски",
  },
} as const;
export const obligationLabels = {
  en: {
    soleBusinessOwners: "Sole business ownership",
    allocations: "Stock allocations",
    offers: "Open offers",
    payments: "Unresolved payments",
    orders: "Open orders",
    refunds: "Unresolved refunds",
    cases: "Open cases",
    billingIntents: "Billing operations",
    billingInvoices: "Unresolved invoices",
    promotionAttempts: "Promotion payments",
    promotionReservations: "Promotion capacity",
    promotionRemedies: "Promotion remedies",
    mediaWriters: "Active media writers",
    assistantRuns: "Unresolved assistant runs",
    sessionEffects: "Unresolved session revocations",
    legalHolds: "Reviewed legal holds",
  },
  bg: {
    soleBusinessOwners: "Единствен собственик на бизнес",
    allocations: "Резервирана наличност",
    offers: "Текущи оферти",
    payments: "Неуредени плащания",
    orders: "Текущи поръчки",
    refunds: "Неуредени възстановявания",
    cases: "Текущи случаи",
    billingIntents: "Абонаментни операции",
    billingInvoices: "Неуредени фактури",
    promotionAttempts: "Плащания за промотиране",
    promotionReservations: "Капацитет за промотиране",
    promotionRemedies: "Компенсации за промотиране",
    mediaWriters: "Активна обработка на медия",
    assistantRuns: "Неуредени действия на асистент",
    sessionEffects: "Неуредени прекратявания на сесии",
    legalHolds: "Прегледани законови ограничения",
  },
} as const;
