export const accountMessageKeys = {
  "Sign in or create an account": "signInOrCreateAnAccount",
  "Buy whatever you want. Track every order. Catch every deal and restock.":
    "profileIntro",
  "Sign in": "signIn",
  Saved: "saved",
  Following: "following",
  "Order history": "orderHistory",
  "No orders yet": "noOrdersYet",
  "Orders you place in Shop or sync from your emails will show up here":
    "orderHistoryNote",
  "Sell an item": "sellAnItem",
  Notifications: "notifications",
  "Data & privacy": "dataPrivacy",
  "Development mode": "developmentMode",
  Support: "support",
  "Terms and conditions": "terms",
  Licenses: "licenses",
  "Powered by": "poweredBy",
  "Start selling for free": "startSelling",
  "Recently viewed": "recentlyViewed",
  Addresses: "addresses",
  "Sign in & security": "signInSecurity",
  Connections: "connections",
  "Payment methods": "paymentMethods",
  "Add card": "addCard",
  Cancel: "cancel",
  Save: "save",
} as const;
