import type { MerchantReviewMediaItem } from "./live-merchant-fixtures";
// First sixteen source photos. Native pagination continued beyond this prefix.
export const ourPlaceReviewMedia: readonly MerchantReviewMediaItem[] = [
  {
    id: "ourplace-gallery-01",
    image: "/api/reference-media/merchant-ourplace-gallery-01",
    thumbnail: "/api/reference-media/merchant-ourplace-gallery-01-thumb",
    productImage: "/api/reference-media/merchant-ourplace-gallery-01-product",
    productTitle: "Wonder Oven",
    title: "",
    body: "I love my little air fryer it came a little bent on the side but it works great i recommend",
    author: "Stefanny",
    date: "29 days ago",
    stars: 4,
  },
  {
    id: "ourplace-gallery-02",
    image: "/api/reference-media/merchant-ourplace-gallery-02",
    thumbnail: "/api/reference-media/merchant-ourplace-gallery-02-thumb",
    productImage: "/api/reference-media/merchant-ourplace-gallery-02-product",
    productTitle: "Ceramic Nonstick Always Pan 8.5”",
    title: "",
    body: "Not a nostick pan! Less than two months of use . Really disappointing!",
    author: "Sadia",
    date: "Aug 27, 2026",
    stars: 1,
  },
  {
    id: "ourplace-gallery-03",
    image: "/api/reference-media/merchant-ourplace-gallery-03",
    thumbnail: "/api/reference-media/merchant-ourplace-gallery-03-thumb",
    productTitle: "Wonder Oven",
    title: "",
    body: "I was so looking forward to receiving the wonder oven. Alas. , it came in damaged and since this is the second one, I decided this time to go for a refund.",
    author: "Vickie",
    date: "Feb 27, 2026",
    stars: 1,
  },
  {
    id: "ourplace-gallery-04",
    image: "/api/reference-media/merchant-ourplace-gallery-04",
    thumbnail: "/api/reference-media/merchant-ourplace-gallery-04-thumb",
    productTitle: "Wonder Oven",
    title: "",
    body: "I was so looking forward to receiving the wonder oven. Alas. , it came in damaged and since this is the second one, I decided this time to go for a refund.",
    author: "Vickie",
    date: "Feb 27, 2026",
    stars: 1,
  },
  {
    id: "ourplace-gallery-05",
    image: "/api/reference-media/merchant-ourplace-gallery-05",
    thumbnail: "/api/reference-media/merchant-ourplace-gallery-05-thumb",
    productTitle: "Wonder Oven",
    title: "",
    body: "I was so looking forward to receiving the wonder oven. Alas. , it came in damaged and since this is the second one, I decided this time to go for a refund.",
    author: "Vickie",
    date: "Feb 27, 2026",
    stars: 1,
  },
  {
    id: "ourplace-gallery-06",
    image: "/api/reference-media/merchant-ourplace-gallery-06",
    thumbnail: "/api/reference-media/merchant-ourplace-gallery-06-thumb",
    productImage: "/api/reference-media/merchant-ourplace-gallery-06-product",
    productTitle: "Ceramic Nonstick Always Pan 8.5”",
    title: "Came damged",
    body: "After doing a color exchange and then my color being sold out once return was received, I ordered my pieces in cream individually. Well after the excitement and wait they all came damaged and or bad quality. I had to send them all back. I was bummed. Never had this happen with all my past purchases not sure what happened to the quality control.",
    author: "",
    date: "",
    stars: 2,
  },
  {
    id: "ourplace-gallery-07",
    image: "/api/reference-media/merchant-ourplace-gallery-07",
    thumbnail: "/api/reference-media/merchant-ourplace-gallery-07-thumb",
    productImage: "/api/reference-media/merchant-ourplace-gallery-07-product",
    productTitle: "Ceramic Nonstick Always Pan 8.5”",
    title: "Came damged",
    body: "After doing a color exchange and then my color being sold out once return was received, I ordered my pieces in cream individually. Well after the excitement and wait they all came damaged and or bad quality. I had to send them all back. I was bummed. Never had this happen with all my past purchases not sure what happened to the quality control.",
    author: "",
    date: "",
    stars: 2,
  },
  {
    id: "ourplace-gallery-08",
    image: "/api/reference-media/merchant-ourplace-gallery-08",
    thumbnail: "/api/reference-media/merchant-ourplace-gallery-08-thumb",
    productImage: "/api/reference-media/merchant-ourplace-gallery-08-product",
    productTitle: "Ceramic Nonstick Always Pan 8.5”",
    title: "Came damged",
    body: "After doing a color exchange and then my color being sold out once return was received, I ordered my pieces in cream individually. Well after the excitement and wait they all came damaged and or bad quality. I had to send them all back. I was bummed. Never had this happen with all my past purchases not sure what happened to the quality control.",
    author: "",
    date: "",
    stars: 2,
  },
  {
    id: "ourplace-gallery-09",
    image: "/api/reference-media/merchant-ourplace-gallery-09",
    thumbnail: "/api/reference-media/merchant-ourplace-gallery-09-thumb",
    productImage: "/api/reference-media/merchant-ourplace-gallery-09-product",
    productTitle: "Ceramic Nonstick Always Pan 8.5”",
    title: "Came damged",
    body: "After doing a color exchange and then my color being sold out once return was received, I ordered my pieces in cream individually. Well after the excitement and wait they all came damaged and or bad quality. I had to send them all back. I was bummed. Never had this happen with all my past purchases not sure what happened to the quality control.",
    author: "",
    date: "",
    stars: 2,
  },
  {
    id: "ourplace-gallery-10",
    image: "/api/reference-media/merchant-ourplace-gallery-10",
    thumbnail: "/api/reference-media/merchant-ourplace-gallery-10-thumb",
    productImage: "/api/reference-media/merchant-ourplace-gallery-10-product",
    productTitle: "Ceramic Nonstick Always Pan 8.5”",
    title: "Came damged",
    body: "After doing a color exchange and then my color being sold out once return was received, I ordered my pieces in cream individually. Well after the excitement and wait they all came damaged and or bad quality. I had to send them all back. I was bummed. Never had this happen with all my past purchases not sure what happened to the quality control.",
    author: "",
    date: "",
    stars: 2,
  },
  {
    id: "ourplace-gallery-11",
    image: "/api/reference-media/merchant-ourplace-gallery-11",
    thumbnail: "/api/reference-media/merchant-ourplace-gallery-11-thumb",
    productImage: "/api/reference-media/merchant-ourplace-gallery-11-product",
    productTitle: "Wonder Oven Essentials Kit",
    title: "Disappointed",
    body: "I think Our Place is great overall. I love my air fryer, my titanium pots and pans, and the utensils I have but these ceramic coated air fryer pans are not coated well enough and I'm very disappointed. They are only actually nonstick for about 2 weeks and then grease just starts getting coated to the pans and won't come off. I've never put them in the dishwasher, I've followed all of the care instructions, and still the grease buildup persists. I'm going to look elsewhere for air fryer pans from now on until Our Place comes out with something better.",
    author: "",
    date: "",
    stars: 1,
  },
  {
    id: "ourplace-gallery-12",
    image: "/api/reference-media/merchant-ourplace-gallery-12",
    thumbnail: "/api/reference-media/merchant-ourplace-gallery-12-thumb",
    productImage: "/api/reference-media/merchant-ourplace-gallery-12-product",
    productTitle: "Titanium Always Pan Pro 10.5”",
    title: "",
    body: "I followed all the instructions. The omelet sticks to the pan and doesn't wash off completely. The lid handle gets hot during use, so you can burn yourself. The advertising and pictures are beautiful, though.",
    author: "Sergey",
    date: "Dec 19, 2025",
    stars: 1,
  },
  {
    id: "ourplace-gallery-13",
    image: "/api/reference-media/merchant-ourplace-gallery-13",
    thumbnail: "/api/reference-media/merchant-ourplace-gallery-13-thumb",
    productImage: "/api/reference-media/merchant-ourplace-gallery-13-product",
    productTitle: "Titanium Always Pan Pro 10.5”",
    title: "",
    body: "I followed all the instructions. The omelet sticks to the pan and doesn't wash off completely. The lid handle gets hot during use, so you can burn yourself. The advertising and pictures are beautiful, though.",
    author: "Sergey",
    date: "Dec 19, 2025",
    stars: 1,
  },
  {
    id: "ourplace-gallery-14",
    image: "/api/reference-media/merchant-ourplace-gallery-14",
    thumbnail: "/api/reference-media/merchant-ourplace-gallery-14-thumb",
    productTitle: "",
    title: "Underwhelmed and feelings of being scammed",
    body: "This pan was advertised to be a professional level pan that's cleans easily and is better than the hexclad however after 2 weeks the carbon buildup in the pores are getting worst and stains are appearing all over.",
    author: "Anthony",
    date: "Dec 19, 2025",
    stars: 1,
  },
  {
    id: "ourplace-gallery-15",
    image: "/api/reference-media/merchant-ourplace-gallery-15",
    thumbnail: "/api/reference-media/merchant-ourplace-gallery-15-thumb",
    productTitle: "",
    title: "Underwhelmed and feelings of being scammed",
    body: "This pan was advertised to be a professional level pan that's cleans easily and is better than the hexclad however after 2 weeks the carbon buildup in the pores are getting worst and stains are appearing all over.",
    author: "Anthony",
    date: "Dec 19, 2025",
    stars: 1,
  },
  {
    id: "ourplace-gallery-16",
    image: "/api/reference-media/merchant-ourplace-gallery-16",
    thumbnail: "/api/reference-media/merchant-ourplace-gallery-16-thumb",
    productImage: "/api/reference-media/merchant-ourplace-gallery-16-product",
    productTitle: "Titanium Pro Cookware Set",
    title:
      "Not as good as it should be for the cost. Disappointed with the quality and effectiveness.",
    body: "Product looks great but works poorly. Non stick doesn’t work well. Everything sticks even when I follow all instructions provided and spoke with support. Even harder to clean, pan stains easily and will not go away. I’ve used all instructions provided provided. Eggs are so hard to cook with these pans and sticks terribly. For the cost the pan should clean better. I understand there is a little learning curve with these pans but I’m use to cooking on stainless which has been easier to clean. Also the weight of these pans is crazy. But they look good for. The outside. Very disappointed. I Can not recommend. I will be returning. Customer service was difficult but after some tussle I was able to get the help I needed for a return. Too much drama….",
    author: "",
    date: "",
    stars: 2,
  },
];
