import type { Product, Store } from "../types";
// Native EUR prices and collection order, emulator-5560, 2026-09-27.
// Original merchant photography/descriptions; nullable stock is not inventory authority.
export const staudStore: Store = {
  id: "live-staud",
  name: "STAUD",
  logo: "/api/reference-media/live-explore-staud-logo",
  rating: 4.8,
  ratingCount: "5.7K",
  description: "",
  categories: ["Womenswear"],
  referenceStyle: "android",
  referenceWebsite: "https://staud.clothing",
};
export const staudProducts: readonly Product[] = [
  {
    id: "live-staud-davina-silk-top-pear",
    title: "DAVINA SILK TOP | PEAR",
    storeId: "live-staud",
    category: "Womenswear",
    color: "PEAR",
    images: [
      "/api/reference-media/live-staud-davina-silk-top-pear-1",
      "/api/reference-media/live-staud-davina-silk-top-pear-2",
      "/api/reference-media/live-staud-davina-silk-top-pear-3",
      "/api/reference-media/live-staud-davina-silk-top-pear-4",
      "/api/reference-media/live-staud-davina-silk-top-pear-5",
    ],
    price: {
      amount: 45500,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "Returning in a silk update for the season, the Davina Top is a draped top with asymmetrical sleeves. This style offers gentle draping throughout the body and offers a roomy fit through the waist.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf: "/api/reference-media/live-staud-davina-silk-top-pear-1",
      grid: "/api/reference-media/live-staud-davina-silk-top-pear-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch: "/api/reference-media/live-staud-davina-silk-top-pear-1",
      specifications: [
        {
          label: "Material",
          value: "70% acetate, 30% polyester (select variants: silk, lycra)",
        },
        {
          label: "Neckline",
          value: "High or mock turtle",
        },
        {
          label: "Sleeve style",
          value: "Short, short flutter, or asymmetrical",
        },
        {
          label: "Pattern",
          value: "Solid",
        },
        {
          label: "Available sizes",
          value: "00 US, 2 US, 4 US, 6 US, 8 US, 10 US, 12 US, 14 US, 16 US",
        },
        {
          label: "Care instructions",
          value: "Dry clean or hand wash cold",
        },
      ],
      referenceBadge: "Only 5 left",
      delivery: {
        postalCode: "9000",
        message: "Shipping calculated at checkout",
        shippingPolicy: true,
      },
      descriptionInitiallyCollapsed: true,
      highlights: [
        "Asymmetrical sleeves create a modern, eye-catching silhouette",
        "Draped body design offers gentle, elegant movement",
        "Roomy fit at waist provides comfort and versatility",
        "High neckline enhances style and sophistication",
        "Premium silk material ensures a luxurious feel and drape",
      ],
      referenceBadgeVariantId: "live-staud-46781055664301",
    },
    variants: [
      {
        id: "live-staud-46781055664301",
        label: "00",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781055697069",
        label: "0",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781055729837",
        label: "2",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781055762605",
        label: "4",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781055795373",
        label: "6",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781055828141",
        label: "8",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781055860909",
        label: "10",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781055893677",
        label: "12",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781055926445",
        label: "14",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781055959213",
        label: "16",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-timmy-shoulder-bag-butterfly-chrome",
    title: "TIMMY SHOULDER BAG | BUTTERFLY CHROME",
    storeId: "live-staud",
    category: "Womenswear",
    color: "BUTTERFLY CHROME",
    images: [
      "/api/reference-media/live-staud-timmy-shoulder-bag-butterfly-chrome-2",
      "/api/reference-media/live-staud-timmy-shoulder-bag-butterfly-chrome-1",
      "/api/reference-media/live-staud-timmy-shoulder-bag-butterfly-chrome-3",
      "/api/reference-media/live-staud-timmy-shoulder-bag-butterfly-chrome-4",
      "/api/reference-media/live-staud-timmy-shoulder-bag-butterfly-chrome-5",
      "/api/reference-media/live-staud-timmy-shoulder-bag-butterfly-chrome-6",
      "/api/reference-media/live-staud-timmy-shoulder-bag-butterfly-chrome-7",
      "/api/reference-media/live-staud-timmy-shoulder-bag-butterfly-chrome-8",
    ],
    price: {
      amount: 41000,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "The Timmy Convertible Shoulder Bag is a versatile statement bag designed for more than one way to wear. Its compact shoulder shape keeps the styling effortless.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf:
        "/api/reference-media/live-staud-timmy-shoulder-bag-butterfly-chrome-2",
      grid: "/api/reference-media/live-staud-timmy-shoulder-bag-butterfly-chrome-2",
    },
    detail: {
      completeDescription: true,
      colorSwatch:
        "/api/reference-media/live-staud-timmy-shoulder-bag-butterfly-chrome-2",
    },
    variants: [
      {
        id: "live-staud-46780986228909",
        label: "BUTTERFLY CHROME",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-myra-top-cigar-multi",
    title: "MYRA TOP | CIGAR MULTI",
    storeId: "live-staud",
    category: "Womenswear",
    color: "CIGAR MULTI",
    images: [
      "/api/reference-media/live-staud-myra-top-cigar-multi-1",
      "/api/reference-media/live-staud-myra-top-cigar-multi-2",
      "/api/reference-media/live-staud-myra-top-cigar-multi-3",
      "/api/reference-media/live-staud-myra-top-cigar-multi-4",
    ],
    price: {
      amount: 28500,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "The Myra Top is a refined, fitted silhouette with an easy elevated feel. Style it with the matching skirt or tailored trousers.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf: "/api/reference-media/live-staud-myra-top-cigar-multi-1",
      grid: "/api/reference-media/live-staud-myra-top-cigar-multi-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch: "/api/reference-media/live-staud-myra-top-cigar-multi-1",
    },
    variants: [
      {
        id: "live-staud-46780959424685",
        label: "XS",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46780959457453",
        label: "S",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46780959490221",
        label: "M",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46780959522989",
        label: "L",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46780959555757",
        label: "XL",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-hunter-culotte-jean-indigo",
    title: "HUNTER CULOTTE JEAN | INDIGO",
    storeId: "live-staud",
    category: "Womenswear",
    color: "INDIGO",
    images: [
      "/api/reference-media/live-staud-hunter-culotte-jean-indigo-1",
      "/api/reference-media/live-staud-hunter-culotte-jean-indigo-2",
      "/api/reference-media/live-staud-hunter-culotte-jean-indigo-3",
      "/api/reference-media/live-staud-hunter-culotte-jean-indigo-4",
      "/api/reference-media/live-staud-hunter-culotte-jean-indigo-5",
      "/api/reference-media/live-staud-hunter-culotte-jean-indigo-6",
    ],
    price: {
      amount: 28500,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "The Hunter Jean is designed with a mid-rise waist and an oversized culotte silhouette. Cut from rigid cotton denim with a cropped inseam, it offers a relaxed fit and a clean, modern shape that pairs effortlessly with everything from boots to sandals.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf: "/api/reference-media/live-staud-hunter-culotte-jean-indigo-1",
      grid: "/api/reference-media/live-staud-hunter-culotte-jean-indigo-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch:
        "/api/reference-media/live-staud-hunter-culotte-jean-indigo-1",
    },
    variants: [
      {
        id: "live-staud-46781035282605",
        label: "23",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781035315373",
        label: "24",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781035348141",
        label: "25",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781035380909",
        label: "26",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781035413677",
        label: "27",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781035446445",
        label: "28",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781035479213",
        label: "29",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781035511981",
        label: "30",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781035544749",
        label: "31",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781035577517",
        label: "32",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781035610285",
        label: "33",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781035643053",
        label: "34",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-harlow-messenger-bag-cigar",
    title: "HARLOW MESSENGER BAG | CIGAR",
    storeId: "live-staud",
    category: "Womenswear",
    color: "CIGAR",
    images: [
      "/api/reference-media/live-staud-harlow-messenger-bag-cigar-2",
      "/api/reference-media/live-staud-harlow-messenger-bag-cigar-1",
      "/api/reference-media/live-staud-harlow-messenger-bag-cigar-3",
      "/api/reference-media/live-staud-harlow-messenger-bag-cigar-4",
      "/api/reference-media/live-staud-harlow-messenger-bag-cigar-5",
      "/api/reference-media/live-staud-harlow-messenger-bag-cigar-6",
    ],
    price: {
      amount: 104500,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "The Harlow Messenger Bag is an easy crossbody silhouette with a refined finish. Whipstitch detailing gives the everyday shape subtle texture.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf: "/api/reference-media/live-staud-harlow-messenger-bag-cigar-2",
      grid: "/api/reference-media/live-staud-harlow-messenger-bag-cigar-2",
    },
    detail: {
      completeDescription: true,
      colorSwatch:
        "/api/reference-media/live-staud-harlow-messenger-bag-cigar-2",
    },
    variants: [
      {
        id: "live-staud-46780986589357",
        label: "CIGAR",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-james-boyfriend-jean-archive",
    title: "JAMES BOYFRIEND JEAN | ARCHIVE",
    storeId: "live-staud",
    category: "Womenswear",
    color: "ARCHIVE",
    images: [
      "/api/reference-media/live-staud-james-boyfriend-jean-archive-1",
      "/api/reference-media/live-staud-james-boyfriend-jean-archive-2",
      "/api/reference-media/live-staud-james-boyfriend-jean-archive-3",
      "/api/reference-media/live-staud-james-boyfriend-jean-archive-4",
      "/api/reference-media/live-staud-james-boyfriend-jean-archive-5",
      "/api/reference-media/live-staud-james-boyfriend-jean-archive-6",
    ],
    price: {
      amount: 27695,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "The James Boyfriend Jean is a timeless denim essential featuring a mid-rise fit that sits comfortably at the hip. Cut with a straight silhouette through the thigh, it tapers subtly toward the ankle for a refined, versatile look. Crafted in rigid denim, this jean develops character and a personalized fit with wear. The straight-cut waistband provides structure and all-day comfort, making it an easy go-to for any occasion.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf: "/api/reference-media/live-staud-james-boyfriend-jean-archive-1",
      grid: "/api/reference-media/live-staud-james-boyfriend-jean-archive-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch:
        "/api/reference-media/live-staud-james-boyfriend-jean-archive-1",
    },
    variants: [
      {
        id: "live-staud-46818267267245",
        label: "24",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46818267300013",
        label: "25",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46818267332781",
        label: "26",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46818267365549",
        label: "27",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46818267398317",
        label: "28",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46818267431085",
        label: "29",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46818267463853",
        label: "30",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46818267496621",
        label: "31",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46818267529389",
        label: "32",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46818267562157",
        label: "33",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46818267594925",
        label: "34",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-birkenstock-loma-suede-faded-khaki",
    title: "BIRKENSTOCK LOMA SUEDE | FADED KHAKI",
    storeId: "live-staud",
    category: "Womenswear",
    color: "FADED KHAKI",
    images: [
      "/api/reference-media/live-staud-birkenstock-loma-suede-faded-khaki-1",
      "/api/reference-media/live-staud-birkenstock-loma-suede-faded-khaki-2",
      "/api/reference-media/live-staud-birkenstock-loma-suede-faded-khaki-3",
      "/api/reference-media/live-staud-birkenstock-loma-suede-faded-khaki-4",
      "/api/reference-media/live-staud-birkenstock-loma-suede-faded-khaki-5",
      "/api/reference-media/live-staud-birkenstock-loma-suede-faded-khaki-6",
      "/api/reference-media/live-staud-birkenstock-loma-suede-faded-khaki-7",
      "/api/reference-media/live-staud-birkenstock-loma-suede-faded-khaki-8",
    ],
    price: {
      amount: 16695,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "Effortless comfort meets understated style with the Birkenstock Loma suede clog. Crafted from soft faded khaki suede, this slip-on silhouette features a wrap-style strap that offers a customizable fit while maintaining the brand's iconic ease. The contoured footbed provides all-day support, making it perfect for casual wear or relaxed weekend dressing.\n\n\n*Please note that this style is only available in Birkenstock's Medium/Narrow Fit. We recommend sizing up.\n\n\nThe Birkenstock + STAUD Loma are only available to ship within the domestic United States.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf:
        "/api/reference-media/live-staud-birkenstock-loma-suede-faded-khaki-1",
      grid: "/api/reference-media/live-staud-birkenstock-loma-suede-faded-khaki-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch:
        "/api/reference-media/live-staud-birkenstock-loma-suede-faded-khaki-1",
    },
    variants: [
      {
        id: "live-staud-47200057262253",
        label: "35",
        availableQuantity: null,
      },
      {
        id: "live-staud-47200057295021",
        label: "36",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-47200057327789",
        label: "37",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-47200057360557",
        label: "38",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-47200057393325",
        label: "39",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-47200057426093",
        label: "40",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-47200057458861",
        label: "41",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-47200057491629",
        label: "42",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-lounge-terry-hoodie-heather-grey",
    title: "LOUNGE TERRY HOODIE | HEATHER GREY",
    storeId: "live-staud",
    category: "Womenswear",
    color: "HEATHER GREY",
    images: [
      "/api/reference-media/live-staud-lounge-terry-hoodie-heather-grey-1",
      "/api/reference-media/live-staud-lounge-terry-hoodie-heather-grey-2",
      "/api/reference-media/live-staud-lounge-terry-hoodie-heather-grey-3",
      "/api/reference-media/live-staud-lounge-terry-hoodie-heather-grey-4",
      "/api/reference-media/live-staud-lounge-terry-hoodie-heather-grey-5",
      "/api/reference-media/live-staud-lounge-terry-hoodie-heather-grey-6",
      "/api/reference-media/live-staud-lounge-terry-hoodie-heather-grey-7",
    ],
    price: {
      amount: 28500,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "Crafted from soft cotton, the Lounge Terry Hoodie features a lived-in worn aesthetic that feels broken in from day one. The generous fit drapes beautifully for an easy, laid-back silhouette perfect for lounging or casual outings. Pair it with the Stroll Terry Pant for a matching set.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf:
        "/api/reference-media/live-staud-lounge-terry-hoodie-heather-grey-1",
      grid: "/api/reference-media/live-staud-lounge-terry-hoodie-heather-grey-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch:
        "/api/reference-media/live-staud-lounge-terry-hoodie-heather-grey-1",
    },
    variants: [
      {
        id: "live-staud-46781057925293",
        label: "XS",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781057958061",
        label: "S",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781057990829",
        label: "M",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781058023597",
        label: "L",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781058056365",
        label: "XL",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-archie-jacket-cigar",
    title: "ARCHIE JACKET | CIGAR",
    storeId: "live-staud",
    category: "Womenswear",
    color: "CIGAR",
    images: [
      "/api/reference-media/live-staud-archie-jacket-cigar-3",
      "/api/reference-media/live-staud-archie-jacket-cigar-1",
      "/api/reference-media/live-staud-archie-jacket-cigar-2",
      "/api/reference-media/live-staud-archie-jacket-cigar-4",
      "/api/reference-media/live-staud-archie-jacket-cigar-5",
      "/api/reference-media/live-staud-archie-jacket-cigar-6",
      "/api/reference-media/live-staud-archie-jacket-cigar-7",
      "/api/reference-media/live-staud-archie-jacket-cigar-8",
    ],
    price: {
      amount: 68500,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "The Archie Jacket is a polished peplum layer with a high neckline and long sleeves. A center-front zipper and snap placket keep the finish streamlined. Designed to define the waist.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf: "/api/reference-media/live-staud-archie-jacket-cigar-3",
      grid: "/api/reference-media/live-staud-archie-jacket-cigar-3",
    },
    detail: {
      completeDescription: true,
      colorSwatch: "/api/reference-media/live-staud-archie-jacket-cigar-3",
    },
    variants: [
      {
        id: "live-staud-46780972499117",
        label: "XS",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46780972531885",
        label: "S",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46780972564653",
        label: "M",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46780972597421",
        label: "L",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46780972630189",
        label: "XL",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-odette-silk-skirt-cigar-black",
    title: "ODETTE SILK SKIRT | CIGAR BLACK",
    storeId: "live-staud",
    category: "Womenswear",
    color: "CIGAR BLACK",
    images: [
      "/api/reference-media/live-staud-odette-silk-skirt-cigar-black-1",
      "/api/reference-media/live-staud-odette-silk-skirt-cigar-black-2",
      "/api/reference-media/live-staud-odette-silk-skirt-cigar-black-3",
      "/api/reference-media/live-staud-odette-silk-skirt-cigar-black-4",
      "/api/reference-media/live-staud-odette-silk-skirt-cigar-black-5",
      "/api/reference-media/live-staud-odette-silk-skirt-cigar-black-6",
      "/api/reference-media/live-staud-odette-silk-skirt-cigar-black-7",
      "/api/reference-media/live-staud-odette-silk-skirt-cigar-black-8",
      "/api/reference-media/live-staud-odette-silk-skirt-cigar-black-9",
    ],
    price: {
      amount: 57000,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "The Odette Silk Skirt is a slim-fitting, mid-rise midi skirt crafted in silk dupioni. Featuring a contrast poplin waistband and twisted bubble hem, the structured fabric takes a sculptural finish, while an elasticized drawstring waist keeps the fit easy. Pair with the Sade Silk Top for a matching set.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf: "/api/reference-media/live-staud-odette-silk-skirt-cigar-black-1",
      grid: "/api/reference-media/live-staud-odette-silk-skirt-cigar-black-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch:
        "/api/reference-media/live-staud-odette-silk-skirt-cigar-black-1",
    },
    variants: [
      {
        id: "live-staud-46781052256429",
        label: "XS",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781052289197",
        label: "S",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781052321965",
        label: "M",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781052354733",
        label: "L",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781052387501",
        label: "XL",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-hester-satchel-toast",
    title: "HESTER SATCHEL | TOAST",
    storeId: "live-staud",
    category: "Womenswear",
    color: "TOAST",
    images: [
      "/api/reference-media/live-staud-hester-satchel-toast-1",
      "/api/reference-media/live-staud-hester-satchel-toast-2",
      "/api/reference-media/live-staud-hester-satchel-toast-3",
      "/api/reference-media/live-staud-hester-satchel-toast-4",
      "/api/reference-media/live-staud-hester-satchel-toast-5",
      "/api/reference-media/live-staud-hester-satchel-toast-6",
    ],
    price: {
      amount: 75500,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "The Hester Satchel is a polished structured bag with a compact silhouette. It is designed to bring an elevated finish to everyday looks.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf: "/api/reference-media/live-staud-hester-satchel-toast-1",
      grid: "/api/reference-media/live-staud-hester-satchel-toast-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch: "/api/reference-media/live-staud-hester-satchel-toast-1",
    },
    variants: [
      {
        id: "live-staud-46780986458285",
        label: "TOAST",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-miles-zip-ankle-boot-cigar",
    title: "MILES ZIP ANKLE BOOT | CIGAR",
    storeId: "live-staud",
    category: "Womenswear",
    color: "CIGAR",
    images: [
      "/api/reference-media/live-staud-miles-zip-ankle-boot-cigar-1",
      "/api/reference-media/live-staud-miles-zip-ankle-boot-cigar-2",
      "/api/reference-media/live-staud-miles-zip-ankle-boot-cigar-3",
      "/api/reference-media/live-staud-miles-zip-ankle-boot-cigar-4",
      "/api/reference-media/live-staud-miles-zip-ankle-boot-cigar-5",
      "/api/reference-media/live-staud-miles-zip-ankle-boot-cigar-6",
      "/api/reference-media/live-staud-miles-zip-ankle-boot-cigar-7",
      "/api/reference-media/live-staud-miles-zip-ankle-boot-cigar-8",
      "/api/reference-media/live-staud-miles-zip-ankle-boot-cigar-9",
    ],
    price: {
      amount: 57500,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "The Miles Zip Ankle Boot is a polished everyday boot with a clean, versatile shape. A zip closure keeps the finish streamlined.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf: "/api/reference-media/live-staud-miles-zip-ankle-boot-cigar-1",
      grid: "/api/reference-media/live-staud-miles-zip-ankle-boot-cigar-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch:
        "/api/reference-media/live-staud-miles-zip-ankle-boot-cigar-1",
    },
    variants: [
      {
        id: "live-staud-46813403775149",
        label: "35",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46813403807917",
        label: "35.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46813403840685",
        label: "36",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46813403873453",
        label: "36.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46813403906221",
        label: "37",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46813403938989",
        label: "37.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46813403971757",
        label: "38",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46813404004525",
        label: "38.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46813404037293",
        label: "39",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46813404070061",
        label: "39.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46813404102829",
        label: "40",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46813404135597",
        label: "40.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46813404168365",
        label: "41",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46813404201133",
        label: "41.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46813404233901",
        label: "42",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-charli-silk-top-tapestry-midnight",
    title: "CHARLI SILK TOP | TAPESTRY MIDNIGHT",
    storeId: "live-staud",
    category: "Womenswear",
    color: "TAPESTRY MIDNIGHT",
    images: [
      "/api/reference-media/live-staud-charli-silk-top-tapestry-midnight-1",
      "/api/reference-media/live-staud-charli-silk-top-tapestry-midnight-2",
      "/api/reference-media/live-staud-charli-silk-top-tapestry-midnight-3",
    ],
    price: {
      amount: 39195,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "The Charli Silk Top features a fitted halter silhouette in printed silk. A twisted chiffon strap frames the neckline, while a low back adds an unexpected finish.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf:
        "/api/reference-media/live-staud-charli-silk-top-tapestry-midnight-1",
      grid: "/api/reference-media/live-staud-charli-silk-top-tapestry-midnight-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch:
        "/api/reference-media/live-staud-charli-silk-top-tapestry-midnight-1",
    },
    variants: [
      {
        id: "live-staud-47278108803245",
        label: "XS",
        availableQuantity: null,
      },
      {
        id: "live-staud-47278108836013",
        label: "S",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-47278108868781",
        label: "M",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-47278108901549",
        label: "L",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-47278108934317",
        label: "XL",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-bea-mule-fawn-haircalf",
    title: "BEA MULE | FAWN HAIRCALF",
    storeId: "live-staud",
    category: "Womenswear",
    color: "FAWN HAIRCALF",
    images: [
      "/api/reference-media/live-staud-bea-mule-fawn-haircalf-1",
      "/api/reference-media/live-staud-bea-mule-fawn-haircalf-2",
      "/api/reference-media/live-staud-bea-mule-fawn-haircalf-3",
      "/api/reference-media/live-staud-bea-mule-fawn-haircalf-4",
      "/api/reference-media/live-staud-bea-mule-fawn-haircalf-5",
      "/api/reference-media/live-staud-bea-mule-fawn-haircalf-6",
      "/api/reference-media/live-staud-bea-mule-fawn-haircalf-7",
    ],
    price: {
      amount: 46000,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "Updated in a printed haircalf, the Bea Mule takes our signature Brigitte silhouette and elevates it with a chic square toe and enhanced coverage. Crafted in supple leather with a comfortable medium heel, this style strikes the perfect balance between polished and effortless—ready for everything from office days to weekend outings.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf: "/api/reference-media/live-staud-bea-mule-fawn-haircalf-1",
      grid: "/api/reference-media/live-staud-bea-mule-fawn-haircalf-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch: "/api/reference-media/live-staud-bea-mule-fawn-haircalf-1",
    },
    variants: [
      {
        id: "live-staud-46781025353901",
        label: "35",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781025386669",
        label: "35.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781025419437",
        label: "36",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781025452205",
        label: "36.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781025484973",
        label: "37",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781025517741",
        label: "37.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781025550509",
        label: "38",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781025583277",
        label: "38.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781025616045",
        label: "39",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781025648813",
        label: "39.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781025681581",
        label: "40",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781025714349",
        label: "40.5",
        availableQuantity: null,
      },
      {
        id: "live-staud-46781025747117",
        label: "41",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781025779885",
        label: "41.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781025812653",
        label: "42",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-maude-mini-carryall-black-snake",
    title: "MAUDE MINI CARRYALL | BLACK SNAKE",
    storeId: "live-staud",
    category: "Womenswear",
    color: "BLACK SNAKE",
    images: [
      "/api/reference-media/live-staud-maude-mini-carryall-black-snake-1",
      "/api/reference-media/live-staud-maude-mini-carryall-black-snake-2",
      "/api/reference-media/live-staud-maude-mini-carryall-black-snake-3",
      "/api/reference-media/live-staud-maude-mini-carryall-black-snake-4",
      "/api/reference-media/live-staud-maude-mini-carryall-black-snake-5",
      "/api/reference-media/live-staud-maude-mini-carryall-black-snake-6",
      "/api/reference-media/live-staud-maude-mini-carryall-black-snake-7",
      "/api/reference-media/live-staud-maude-mini-carryall-black-snake-8",
      "/api/reference-media/live-staud-maude-mini-carryall-black-snake-9",
    ],
    price: {
      amount: 57500,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "The Maude Mini Carryall reimagines our signature silhouette in a compact size, perfect for date nights and evenings out. Featuring the Maude family's signature rounded handles, a front flap closure, interior zip pocket, and adjustable thin crossbody strap, it can be carried by hand or worn crossbody for versatile styling. Crafted in snake-embossed leather for a refined, textured finish.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf:
        "/api/reference-media/live-staud-maude-mini-carryall-black-snake-1",
      grid: "/api/reference-media/live-staud-maude-mini-carryall-black-snake-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch:
        "/api/reference-media/live-staud-maude-mini-carryall-black-snake-1",
    },
    variants: [
      {
        id: "live-staud-46781050585261",
        label: "BLACK SNAKE",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-enya-top-sesame",
    title: "ENYA TOP | SESAME",
    storeId: "live-staud",
    category: "Womenswear",
    color: "SESAME",
    images: [
      "/api/reference-media/live-staud-enya-top-sesame-1",
      "/api/reference-media/live-staud-enya-top-sesame-2",
      "/api/reference-media/live-staud-enya-top-sesame-3",
      "/api/reference-media/live-staud-enya-top-sesame-4",
      "/api/reference-media/live-staud-enya-top-sesame-5",
    ],
    price: {
      amount: 34000,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "This single-shoulder silhouette top is defined by an adjustable tie that lets you customize the fit and drape to suit your style. Crafted from a lightweight merino wool, the Enya Top is perfect for layering or wearing solo across seasons.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf: "/api/reference-media/live-staud-enya-top-sesame-1",
      grid: "/api/reference-media/live-staud-enya-top-sesame-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch: "/api/reference-media/live-staud-enya-top-sesame-1",
    },
    variants: [
      {
        id: "live-staud-46781044129965",
        label: "XS",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781044162733",
        label: "S",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781044195501",
        label: "M",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781044228269",
        label: "L",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781044261037",
        label: "XL",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-crest-skirt-fawn-haircalf",
    title: "CREST SKIRT | FAWN HAIRCALF",
    storeId: "live-staud",
    category: "Womenswear",
    color: "FAWN HAIRCALF",
    images: [
      "/api/reference-media/live-staud-crest-skirt-fawn-haircalf-1",
      "/api/reference-media/live-staud-crest-skirt-fawn-haircalf-2",
      "/api/reference-media/live-staud-crest-skirt-fawn-haircalf-3",
    ],
    price: {
      amount: 161000,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "The Crest Skirt is a fitted mini crafted in genuine haircalf. Its fawn spot print and brushed pile give the clean silhouette natural depth. Finished with a front seam and center-back zipper.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf: "/api/reference-media/live-staud-crest-skirt-fawn-haircalf-1",
      grid: "/api/reference-media/live-staud-crest-skirt-fawn-haircalf-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch:
        "/api/reference-media/live-staud-crest-skirt-fawn-haircalf-1",
    },
    variants: [
      {
        id: "live-staud-46781044490413",
        label: "00",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781044523181",
        label: "0",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781044555949",
        label: "2",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781044588717",
        label: "4",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781044621485",
        label: "6",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781044654253",
        label: "8",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781044687021",
        label: "10",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781044719789",
        label: "12",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781044752557",
        label: "14",
        availableQuantity: null,
      },
      {
        id: "live-staud-46781044785325",
        label: "16",
        availableQuantity: null,
      },
    ],
  },
  {
    id: "live-staud-wally-boot-espresso-snake",
    title: "WALLY BOOT | ESPRESSO SNAKE",
    storeId: "live-staud",
    category: "Womenswear",
    color: "ESPRESSO SNAKE",
    images: [
      "/api/reference-media/live-staud-wally-boot-espresso-snake-1",
      "/api/reference-media/live-staud-wally-boot-espresso-snake-2",
      "/api/reference-media/live-staud-wally-boot-espresso-snake-3",
      "/api/reference-media/live-staud-wally-boot-espresso-snake-4",
      "/api/reference-media/live-staud-wally-boot-espresso-snake-5",
      "/api/reference-media/live-staud-wally-boot-espresso-snake-6",
      "/api/reference-media/live-staud-wally-boot-espresso-snake-7",
      "/api/reference-media/live-staud-wally-boot-espresso-snake-8",
      "/api/reference-media/live-staud-wally-boot-espresso-snake-9",
    ],
    price: {
      amount: 81000,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "The Wally Boot is a versatile everyday boot with a clean, easy profile. It pairs naturally with denim, tailoring, and dresses.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf: "/api/reference-media/live-staud-wally-boot-espresso-snake-1",
      grid: "/api/reference-media/live-staud-wally-boot-espresso-snake-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch:
        "/api/reference-media/live-staud-wally-boot-espresso-snake-1",
    },
    variants: [
      {
        id: "live-staud-46781024698541",
        label: "35",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781024731309",
        label: "35.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781024764077",
        label: "36",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781024796845",
        label: "36.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781024829613",
        label: "37",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781024862381",
        label: "37.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781024895149",
        label: "38",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781024927917",
        label: "38.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781024960685",
        label: "39",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781024993453",
        label: "39.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781025026221",
        label: "40",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781025058989",
        label: "40.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781025091757",
        label: "41",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781025124525",
        label: "41.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781025157293",
        label: "42",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-myles-shirt-jacket-oyster-corduroy",
    title: "MYLES SHIRT JACKET | OYSTER CORDUROY",
    storeId: "live-staud",
    category: "Womenswear",
    color: "OYSTER CORDUROY",
    images: [
      "/api/reference-media/live-staud-myles-shirt-jacket-oyster-corduroy-1",
      "/api/reference-media/live-staud-myles-shirt-jacket-oyster-corduroy-2",
      "/api/reference-media/live-staud-myles-shirt-jacket-oyster-corduroy-3",
      "/api/reference-media/live-staud-myles-shirt-jacket-oyster-corduroy-4",
      "/api/reference-media/live-staud-myles-shirt-jacket-oyster-corduroy-5",
      "/api/reference-media/live-staud-myles-shirt-jacket-oyster-corduroy-6",
      "/api/reference-media/live-staud-myles-shirt-jacket-oyster-corduroy-7",
    ],
    price: {
      amount: 34000,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "The Myles Shirt Jacket is an easy corduroy layer with a relaxed, structured feel. Wear it open over a tee or buttoned as a top. Pair it back to the Gus Relaxed Jean for a coordinating set.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf:
        "/api/reference-media/live-staud-myles-shirt-jacket-oyster-corduroy-1",
      grid: "/api/reference-media/live-staud-myles-shirt-jacket-oyster-corduroy-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch:
        "/api/reference-media/live-staud-myles-shirt-jacket-oyster-corduroy-1",
    },
    variants: [
      {
        id: "live-staud-46781042393261",
        label: "XS",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781042426029",
        label: "S",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781042458797",
        label: "M",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781042491565",
        label: "L",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781042524333",
        label: "XL",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-phare-silk-dress-butterfly-fuchsia",
    title: "PHARE SILK DRESS | BUTTERFLY FUCHSIA",
    storeId: "live-staud",
    category: "Womenswear",
    color: "BUTTERFLY FUCHSIA",
    images: [
      "/api/reference-media/live-staud-phare-silk-dress-butterfly-fuchsia-1",
      "/api/reference-media/live-staud-phare-silk-dress-butterfly-fuchsia-2",
      "/api/reference-media/live-staud-phare-silk-dress-butterfly-fuchsia-3",
      "/api/reference-media/live-staud-phare-silk-dress-butterfly-fuchsia-4",
      "/api/reference-media/live-staud-phare-silk-dress-butterfly-fuchsia-5",
    ],
    price: {
      amount: 83500,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "The Phare Silk Dress is an off-the-shoulder silhouette fitted through the waist and hip. Pleating at the front and back creates soft shape. Finished with a side-seam zipper..\nDue to the nature of the pattern, placement may vary from garment to garment.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf:
        "/api/reference-media/live-staud-phare-silk-dress-butterfly-fuchsia-1",
      grid: "/api/reference-media/live-staud-phare-silk-dress-butterfly-fuchsia-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch:
        "/api/reference-media/live-staud-phare-silk-dress-butterfly-fuchsia-1",
    },
    variants: [
      {
        id: "live-staud-46781048422573",
        label: "00",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781048455341",
        label: "0",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781048488109",
        label: "2",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781048520877",
        label: "4",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781048553645",
        label: "6",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781048586413",
        label: "8",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781048619181",
        label: "10",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781048651949",
        label: "12",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781048684717",
        label: "14",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781048717485",
        label: "16",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-tommy-beaded-bag-millefiore-2-0",
    title: "TOMMY BEADED BAG | MILLEFIORE 2.0",
    storeId: "live-staud",
    category: "Womenswear",
    color: "MILLEFIORE 2.0",
    images: [
      "/api/reference-media/live-staud-tommy-beaded-bag-millefiore-2-0-1",
      "/api/reference-media/live-staud-tommy-beaded-bag-millefiore-2-0-2",
      "/api/reference-media/live-staud-tommy-beaded-bag-millefiore-2-0-3",
      "/api/reference-media/live-staud-tommy-beaded-bag-millefiore-2-0-4",
      "/api/reference-media/live-staud-tommy-beaded-bag-millefiore-2-0-5",
      "/api/reference-media/live-staud-tommy-beaded-bag-millefiore-2-0-6",
    ],
    price: {
      amount: 41000,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "Our iconic Tommy Millefiori pattern returns—reimagined as Millefiore 2.0. This limited-edition hand-beaded shoulder bag showcases the evolution of our original design with meticulous beadwork and vegan leather piping. A single flap closure secures your essentials, while an inner zip pocket and back slip pocket offer practical storage. Artisanal craftsmanship meets contemporary style.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf:
        "/api/reference-media/live-staud-tommy-beaded-bag-millefiore-2-0-1",
      grid: "/api/reference-media/live-staud-tommy-beaded-bag-millefiore-2-0-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch:
        "/api/reference-media/live-staud-tommy-beaded-bag-millefiore-2-0-1",
    },
    variants: [
      {
        id: "live-staud-46780985671853",
        label: "MILLEFIORE 2.0",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-hunter-culotte-jean-archive",
    title: "HUNTER CULOTTE JEAN | ARCHIVE",
    storeId: "live-staud",
    category: "Womenswear",
    color: "ARCHIVE",
    images: [
      "/api/reference-media/live-staud-hunter-culotte-jean-archive-1",
      "/api/reference-media/live-staud-hunter-culotte-jean-archive-2",
      "/api/reference-media/live-staud-hunter-culotte-jean-archive-3",
      "/api/reference-media/live-staud-hunter-culotte-jean-archive-4",
      "/api/reference-media/live-staud-hunter-culotte-jean-archive-5",
    ],
    price: {
      amount: 28500,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "The Hunter Jean is designed with a mid-rise waist and an oversized culotte silhouette. Cut from rigid cotton denim with a cropped inseam, it offers a relaxed fit and a clean, modern shape that pairs effortlessly with everything from boots to sandals.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf: "/api/reference-media/live-staud-hunter-culotte-jean-archive-1",
      grid: "/api/reference-media/live-staud-hunter-culotte-jean-archive-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch:
        "/api/reference-media/live-staud-hunter-culotte-jean-archive-1",
    },
    variants: [
      {
        id: "live-staud-46781034725549",
        label: "23",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781034758317",
        label: "24",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781034791085",
        label: "25",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781034823853",
        label: "26",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781034856621",
        label: "27",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781034889389",
        label: "28",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781034922157",
        label: "29",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781034954925",
        label: "30",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781034987693",
        label: "31",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781035020461",
        label: "32",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781035053229",
        label: "33",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781035085997",
        label: "34",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-dillon-tee-potter-stripe-multi",
    title: "DILLON TEE | POTTER STRIPE MULTI",
    storeId: "live-staud",
    category: "Womenswear",
    color: "POTTER STRIPE MULTI",
    images: [
      "/api/reference-media/live-staud-dillon-tee-potter-stripe-multi-4",
      "/api/reference-media/live-staud-dillon-tee-potter-stripe-multi-1",
      "/api/reference-media/live-staud-dillon-tee-potter-stripe-multi-2",
      "/api/reference-media/live-staud-dillon-tee-potter-stripe-multi-3",
    ],
    price: {
      amount: 26000,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "The Dillon Tee is a slim, easy-fit style with the look of two layers. A simple essential with a little more dimension.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf: "/api/reference-media/live-staud-dillon-tee-potter-stripe-multi-4",
      grid: "/api/reference-media/live-staud-dillon-tee-potter-stripe-multi-4",
    },
    detail: {
      completeDescription: true,
      colorSwatch:
        "/api/reference-media/live-staud-dillon-tee-potter-stripe-multi-4",
    },
    variants: [
      {
        id: "live-staud-46780959064237",
        label: "XS",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46780959097005",
        label: "S",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46780959129773",
        label: "M",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46780959162541",
        label: "L",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46780959195309",
        label: "XL",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-aero-short-pine-shadow",
    title: "AERO SHORT | PINE SHADOW",
    storeId: "live-staud",
    category: "Womenswear",
    color: "PINE SHADOW",
    images: [
      "/api/reference-media/live-staud-aero-short-pine-shadow-1",
      "/api/reference-media/live-staud-aero-short-pine-shadow-2",
      "/api/reference-media/live-staud-aero-short-pine-shadow-3",
      "/api/reference-media/live-staud-aero-short-pine-shadow-4",
      "/api/reference-media/live-staud-aero-short-pine-shadow-5",
      "/api/reference-media/live-staud-aero-short-pine-shadow-6",
    ],
    price: {
      amount: 26000,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "Effortless comfort meets contemporary style with these sporty satin shorts. Designed with a pull-on waistband for easy wear and contrast piping that adds a sharp, modern edge. Perfect for dressing up or down.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf: "/api/reference-media/live-staud-aero-short-pine-shadow-1",
      grid: "/api/reference-media/live-staud-aero-short-pine-shadow-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch: "/api/reference-media/live-staud-aero-short-pine-shadow-1",
    },
    variants: [
      {
        id: "live-staud-46780948938925",
        label: "XS",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46780948971693",
        label: "S",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46780949004461",
        label: "M",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46780949037229",
        label: "L",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46780949069997",
        label: "XL",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-emmett-boot-black",
    title: "EMMETT BOOT | BLACK",
    storeId: "live-staud",
    category: "Womenswear",
    color: "BLACK",
    images: [
      "/api/reference-media/live-staud-emmett-boot-black-1",
      "/api/reference-media/live-staud-emmett-boot-black-2",
      "/api/reference-media/live-staud-emmett-boot-black-3",
      "/api/reference-media/live-staud-emmett-boot-black-4",
      "/api/reference-media/live-staud-emmett-boot-black-5",
      "/api/reference-media/live-staud-emmett-boot-black-6",
      "/api/reference-media/live-staud-emmett-boot-black-7",
    ],
    price: {
      amount: 64000,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "The Emmett Boot is a versatile everyday boot with a clean, polished profile. Style it with denim or a mini for an easy finish.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf: "/api/reference-media/live-staud-emmett-boot-black-1",
      grid: "/api/reference-media/live-staud-emmett-boot-black-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch: "/api/reference-media/live-staud-emmett-boot-black-1",
    },
    variants: [
      {
        id: "live-staud-46813402464429",
        label: "35",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46813402497197",
        label: "35.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46813402529965",
        label: "36",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46813402562733",
        label: "36.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46813402595501",
        label: "37",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46813402628269",
        label: "37.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46813402661037",
        label: "38",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46813402693805",
        label: "38.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46813402726573",
        label: "39",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46813402759341",
        label: "39.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46813402792109",
        label: "40",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46813402824877",
        label: "40.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46813402857645",
        label: "41",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46813402890413",
        label: "41.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46813402923181",
        label: "42",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-flo-pant-dark-oak",
    title: "FLO PANT | DARK OAK",
    storeId: "live-staud",
    category: "Womenswear",
    color: "DARK OAK",
    images: [
      "/api/reference-media/live-staud-flo-pant-dark-oak-1",
      "/api/reference-media/live-staud-flo-pant-dark-oak-2",
      "/api/reference-media/live-staud-flo-pant-dark-oak-3",
      "/api/reference-media/live-staud-flo-pant-dark-oak-4",
      "/api/reference-media/live-staud-flo-pant-dark-oak-5",
      "/api/reference-media/live-staud-flo-pant-dark-oak-6",
    ],
    price: {
      amount: 34000,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "Sporty twist meets everyday comfort in these wide-leg pants crafted from breathable basketball mesh. The elasticized waistband ensures an easy, secure fit, while the relaxed silhouette makes it perfect for movement. Pull on and go—effortless style for active days.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf: "/api/reference-media/live-staud-flo-pant-dark-oak-1",
      grid: "/api/reference-media/live-staud-flo-pant-dark-oak-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch: "/api/reference-media/live-staud-flo-pant-dark-oak-1",
    },
    variants: [
      {
        id: "live-staud-46781043245229",
        label: "XS",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781043277997",
        label: "S",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781043310765",
        label: "M",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781043343533",
        label: "L",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781043376301",
        label: "XL",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-maude-satchel-espresso-snake",
    title: "MAUDE SATCHEL | ESPRESSO SNAKE",
    storeId: "live-staud",
    category: "Womenswear",
    color: "ESPRESSO SNAKE",
    images: [
      "/api/reference-media/live-staud-maude-satchel-espresso-snake-1",
      "/api/reference-media/live-staud-maude-satchel-espresso-snake-2",
      "/api/reference-media/live-staud-maude-satchel-espresso-snake-3",
      "/api/reference-media/live-staud-maude-satchel-espresso-snake-4",
      "/api/reference-media/live-staud-maude-satchel-espresso-snake-5",
      "/api/reference-media/live-staud-maude-satchel-espresso-snake-6",
      "/api/reference-media/live-staud-maude-satchel-espresso-snake-7",
      "/api/reference-media/live-staud-maude-satchel-espresso-snake-8",
    ],
    price: {
      amount: 57500,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "Meet your new favorite everyday bag. The Maude Satchel features a structured silhouette with rounded top handles and a removable wide shoulder strap for versatile styling. Spacious enough to fit most laptops up to 13–14 inches, it features a front phone pocket for easy access and a zip closure to keep your belongings secure. Crafted from slightly shiny, snake-embossed leather for a refined, textured finish.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf: "/api/reference-media/live-staud-maude-satchel-espresso-snake-1",
      grid: "/api/reference-media/live-staud-maude-satchel-espresso-snake-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch:
        "/api/reference-media/live-staud-maude-satchel-espresso-snake-1",
    },
    variants: [
      {
        id: "live-staud-46781051273389",
        label: "ESPRESSO SNAKE",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-serrano-cashmere-relaxed-crew-cosmos",
    title: "SERRANO CASHMERE RELAXED CREW | COSMOS",
    storeId: "live-staud",
    category: "Womenswear",
    color: "COSMOS",
    images: [
      "/api/reference-media/live-staud-serrano-cashmere-relaxed-crew-cosmos-1",
      "/api/reference-media/live-staud-serrano-cashmere-relaxed-crew-cosmos-2",
      "/api/reference-media/live-staud-serrano-cashmere-relaxed-crew-cosmos-3",
    ],
    price: {
      amount: 55000,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "A classic crewneck sweater made of 100% cashmere, the Serrano offers a relaxed, slightly boxy fit for added ease. Wear this style with your trouser of choice or over your favorite skirt.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf:
        "/api/reference-media/live-staud-serrano-cashmere-relaxed-crew-cosmos-1",
      grid: "/api/reference-media/live-staud-serrano-cashmere-relaxed-crew-cosmos-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch:
        "/api/reference-media/live-staud-serrano-cashmere-relaxed-crew-cosmos-1",
    },
    variants: [
      {
        id: "live-staud-46780944842925",
        label: "XS",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46780944875693",
        label: "S",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46780944908461",
        label: "M",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46780944941229",
        label: "L",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46780944973997",
        label: "XL",
        availableQuantity: null,
      },
    ],
  },
  {
    id: "live-staud-teddy-cropped-with-raw-hem-stone-blue",
    title: "TEDDY CROPPED WITH RAW HEM | STONE BLUE",
    storeId: "live-staud",
    category: "Womenswear",
    color: "STONE BLUE",
    images: [
      "/api/reference-media/live-staud-teddy-cropped-with-raw-hem-stone-blue-1",
      "/api/reference-media/live-staud-teddy-cropped-with-raw-hem-stone-blue-2",
      "/api/reference-media/live-staud-teddy-cropped-with-raw-hem-stone-blue-3",
      "/api/reference-media/live-staud-teddy-cropped-with-raw-hem-stone-blue-4",
      "/api/reference-media/live-staud-teddy-cropped-with-raw-hem-stone-blue-5",
      "/api/reference-media/live-staud-teddy-cropped-with-raw-hem-stone-blue-6",
    ],
    price: {
      amount: 25595,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "The Teddy Jean is a classic straight-leg silhouette with an easy mid-rise waist. Crafted from Italian denim, it has a flattering V-shaped yoke at the back. Complete with antique-finish hardware and a logo-embroidered button fly.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf:
        "/api/reference-media/live-staud-teddy-cropped-with-raw-hem-stone-blue-1",
      grid: "/api/reference-media/live-staud-teddy-cropped-with-raw-hem-stone-blue-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch:
        "/api/reference-media/live-staud-teddy-cropped-with-raw-hem-stone-blue-1",
    },
    variants: [
      {
        id: "live-staud-46818267627693",
        label: "23",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46818267660461",
        label: "24",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46818267693229",
        label: "25",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46818267725997",
        label: "26",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46818267758765",
        label: "27",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46818267791533",
        label: "28",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46818267824301",
        label: "29",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46818267857069",
        label: "30",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46818267889837",
        label: "31",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46818267922605",
        label: "32",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46818267955373",
        label: "33",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46818267988141",
        label: "34",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-cecile-silk-scarf-studio",
    title: "CECILE SILK SCARF | STUDIO",
    storeId: "live-staud",
    category: "Womenswear",
    color: "STUDIO",
    images: [
      "/api/reference-media/live-staud-cecile-silk-scarf-studio-1",
      "/api/reference-media/live-staud-cecile-silk-scarf-studio-2",
      "/api/reference-media/live-staud-cecile-silk-scarf-studio-3",
      "/api/reference-media/live-staud-cecile-silk-scarf-studio-4",
      "/api/reference-media/live-staud-cecile-silk-scarf-studio-5",
    ],
    price: {
      amount: 16500,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "The Cecile Silk Scarf is a printed silk accessory made for endless styling. Tie it at the neck, in the hair, or onto a favorite bag.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf: "/api/reference-media/live-staud-cecile-silk-scarf-studio-1",
      grid: "/api/reference-media/live-staud-cecile-silk-scarf-studio-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch: "/api/reference-media/live-staud-cecile-silk-scarf-studio-1",
    },
    variants: [
      {
        id: "live-staud-46781053862061",
        label: "STUDIO",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-kai-jean-greige",
    title: "KAI JEAN | GREIGE",
    storeId: "live-staud",
    category: "Womenswear",
    color: "GREIGE",
    images: [
      "/api/reference-media/live-staud-kai-jean-greige-1",
      "/api/reference-media/live-staud-kai-jean-greige-2",
      "/api/reference-media/live-staud-kai-jean-greige-3",
      "/api/reference-media/live-staud-kai-jean-greige-4",
      "/api/reference-media/live-staud-kai-jean-greige-5",
      "/api/reference-media/live-staud-kai-jean-greige-6",
      "/api/reference-media/live-staud-kai-jean-greige-7",
      "/api/reference-media/live-staud-kai-jean-greige-8",
      "/api/reference-media/live-staud-kai-jean-greige-9",
      "/api/reference-media/live-staud-kai-jean-greige-10",
      "/api/reference-media/live-staud-kai-jean-greige-11",
    ],
    price: {
      amount: 30500,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "The Kai Jean is designed with a low-rise waist and a clean, waistband-free silhouette for a modern, streamlined look. Cut with a straight leg and full-length inseam, it offers an easy, relaxed fit and is finished with utility patch pockets.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf: "/api/reference-media/live-staud-kai-jean-greige-1",
      grid: "/api/reference-media/live-staud-kai-jean-greige-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch: "/api/reference-media/live-staud-kai-jean-greige-1",
    },
    variants: [
      {
        id: "live-staud-46781032399021",
        label: "23",
        availableQuantity: null,
      },
      {
        id: "live-staud-46781032431789",
        label: "24",
        availableQuantity: null,
      },
      {
        id: "live-staud-46781032464557",
        label: "25",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781032497325",
        label: "26",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781032530093",
        label: "27",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781032562861",
        label: "28",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781032595629",
        label: "29",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781032628397",
        label: "30",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781032661165",
        label: "31",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781032693933",
        label: "32",
        availableQuantity: null,
      },
      {
        id: "live-staud-46781032726701",
        label: "33",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781032759469",
        label: "34",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-moon-metal-keeper-belt-26-mm-cigar",
    title: "MOON METAL KEEPER BELT - 26 MM | CIGAR",
    storeId: "live-staud",
    category: "Womenswear",
    color: "CIGAR",
    images: [
      "/api/reference-media/live-staud-moon-metal-keeper-belt-26-mm-cigar-1",
      "/api/reference-media/live-staud-moon-metal-keeper-belt-26-mm-cigar-2",
      "/api/reference-media/live-staud-moon-metal-keeper-belt-26-mm-cigar-3",
      "/api/reference-media/live-staud-moon-metal-keeper-belt-26-mm-cigar-4",
    ],
    price: {
      amount: 22500,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "The Moon Metal Keeper Belt is a slim leather belt with a polished metal keeper. An easy finishing touch for denim, trousers, and dresses.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf:
        "/api/reference-media/live-staud-moon-metal-keeper-belt-26-mm-cigar-1",
      grid: "/api/reference-media/live-staud-moon-metal-keeper-belt-26-mm-cigar-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch:
        "/api/reference-media/live-staud-moon-metal-keeper-belt-26-mm-cigar-1",
    },
    variants: [
      {
        id: "live-staud-46781058252973",
        label: "XS/S",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781058285741",
        label: "M/L",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-norman-sweater-pinot-multi",
    title: "NORMAN SWEATER | PINOT MULTI",
    storeId: "live-staud",
    category: "Womenswear",
    color: "PINOT MULTI",
    images: [
      "/api/reference-media/live-staud-norman-sweater-pinot-multi-1",
      "/api/reference-media/live-staud-norman-sweater-pinot-multi-2",
      "/api/reference-media/live-staud-norman-sweater-pinot-multi-3",
      "/api/reference-media/live-staud-norman-sweater-pinot-multi-4",
      "/api/reference-media/live-staud-norman-sweater-pinot-multi-5",
      "/api/reference-media/live-staud-norman-sweater-pinot-multi-6",
    ],
    price: {
      amount: 45500,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "The Norman Sweater is an oversized knit with a triple-layer neckline trim. Its easy silhouette makes it an effortless cold-weather layer.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf: "/api/reference-media/live-staud-norman-sweater-pinot-multi-1",
      grid: "/api/reference-media/live-staud-norman-sweater-pinot-multi-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch:
        "/api/reference-media/live-staud-norman-sweater-pinot-multi-1",
    },
    variants: [
      {
        id: "live-staud-46781043966125",
        label: "XS",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781043998893",
        label: "S",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781044031661",
        label: "M",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781044064429",
        label: "L",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781044097197",
        label: "XL",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-fen-skirt-afterglow",
    title: "FEN SKIRT | AFTERGLOW",
    storeId: "live-staud",
    category: "Womenswear",
    color: "AFTERGLOW",
    images: [
      "/api/reference-media/live-staud-fen-skirt-afterglow-1",
      "/api/reference-media/live-staud-fen-skirt-afterglow-2",
      "/api/reference-media/live-staud-fen-skirt-afterglow-3",
      "/api/reference-media/live-staud-fen-skirt-afterglow-4",
      "/api/reference-media/live-staud-fen-skirt-afterglow-5",
      "/api/reference-media/live-staud-fen-skirt-afterglow-6",
    ],
    price: {
      amount: 63500,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "The Fen Skirt is a fully lined low-rise midi in sequin paillettes. A feathered hem gives the sleek silhouette a soft statement finish. Finished with waistband piping and an invisible side zipper.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf: "/api/reference-media/live-staud-fen-skirt-afterglow-1",
      grid: "/api/reference-media/live-staud-fen-skirt-afterglow-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch: "/api/reference-media/live-staud-fen-skirt-afterglow-1",
    },
    variants: [
      {
        id: "live-staud-46780969091245",
        label: "00",
        availableQuantity: null,
      },
      {
        id: "live-staud-46780969124013",
        label: "0",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46780969156781",
        label: "2",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46780969189549",
        label: "4",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46780969222317",
        label: "6",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46780969255085",
        label: "8",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46780969287853",
        label: "10",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46780969320621",
        label: "12",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46780969353389",
        label: "14",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46780969386157",
        label: "16",
        availableQuantity: null,
      },
    ],
  },
  {
    id: "live-staud-brigitte-peep-toe-wedge-black-satin",
    title: "BRIGITTE PEEP TOE WEDGE | BLACK SATIN",
    storeId: "live-staud",
    category: "Womenswear",
    color: "BLACK SATIN",
    images: [
      "/api/reference-media/live-staud-brigitte-peep-toe-wedge-black-satin-1",
      "/api/reference-media/live-staud-brigitte-peep-toe-wedge-black-satin-2",
      "/api/reference-media/live-staud-brigitte-peep-toe-wedge-black-satin-3",
      "/api/reference-media/live-staud-brigitte-peep-toe-wedge-black-satin-4",
      "/api/reference-media/live-staud-brigitte-peep-toe-wedge-black-satin-5",
      "/api/reference-media/live-staud-brigitte-peep-toe-wedge-black-satin-6",
      "/api/reference-media/live-staud-brigitte-peep-toe-wedge-black-satin-7",
      "/api/reference-media/live-staud-brigitte-peep-toe-wedge-black-satin-8",
    ],
    price: {
      amount: 57500,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "The Brigitte Peep Toe Wedge is a refined wedge with a clean, open-toe finish. It brings effortless height to day or night looks.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf:
        "/api/reference-media/live-staud-brigitte-peep-toe-wedge-black-satin-1",
      grid: "/api/reference-media/live-staud-brigitte-peep-toe-wedge-black-satin-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch:
        "/api/reference-media/live-staud-brigitte-peep-toe-wedge-black-satin-1",
    },
    variants: [
      {
        id: "live-staud-46781052780717",
        label: "35",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781052813485",
        label: "35.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781052846253",
        label: "36",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781052879021",
        label: "36.5",
        availableQuantity: null,
      },
      {
        id: "live-staud-46781052911789",
        label: "37",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781052944557",
        label: "37.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781052977325",
        label: "38",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781053010093",
        label: "38.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781053042861",
        label: "39",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781053075629",
        label: "39.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781053108397",
        label: "40",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781053141165",
        label: "40.5",
        availableQuantity: null,
      },
      {
        id: "live-staud-46781053173933",
        label: "41",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781053206701",
        label: "41.5",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781053239469",
        label: "42",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
  {
    id: "live-staud-felicity-dress-cigar",
    title: "FELICITY DRESS | CIGAR",
    storeId: "live-staud",
    category: "Womenswear",
    color: "CIGAR",
    images: [
      "/api/reference-media/live-staud-felicity-dress-cigar-1",
      "/api/reference-media/live-staud-felicity-dress-cigar-2",
      "/api/reference-media/live-staud-felicity-dress-cigar-3",
      "/api/reference-media/live-staud-felicity-dress-cigar-4",
      "/api/reference-media/live-staud-felicity-dress-cigar-5",
      "/api/reference-media/live-staud-felicity-dress-cigar-6",
    ],
    price: {
      amount: 45500,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      "The Felicity Dress is an asymmetric jersey maxi with a one-shoulder draped neckline. An asymmetric waist drape creates a fluid, body-skimming finish. Easy pull-on styling keeps the look effortless.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceThumbnails: {
      shelf: "/api/reference-media/live-staud-felicity-dress-cigar-1",
      grid: "/api/reference-media/live-staud-felicity-dress-cigar-1",
    },
    detail: {
      completeDescription: true,
      colorSwatch: "/api/reference-media/live-staud-felicity-dress-cigar-1",
    },
    variants: [
      {
        id: "live-staud-46781054451885",
        label: "XS",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781054484653",
        label: "S",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781054517421",
        label: "M",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781054550189",
        label: "L",
        availableQuantity: null,
        referenceSelectable: true,
      },
      {
        id: "live-staud-46781054582957",
        label: "XL",
        availableQuantity: null,
        referenceSelectable: true,
      },
    ],
  },
];
