import type { Product, Store, Money } from "../types";
// Native collection and opened product snapshots are separate; unknown stock stays null.
export const livingRoomStores: readonly Store[] = [
  {
    id: "live-home-store-docos",
    name: "Docos",
    logo: "/api/reference-media/live-home-silque-logo",
    referenceStyle: "android",
    description: "",
    categories: ["Home"],
    rating: 4.1,
    ratingCount: "87",
    referenceWebsite: "https://docos.us",
  },
  {
    id: "live-home-store-rough-linen",
    name: "Rough Linen",
    logo: "/api/reference-media/live-home-barts-logo",
    referenceStyle: "android",
    description: "",
    categories: ["Home"],
    rating: 4.7,
    ratingCount: "6.6K",
    referenceWebsite: "https://www.roughlinen.com",
  },
  {
    id: "live-home-store-pier-1",
    name: "Pier 1",
    logo: "/api/reference-media/live-home-papasan-logo",
    referenceStyle: "android",
    description: "",
    categories: ["Home"],
    rating: 4.3,
    ratingCount: "3.2K",
    referenceWebsite: "https://www.pier1.com",
  },
  {
    id: "live-home-store-graf-lantz",
    name: "Graf Lantz",
    logo: "/api/reference-media/live-home-kobon-logo",
    referenceStyle: "android",
    description: "",
    categories: ["Home"],
    rating: 4.7,
    ratingCount: "22.2K",
    referenceWebsite: "https://graflantz.com",
  },
  {
    id: "live-home-store-bed-threads",
    name: "Bed Threads",
    logo: "/api/reference-media/live-home-olive-logo",
    referenceStyle: "android",
    description: "",
    categories: ["Home"],
    rating: 4.6,
    ratingCount: "10.9K",
    referenceWebsite: "https://bedthreads.com",
  },
  {
    id: "live-home-store-cedar-moss",
    name: "Cedar & Moss",
    logo: "/api/reference-media/live-home-lexi-logo",
    referenceStyle: "android",
    description: "",
    categories: ["Home"],
    rating: 4.9,
    ratingCount: "57",
    referenceWebsite: "https://cedarandmoss.com",
  },
  {
    id: "live-home-store-oakywood",
    name: "Oakywood",
    logo: "/api/reference-media/live-home-tray-logo",
    referenceStyle: "android",
    description: "",
    categories: ["Home"],
    rating: 4.7,
    ratingCount: "1.1K",
    referenceWebsite: "https://oakywood.shop",
  },
  {
    id: "live-home-store-linen-tales",
    name: "Linen Tales",
    logo: "/api/reference-media/live-home-cushion-logo",
    referenceStyle: "android",
    description: "",
    categories: ["Home"],
    rating: 4.9,
    ratingCount: "823",
    referenceWebsite: "https://linentales.com",
  },
  {
    id: "live-home-store-insight-cordless-lighting",
    name: "Insight Cordless Lighting",
    logo: "/api/reference-media/live-home-jupiter-logo",
    referenceStyle: "android",
    description: "",
    categories: ["Home"],
    rating: 4.8,
    ratingCount: "2.5K",
    referenceWebsite: "https://www.insightcordlesslighting.com",
  },
];
export const livingRoomProducts: readonly Product[] = [
  {
    id: "live-home-silque",
    title: "Silque Wall Sconce",
    storeId: "live-home-store-docos",
    category: "Home",
    images: [
      "/api/reference-media/live-home-silque-photo-8",
      "/api/reference-media/live-home-silque-photo-1",
      "/api/reference-media/live-home-silque-photo-2",
      "/api/reference-media/live-home-silque-photo-3",
      "/api/reference-media/live-home-silque-photo-4",
      "/api/reference-media/live-home-silque-photo-5",
      "/api/reference-media/live-home-silque-photo-6",
      "/api/reference-media/live-home-silque-photo-7",
      "/api/reference-media/live-home-silque-photo-9",
      "/api/reference-media/live-home-silque-photo-10",
      "/api/reference-media/live-home-silque-photo-11",
      "/api/reference-media/live-home-silque-photo-12",
      "/api/reference-media/live-home-silque-photo-13",
      "/api/reference-media/live-home-silque-photo-14",
      "/api/reference-media/live-home-silque-photo-15",
      "/api/reference-media/live-home-silque-photo-16",
      "/api/reference-media/live-home-silque-photo-17",
      "/api/reference-media/live-home-silque-photo-18",
      "/api/reference-media/live-home-silque-photo-19",
      "/api/reference-media/live-home-silque-photo-20",
      "/api/reference-media/live-home-silque-photo-21",
      "/api/reference-media/live-home-silque-photo-22",
      "/api/reference-media/live-home-silque-photo-23",
      "/api/reference-media/live-home-silque-photo-24",
      "/api/reference-media/live-home-silque-photo-25",
      "/api/reference-media/live-home-silque-photo-26",
      "/api/reference-media/live-home-silque-photo-27",
      "/api/reference-media/live-home-silque-photo-28",
      "/api/reference-media/live-home-silque-photo-29",
    ],
    referenceThumbnails: {
      shelf: "/api/reference-media/live-home-silque-photo-8",
      grid: "/api/reference-media/live-home-silque-photo-8",
    },
    price: {
      amount: 23500,
      currency: "USD",
    },
    ratingCount: "",
    description:
      'Overview\n\nThe Silque Wall Sconce is a poetic architectural accent designed for effortless, plug-and-play installation. Featuring a large-scale screen of premium imported Washi paper, this sculptural light mimics a glowing window, softening the output of its integrated four-bulb E26/E27 array. Measuring 60cm wide and 70cm tall, Silque provides an expansive ambient glow that transforms bare walls into serene art pieces. With its visible plug-in cord and in-line switch, it offers a contemporary Wabi-sabi aesthetic that requires no internal wall wiring—perfect for renters or versatile bedroom setups.\n\nKey Features\n\nArtisanal Washi Paper\n\nHand-selected imported Washi paper provides a natural, fibrous texture that diffuses light with a soft, ethereal quality.\n\nEasy Plug-in Setup\n\nComes with a high-quality power cord and integrated switch, allowing for instant wall-mounted lighting without electrical work.\n\nExpansive Soft Light\n\nFour symmetrical light points create a large, even glow behind the paper, acting as a secondary ambient "window" in any room.\n\nProduct Size\n\nTotal Width23.6″ / 60 cm\n\nTotal Height27.6″ / 70 cm\n\nInstallation TypePlug-in Wall Mount (Corded)\n\nConnectivityIntegrated Cord with In-line Switch\n\nSpecifications\n\nMain Materials\n\nReinforced Metal Alloy, Imported Artisanal Washi Paper\n\nFinish Color\n\nMatte Cream Paper with Architectural Black framework\n\nSockets\n\n4 × E26 / E27 Universal Medium Base\n\nPower Source\n\nStandard Plug-in Power Cord\n\nMounting\n\nFlush wall-bracket system included\n\nDesign Style\n\nJapandiWabi-SabiModern Zen\n\nWhere It Works\n\nThe Silque Wall Sconce is the ultimate solution for renters or homeowners who want high-impact ambient lighting without the permanence of hardwiring. Its 60cm width makes it an exceptional bedside light, hanging just above a nightstand to provide a soothing reading glow. In living rooms or reading corners, the visible black cord adds a modern industrial touch to the soft, artisanal paper screen, grounding the Japandi or Wabi-sabi aesthetic.\n\nBecause it uses standard E26/E27 sockets, you can customize the glow with Warm White LED bulbs for a healing atmosphere or smart bulbs for color-temperature control. Pair it with textured plaster walls or wooden accents to let the natural fibers of the Washi paper truly shine as a functional piece of luminous art.\n\nFAQ\n\nDo I need an electrician to install this?\nNo. Silque is a plug-in wall sconce. You simply mount the slim frame to your wall using the included brackets and plug it into a standard wall outlet. No internal wiring is required.\n\nWhere is the switch located?\nThe sconce features a convenient in-line switch located on the power cord, allowing you to easily turn the light on and off without reaching behind the paper screen.\n\nWhat kind of bulb base does it use?\nIt is equipped with four standard E26 / E27 sockets. We recommend using 4W-10W LED bulbs (Warm White) to maintain a soft ambient effect while keeping energy consumption low.\n\nHow do I clean the Washi paper?\nWe recommend using a soft, dry brush or a feather duster periodically. Since Washi is an artisanal paper, avoid using water or chemical cleaners to preserve its natural texture.\n\nDownloads\n\nInstallation materials and spec sheets for the Silque series.\n\nSpec Sheet\n\nPaper & Cord Specs · PDF\n\nInstall Guide\n\nPlug-in Mounting · PDF\n\n3D Files\n\nZen Interior Renders · ZIP\n\nPending',
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceDefaultVariantId: "live-home-silque-52270576697618",
    detail: {
      completeDescription: true,
      colorGallery: [
        "/api/reference-media/live-home-silque-photo-1",
        "/api/reference-media/live-home-silque-photo-2",
        "/api/reference-media/live-home-silque-photo-3",
        "/api/reference-media/live-home-silque-photo-4",
        "/api/reference-media/live-home-silque-photo-5",
        "/api/reference-media/live-home-silque-photo-6",
        "/api/reference-media/live-home-silque-photo-7",
        "/api/reference-media/live-home-silque-photo-8",
        "/api/reference-media/live-home-silque-photo-9",
        "/api/reference-media/live-home-silque-photo-10",
        "/api/reference-media/live-home-silque-photo-11",
        "/api/reference-media/live-home-silque-photo-12",
        "/api/reference-media/live-home-silque-photo-13",
        "/api/reference-media/live-home-silque-photo-14",
        "/api/reference-media/live-home-silque-photo-15",
        "/api/reference-media/live-home-silque-photo-16",
        "/api/reference-media/live-home-silque-photo-17",
        "/api/reference-media/live-home-silque-photo-18",
        "/api/reference-media/live-home-silque-photo-19",
        "/api/reference-media/live-home-silque-photo-20",
        "/api/reference-media/live-home-silque-photo-21",
        "/api/reference-media/live-home-silque-photo-22",
        "/api/reference-media/live-home-silque-photo-23",
        "/api/reference-media/live-home-silque-photo-24",
        "/api/reference-media/live-home-silque-photo-25",
        "/api/reference-media/live-home-silque-photo-26",
        "/api/reference-media/live-home-silque-photo-27",
        "/api/reference-media/live-home-silque-photo-28",
        "/api/reference-media/live-home-silque-photo-29",
      ],
      optionGroups: [
        {
          name: "Size",
          colors: false,
          showSelection: false,
          limit: 1,
        },
        {
          name: "Colour",
          colors: true,
          showSelection: true,
        },
        {
          name: "Plug Options",
          colors: false,
          showSelection: false,
        },
      ],
    },
    variants: [
      {
        id: "live-home-silque-52270576697618",
        label: "W 60cm x H 70cm / W 23.6″ x H 27.6″ / Black & Beige / US Plug",
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          Size: "W 60cm x H 70cm / W 23.6″ x H 27.6″",
          Colour: "Black & Beige",
          "Plug Options": "US Plug",
        },
        referencePrice: {
          amount: 23500,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-silque-photo-8",
        referenceColor: {
          photo: "/api/reference-media/live-home-silque-photo-8",
          swatch:
            'url("/api/reference-media/live-home-silque-photo-8") center / contain no-repeat',
        },
      },
      {
        id: "live-home-silque-52270576926994",
        label: "W 60cm x H 70cm / W 23.6″ x H 27.6″ / Black & Beige / UK Plug",
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          Size: "W 60cm x H 70cm / W 23.6″ x H 27.6″",
          Colour: "Black & Beige",
          "Plug Options": "UK Plug",
        },
        referencePrice: {
          amount: 23500,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-silque-photo-8",
        referenceColor: {
          photo: "/api/reference-media/live-home-silque-photo-8",
          swatch:
            'url("/api/reference-media/live-home-silque-photo-8") center / contain no-repeat',
        },
      },
      {
        id: "live-home-silque-52270576959762",
        label: "W 60cm x H 70cm / W 23.6″ x H 27.6″ / Black & Beige / AU Plug",
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          Size: "W 60cm x H 70cm / W 23.6″ x H 27.6″",
          Colour: "Black & Beige",
          "Plug Options": "AU Plug",
        },
        referencePrice: {
          amount: 23500,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-silque-photo-8",
        referenceColor: {
          photo: "/api/reference-media/live-home-silque-photo-8",
          swatch:
            'url("/api/reference-media/live-home-silque-photo-8") center / contain no-repeat',
        },
      },
      {
        id: "live-home-silque-52270576992530",
        label: "W 60cm x H 70cm / W 23.6″ x H 27.6″ / Black & Beige / EU Plug",
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          Size: "W 60cm x H 70cm / W 23.6″ x H 27.6″",
          Colour: "Black & Beige",
          "Plug Options": "EU Plug",
        },
        referencePrice: {
          amount: 23500,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-silque-photo-8",
        referenceColor: {
          photo: "/api/reference-media/live-home-silque-photo-8",
          swatch:
            'url("/api/reference-media/live-home-silque-photo-8") center / contain no-repeat',
        },
      },
    ],
  },
  {
    id: "live-home-barts",
    title: "St. Barts Linen Throw Blanket",
    storeId: "live-home-store-rough-linen",
    category: "Home",
    images: [
      "/api/reference-media/live-home-barts-photo-2",
      "/api/reference-media/live-home-barts-photo-1",
      "/api/reference-media/live-home-barts-photo-3",
      "/api/reference-media/live-home-barts-photo-4",
      "/api/reference-media/live-home-barts-photo-5",
      "/api/reference-media/live-home-barts-photo-6",
      "/api/reference-media/live-home-barts-photo-7",
      "/api/reference-media/live-home-barts-photo-8",
      "/api/reference-media/live-home-barts-photo-9",
    ],
    referenceThumbnails: {
      shelf: "/api/reference-media/live-home-barts-photo-1",
      grid: "/api/reference-media/live-home-barts-photo-1",
    },
    price: {
      amount: 13685,
      currency: "USD",
    },
    rating: 3.7,
    ratingCount: "3",
    description:
      'Snuggle into color and comfort with our new Linen Throw Blankets in our midweight St. Barts linen.  These tactile throws will grace/style your bed or sofa to keep you cosy and add a splash of color.\n\nEasy care means you can keep these throws fresh, just wash and they will come up smiling.\n\nProduct Information\n\nSize:  54" x 80"\n\nCare: Machine wash with a small amount of gentle detergent, not Tide. Tumble dry on hot or medium, and remove from the dryer while still very slightly damp so wrinkles do not set. Shake the fabric out flat and smooth it with your hands. If you can dry outside, let fresh air and sun work their magic.\n\nMaterial: Woven from 100% European Flax.  St. Barts 7.7 oz/sq. yd',
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 1,
    referenceDefaultVariantId: "live-home-barts-41055783452769",
    detail: {
      completeDescription: true,
      colorGallery: [
        "/api/reference-media/live-home-barts-photo-1",
        "/api/reference-media/live-home-barts-photo-2",
        "/api/reference-media/live-home-barts-photo-3",
        "/api/reference-media/live-home-barts-photo-4",
        "/api/reference-media/live-home-barts-photo-5",
        "/api/reference-media/live-home-barts-photo-6",
        "/api/reference-media/live-home-barts-photo-7",
        "/api/reference-media/live-home-barts-photo-8",
        "/api/reference-media/live-home-barts-photo-9",
      ],
      optionGroups: [
        {
          name: "Color",
          colors: true,
          showSelection: true,
        },
      ],
    },
    variants: [
      {
        id: "live-home-barts-41055783321697",
        label: "ink",
        availableQuantity: null,
        referenceUnavailable: true,
        referenceOptions: {
          Color: "ink",
        },
        referencePrice: {
          amount: 13685,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-barts-photo-7",
        referenceColor: {
          photo: "/api/reference-media/live-home-barts-photo-7",
          swatch:
            'url("/api/reference-media/live-home-barts-photo-7") center / contain no-repeat',
          unavailable: true,
        },
      },
      {
        id: "live-home-barts-41055783387233",
        label: "sedona",
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          Color: "sedona",
        },
        referencePrice: {
          amount: 13260,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-barts-photo-4",
        referenceColor: {
          photo: "/api/reference-media/live-home-barts-photo-4",
          swatch:
            'url("/api/reference-media/live-home-barts-photo-4") center / contain no-repeat',
        },
      },
      {
        id: "live-home-barts-41055783420001",
        label: "storm",
        availableQuantity: null,
        referenceUnavailable: true,
        referenceOptions: {
          Color: "storm",
        },
        referencePrice: {
          amount: 13685,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-barts-photo-9",
        referenceColor: {
          photo: "/api/reference-media/live-home-barts-photo-9",
          swatch:
            'url("/api/reference-media/live-home-barts-photo-9") center / contain no-repeat',
          unavailable: true,
        },
      },
      {
        id: "live-home-barts-41055783452769",
        label: "moss",
        availableQuantity: null,
        referenceUnavailable: true,
        referenceOptions: {
          Color: "moss",
        },
        referencePrice: {
          amount: 13685,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-barts-photo-2",
        referenceColor: {
          photo: "/api/reference-media/live-home-barts-photo-2",
          swatch:
            'url("/api/reference-media/live-home-barts-photo-2") center / contain no-repeat',
          unavailable: true,
        },
      },
      {
        id: "live-home-barts-41055284461665",
        label: "aqua",
        availableQuantity: null,
        referenceUnavailable: true,
        referenceOptions: {
          Color: "aqua",
        },
        referencePrice: {
          amount: 13685,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-barts-photo-8",
        referenceColor: {
          photo: "/api/reference-media/live-home-barts-photo-8",
          swatch:
            'url("/api/reference-media/live-home-barts-photo-8") center / contain no-repeat',
          unavailable: true,
        },
      },
      {
        id: "live-home-barts-41055783354465",
        label: "fig",
        availableQuantity: null,
        referenceUnavailable: true,
        referenceOptions: {
          Color: "fig",
        },
        referencePrice: {
          amount: 13685,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-barts-photo-6",
        referenceColor: {
          photo: "/api/reference-media/live-home-barts-photo-6",
          swatch:
            'url("/api/reference-media/live-home-barts-photo-6") center / contain no-repeat',
          unavailable: true,
        },
      },
    ],
  },
  {
    id: "live-home-papasan",
    title:
      "The Original Papasan™ 360° Swivel Indoor Outdoor Wicker Papasan Chair with Soft Thick Cushion",
    storeId: "live-home-store-pier-1",
    category: "Home",
    images: [
      "/api/reference-media/live-home-papasan-photo-24",
      "/api/reference-media/live-home-papasan-photo-1",
      "/api/reference-media/live-home-papasan-photo-2",
      "/api/reference-media/live-home-papasan-photo-3",
      "/api/reference-media/live-home-papasan-photo-4",
      "/api/reference-media/live-home-papasan-photo-5",
      "/api/reference-media/live-home-papasan-photo-6",
      "/api/reference-media/live-home-papasan-photo-7",
      "/api/reference-media/live-home-papasan-photo-8",
      "/api/reference-media/live-home-papasan-photo-9",
      "/api/reference-media/live-home-papasan-photo-10",
      "/api/reference-media/live-home-papasan-photo-11",
      "/api/reference-media/live-home-papasan-photo-12",
      "/api/reference-media/live-home-papasan-photo-13",
      "/api/reference-media/live-home-papasan-photo-14",
      "/api/reference-media/live-home-papasan-photo-15",
      "/api/reference-media/live-home-papasan-photo-16",
      "/api/reference-media/live-home-papasan-photo-17",
      "/api/reference-media/live-home-papasan-photo-18",
      "/api/reference-media/live-home-papasan-photo-19",
      "/api/reference-media/live-home-papasan-photo-20",
      "/api/reference-media/live-home-papasan-photo-21",
      "/api/reference-media/live-home-papasan-photo-22",
      "/api/reference-media/live-home-papasan-photo-23",
      "/api/reference-media/live-home-papasan-photo-25",
      "/api/reference-media/live-home-papasan-photo-26",
      "/api/reference-media/live-home-papasan-photo-27",
      "/api/reference-media/live-home-papasan-photo-28",
      "/api/reference-media/live-home-papasan-photo-29",
      "/api/reference-media/live-home-papasan-photo-30",
      "/api/reference-media/live-home-papasan-photo-31",
      "/api/reference-media/live-home-papasan-photo-32",
      "/api/reference-media/live-home-papasan-photo-33",
      "/api/reference-media/live-home-papasan-photo-34",
      "/api/reference-media/live-home-papasan-photo-35",
      "/api/reference-media/live-home-papasan-photo-36",
      "/api/reference-media/live-home-papasan-photo-37",
      "/api/reference-media/live-home-papasan-photo-38",
      "/api/reference-media/live-home-papasan-photo-39",
      "/api/reference-media/live-home-papasan-photo-40",
      "/api/reference-media/live-home-papasan-photo-41",
      "/api/reference-media/live-home-papasan-photo-42",
      "/api/reference-media/live-home-papasan-photo-43",
      "/api/reference-media/live-home-papasan-photo-44",
      "/api/reference-media/live-home-papasan-photo-45",
      "/api/reference-media/live-home-papasan-photo-46",
      "/api/reference-media/live-home-papasan-photo-47",
      "/api/reference-media/live-home-papasan-photo-48",
      "/api/reference-media/live-home-papasan-photo-49",
      "/api/reference-media/live-home-papasan-photo-50",
      "/api/reference-media/live-home-papasan-photo-51",
      "/api/reference-media/live-home-papasan-photo-52",
      "/api/reference-media/live-home-papasan-photo-53",
      "/api/reference-media/live-home-papasan-photo-54",
      "/api/reference-media/live-home-papasan-photo-55",
      "/api/reference-media/live-home-papasan-photo-56",
      "/api/reference-media/live-home-papasan-photo-57",
      "/api/reference-media/live-home-papasan-photo-58",
      "/api/reference-media/live-home-papasan-photo-59",
      "/api/reference-media/live-home-papasan-photo-60",
      "/api/reference-media/live-home-papasan-photo-61",
      "/api/reference-media/live-home-papasan-photo-62",
      "/api/reference-media/live-home-papasan-photo-63",
      "/api/reference-media/live-home-papasan-photo-64",
      "/api/reference-media/live-home-papasan-photo-65",
      "/api/reference-media/live-home-papasan-photo-66",
      "/api/reference-media/live-home-papasan-photo-67",
      "/api/reference-media/live-home-papasan-photo-68",
      "/api/reference-media/live-home-papasan-photo-69",
      "/api/reference-media/live-home-papasan-photo-70",
      "/api/reference-media/live-home-papasan-photo-71",
      "/api/reference-media/live-home-papasan-photo-72",
      "/api/reference-media/live-home-papasan-photo-73",
      "/api/reference-media/live-home-papasan-photo-74",
      "/api/reference-media/live-home-papasan-photo-75",
      "/api/reference-media/live-home-papasan-photo-76",
      "/api/reference-media/live-home-papasan-photo-77",
      "/api/reference-media/live-home-papasan-photo-78",
      "/api/reference-media/live-home-papasan-photo-79",
      "/api/reference-media/live-home-papasan-photo-80",
      "/api/reference-media/live-home-papasan-photo-81",
      "/api/reference-media/live-home-papasan-photo-82",
      "/api/reference-media/live-home-papasan-photo-83",
      "/api/reference-media/live-home-papasan-photo-84",
      "/api/reference-media/live-home-papasan-photo-85",
      "/api/reference-media/live-home-papasan-photo-86",
      "/api/reference-media/live-home-papasan-photo-87",
      "/api/reference-media/live-home-papasan-photo-88",
      "/api/reference-media/live-home-papasan-photo-89",
      "/api/reference-media/live-home-papasan-photo-90",
      "/api/reference-media/live-home-papasan-photo-91",
      "/api/reference-media/live-home-papasan-photo-92",
      "/api/reference-media/live-home-papasan-photo-93",
      "/api/reference-media/live-home-papasan-photo-94",
      "/api/reference-media/live-home-papasan-photo-95",
    ],
    referenceThumbnails: {
      shelf: "/api/reference-media/live-home-papasan-photo-1",
      grid: "/api/reference-media/live-home-papasan-photo-1",
    },
    price: {
      amount: 20054,
      currency: "EUR",
    },
    ratingCount: "",
    description:
      'Sink into a world of effortless relaxation with this generously cushioned papasan chair, where a whisper-quiet 360° swivel base and an overstuffed, cloud-soft cushion make every sit feel like a retreat. The sculptural round silhouette and woven PE rattan weave bring a globally inspired, casual-luxe aesthetic that layers beautifully into living rooms, bedrooms, and covered outdoor spaces alike. Available in multiple color combinations, this is the kind of statement piece that makes everyone want to claim it as their own.\n\nFeatures\n\nExclusive "Easy Swivel" design delivers virtually frictionless, whisper-quiet 360° rotation\n\nOverstuffed cushion filled with virgin polyester for a plush, enveloping sit\n\nErgonomic circular silhouette supports proper alignment during extended lounging or reading\n\nPowder-coated steel frame with woven PE rattan for lasting durability indoors and out\n\nArmless design and round back create an open, cocoon-like feel\n\nSuitable for bedrooms, living rooms, and covered outdoor use\n\nSupports up to 300 lbs\n\nAvailable in multiple frame and cushion color combinations\n\nCushion included\n\nSpecifications\n\nDimensions: 36.22 in Dia. x 26.38 in H\n\nFrame Material: Powder-coated steel with PE rattan\n\nCushion Fill: Virgin polyester (200g staple fiber)\n\nBack Style: Round\n\nArm Style: Armless\n\nBase Movement: 360° swivel\n\nWeight Capacity: 300 lbs\n\nRecommended Use: Bedroom, living room, covered outdoor spaces\n\nAge Range: Adult\n\nIncluded: Cushion, installation manual\n\nAssembly & Installation\n\nMinimal assembly required; installation manual included\n\nNo additional tools specified',
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 1,
    referenceDefaultVariantId: "live-home-papasan-48187968815271",
    detail: {
      completeDescription: true,
      colorGallery: [
        "/api/reference-media/live-home-papasan-photo-1",
        "/api/reference-media/live-home-papasan-photo-2",
        "/api/reference-media/live-home-papasan-photo-3",
        "/api/reference-media/live-home-papasan-photo-4",
        "/api/reference-media/live-home-papasan-photo-5",
        "/api/reference-media/live-home-papasan-photo-6",
        "/api/reference-media/live-home-papasan-photo-7",
        "/api/reference-media/live-home-papasan-photo-8",
        "/api/reference-media/live-home-papasan-photo-9",
        "/api/reference-media/live-home-papasan-photo-10",
        "/api/reference-media/live-home-papasan-photo-11",
        "/api/reference-media/live-home-papasan-photo-12",
        "/api/reference-media/live-home-papasan-photo-13",
        "/api/reference-media/live-home-papasan-photo-14",
        "/api/reference-media/live-home-papasan-photo-15",
        "/api/reference-media/live-home-papasan-photo-16",
        "/api/reference-media/live-home-papasan-photo-17",
        "/api/reference-media/live-home-papasan-photo-18",
        "/api/reference-media/live-home-papasan-photo-19",
        "/api/reference-media/live-home-papasan-photo-20",
        "/api/reference-media/live-home-papasan-photo-21",
        "/api/reference-media/live-home-papasan-photo-22",
        "/api/reference-media/live-home-papasan-photo-23",
        "/api/reference-media/live-home-papasan-photo-24",
        "/api/reference-media/live-home-papasan-photo-25",
        "/api/reference-media/live-home-papasan-photo-26",
        "/api/reference-media/live-home-papasan-photo-27",
        "/api/reference-media/live-home-papasan-photo-28",
        "/api/reference-media/live-home-papasan-photo-29",
        "/api/reference-media/live-home-papasan-photo-30",
        "/api/reference-media/live-home-papasan-photo-31",
        "/api/reference-media/live-home-papasan-photo-32",
        "/api/reference-media/live-home-papasan-photo-33",
        "/api/reference-media/live-home-papasan-photo-34",
        "/api/reference-media/live-home-papasan-photo-35",
        "/api/reference-media/live-home-papasan-photo-36",
        "/api/reference-media/live-home-papasan-photo-37",
        "/api/reference-media/live-home-papasan-photo-38",
        "/api/reference-media/live-home-papasan-photo-39",
        "/api/reference-media/live-home-papasan-photo-40",
        "/api/reference-media/live-home-papasan-photo-41",
        "/api/reference-media/live-home-papasan-photo-42",
        "/api/reference-media/live-home-papasan-photo-43",
        "/api/reference-media/live-home-papasan-photo-44",
        "/api/reference-media/live-home-papasan-photo-45",
        "/api/reference-media/live-home-papasan-photo-46",
        "/api/reference-media/live-home-papasan-photo-47",
        "/api/reference-media/live-home-papasan-photo-48",
        "/api/reference-media/live-home-papasan-photo-49",
        "/api/reference-media/live-home-papasan-photo-50",
        "/api/reference-media/live-home-papasan-photo-51",
        "/api/reference-media/live-home-papasan-photo-52",
        "/api/reference-media/live-home-papasan-photo-53",
        "/api/reference-media/live-home-papasan-photo-54",
        "/api/reference-media/live-home-papasan-photo-55",
        "/api/reference-media/live-home-papasan-photo-56",
        "/api/reference-media/live-home-papasan-photo-57",
        "/api/reference-media/live-home-papasan-photo-58",
        "/api/reference-media/live-home-papasan-photo-59",
        "/api/reference-media/live-home-papasan-photo-60",
        "/api/reference-media/live-home-papasan-photo-61",
        "/api/reference-media/live-home-papasan-photo-62",
        "/api/reference-media/live-home-papasan-photo-63",
        "/api/reference-media/live-home-papasan-photo-64",
        "/api/reference-media/live-home-papasan-photo-65",
        "/api/reference-media/live-home-papasan-photo-66",
        "/api/reference-media/live-home-papasan-photo-67",
        "/api/reference-media/live-home-papasan-photo-68",
        "/api/reference-media/live-home-papasan-photo-69",
        "/api/reference-media/live-home-papasan-photo-70",
        "/api/reference-media/live-home-papasan-photo-71",
        "/api/reference-media/live-home-papasan-photo-72",
        "/api/reference-media/live-home-papasan-photo-73",
        "/api/reference-media/live-home-papasan-photo-74",
        "/api/reference-media/live-home-papasan-photo-75",
        "/api/reference-media/live-home-papasan-photo-76",
        "/api/reference-media/live-home-papasan-photo-77",
        "/api/reference-media/live-home-papasan-photo-78",
        "/api/reference-media/live-home-papasan-photo-79",
        "/api/reference-media/live-home-papasan-photo-80",
        "/api/reference-media/live-home-papasan-photo-81",
        "/api/reference-media/live-home-papasan-photo-82",
        "/api/reference-media/live-home-papasan-photo-83",
        "/api/reference-media/live-home-papasan-photo-84",
        "/api/reference-media/live-home-papasan-photo-85",
        "/api/reference-media/live-home-papasan-photo-86",
        "/api/reference-media/live-home-papasan-photo-87",
        "/api/reference-media/live-home-papasan-photo-88",
        "/api/reference-media/live-home-papasan-photo-89",
        "/api/reference-media/live-home-papasan-photo-90",
        "/api/reference-media/live-home-papasan-photo-91",
        "/api/reference-media/live-home-papasan-photo-92",
        "/api/reference-media/live-home-papasan-photo-93",
        "/api/reference-media/live-home-papasan-photo-94",
        "/api/reference-media/live-home-papasan-photo-95",
      ],
      optionGroups: [
        {
          name: "Color",
          colors: true,
          showSelection: true,
        },
      ],
    },
    variants: [
      {
        id: "live-home-papasan-48187968815271",
        label: "Beige",
        availableQuantity: null,
        referenceUnavailable: true,
        referenceOptions: {
          Color: "Beige",
        },
        referencePrice: {
          amount: 20054,
          currency: "EUR",
        },
        referenceImage: "/api/reference-media/live-home-papasan-photo-24",
        referenceColor: {
          photo: "/api/reference-media/live-home-papasan-photo-24",
          swatch:
            'url("/api/reference-media/live-home-papasan-photo-24") center / contain no-repeat',
          unavailable: true,
        },
      },
      {
        id: "live-home-papasan-48232799043751",
        label: "Gray",
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          Color: "Gray",
        },
        referencePrice: {
          amount: 20054,
          currency: "EUR",
        },
        referenceImage: "/api/reference-media/live-home-papasan-photo-26",
        referenceColor: {
          photo: "/api/reference-media/live-home-papasan-photo-26",
          swatch:
            'url("/api/reference-media/live-home-papasan-photo-26") center / contain no-repeat',
        },
      },
      {
        id: "live-home-papasan-48232799076519",
        label: "Gray Corduroy",
        availableQuantity: null,
        referenceUnavailable: true,
        referenceOptions: {
          Color: "Gray Corduroy",
        },
        referencePrice: {
          amount: 20054,
          currency: "EUR",
        },
        referenceImage: "/api/reference-media/live-home-papasan-photo-40",
        referenceColor: {
          photo: "/api/reference-media/live-home-papasan-photo-40",
          swatch:
            'url("/api/reference-media/live-home-papasan-photo-40") center / contain no-repeat',
          unavailable: true,
        },
      },
      {
        id: "live-home-papasan-48232799109287",
        label: "Navy Corduroy",
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          Color: "Navy Corduroy",
        },
        referencePrice: {
          amount: 20054,
          currency: "EUR",
        },
        referenceImage: "/api/reference-media/live-home-papasan-photo-53",
        referenceColor: {
          photo: "/api/reference-media/live-home-papasan-photo-53",
          swatch:
            'url("/api/reference-media/live-home-papasan-photo-53") center / contain no-repeat',
        },
      },
      {
        id: "live-home-papasan-48232799142055",
        label: "White Corduroy",
        availableQuantity: null,
        referenceUnavailable: true,
        referenceOptions: {
          Color: "White Corduroy",
        },
        referencePrice: {
          amount: 20054,
          currency: "EUR",
        },
        referenceImage: "/api/reference-media/live-home-papasan-photo-60",
        referenceColor: {
          photo: "/api/reference-media/live-home-papasan-photo-60",
          swatch:
            'url("/api/reference-media/live-home-papasan-photo-60") center / contain no-repeat',
          unavailable: true,
        },
      },
      {
        id: "live-home-papasan-48232799174823",
        label: "Sage Corduroy",
        availableQuantity: null,
        referenceUnavailable: true,
        referenceOptions: {
          Color: "Sage Corduroy",
        },
        referencePrice: {
          amount: 20054,
          currency: "EUR",
        },
        referenceImage: "/api/reference-media/live-home-papasan-photo-73",
        referenceColor: {
          photo: "/api/reference-media/live-home-papasan-photo-73",
          swatch:
            'url("/api/reference-media/live-home-papasan-photo-73") center / contain no-repeat',
          unavailable: true,
        },
      },
      {
        id: "live-home-papasan-48232799207591",
        label: "Pink Corduroy",
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          Color: "Pink Corduroy",
        },
        referencePrice: {
          amount: 20054,
          currency: "EUR",
        },
        referenceImage: "/api/reference-media/live-home-papasan-photo-86",
        referenceColor: {
          photo: "/api/reference-media/live-home-papasan-photo-86",
          swatch:
            'url("/api/reference-media/live-home-papasan-photo-86") center / contain no-repeat',
        },
      },
    ],
  },
  {
    id: "live-home-kobon",
    title: "Kobon Leather/Merino Wool Round Tray 6 Pack Coaster Set",
    storeId: "live-home-store-graf-lantz",
    category: "Home",
    images: [
      "/api/reference-media/live-home-kobon-ocean-photo-1",
      "/api/reference-media/live-home-kobon-ocean-photo-2",
      "/api/reference-media/live-home-kobon-ocean-photo-3",
      "/api/reference-media/live-home-kobon-ocean-photo-4",
      "/api/reference-media/live-home-kobon-ocean-photo-5",
    ],
    referenceThumbnails: {
      shelf: "/api/reference-media/live-home-kobon-ocean-photo-1",
      grid: "/api/reference-media/live-home-kobon-ocean-photo-1",
    },
    price: {
      amount: 10200,
      currency: "USD",
    },
    rating: 5,
    ratingCount: "7",
    description:
      "This thoughtfully curated set includes six Merino wool Bierfilzl coasters, each paired with a finely crafted Kobon leather tray. Perfect for gifting or elevating your own space, this bundle combines sustainable materials with functional elegance. Handcrafted in Los Angeles, it offers a seamless blend of beauty and durability. Each coaster features a subtle logo on the underside, a mark of our commitment to quality. Proudly display this functional yet stylish addition to your home or office. *Includes 6 coasters in Cobalt, Heather Blue, Horizon, Marine, Teal, Turquoise\n\n \n\nBenefits of Merino Wool\n\nSustainable, biodegradable, and renewable\n\nOdor, stain, heat, and dirt-resistant\n\nOeko-Tex® Certified\n\nSee all the benefits of our felt\n\nHow to clean and care for your fabric",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceDefaultVariantId: "live-home-kobon-40375062134893",
    detail: {
      completeDescription: true,
      colorGallery: [
        "/api/reference-media/live-home-kobon-ocean-photo-1",
        "/api/reference-media/live-home-kobon-ocean-photo-2",
        "/api/reference-media/live-home-kobon-ocean-photo-3",
        "/api/reference-media/live-home-kobon-ocean-photo-4",
        "/api/reference-media/live-home-kobon-ocean-photo-5",
      ],
      optionGroups: [
        {
          name: "Color",
          colors: true,
          showSelection: true,
        },
      ],
    },
    variants: [
      {
        id: "live-home-kobon-40375062134893",
        label: "Ocean",
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          Color: "Ocean",
        },
        referencePrice: {
          amount: 10200,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-kobon-ocean-photo-1",
        referenceColor: {
          photo: "/api/reference-media/live-home-kobon-ocean-photo-1",
          swatch:
            'url("/api/reference-media/live-home-kobon-ocean-photo-1") center / contain no-repeat',
        },
      },
    ],
  },
  {
    id: "live-home-olive",
    title: "Olive 100% French Flax Linen Throw",
    storeId: "live-home-store-bed-threads",
    category: "Home",
    images: ["/api/reference-media/live-home-olive-native-1"],
    referenceThumbnails: {
      shelf: "/api/reference-media/live-home-olive-native-1",
      grid: "/api/reference-media/live-home-olive-native-1",
    },
    price: {
      amount: 24000,
      currency: "USD",
    },
    rating: 4.8,
    ratingCount: "19",
    description:
      "Our heavy-weight, pre-washed 100% French flax linen throw in Olive is the all-purpose essential for your home. Super soft, warm, and durable, these thick-textured throws make an ideal duvet substitute, picnic throw or cosy extra layer on your bed or couch.\n\nThe thing about linen is it only gets better over time; the more you use and wash it, the softer and more comfortable it gets. What’s more, linen is good for you too: it’s anti-static, anti-bacterial and naturally temperature-regulating.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceDefaultVariantId: "live-home-olive-32581152473173",
    referenceImageTreatment: "native",
    detail: {
      completeDescription: true,
      colorGallery: ["/api/reference-media/live-home-olive-native-1"],
      optionGroups: [
        {
          name: "Colour",
          colors: true,
          showSelection: true,
        },
        {
          name: "Size",
          colors: false,
          showSelection: false,
        },
      ],
      descriptionInitiallyCollapsed: true,
      referenceBadge: "Only 1 left",
      referenceBadgeTone: "stock",
      referenceBadgeVariantId: "live-home-olive-32581152473173",
      highlights: [
        "Heavyweight pre-washed French flax linen construction provides superior softness and warmth",
        "Naturally temperature regulating for year-round comfort",
        "Anti-static and antibacterial properties for a healthier home environment",
        "Durable and thick textured design ideal for multiple uses",
        "Improves comfort with every wash, getting softer over time",
      ],
      reviewPreview: {
        distribution: [89, 5, 5, 0, 0],
        reviews: [
          {
            title: "Nice product",
            rating: 5,
            author: "Scott",
            date: "Jan 7, 2026",
          },
          {
            title: "throw blanket",
            rating: 5,
            author: "Mackenzie",
            date: "Dec 22, 2025",
          },
        ],
      },
    },
    variants: [
      {
        id: "live-home-olive-32581152473173",
        label: "Olive / Medium",
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          Colour: "Olive",
          Size: "Medium",
        },
        referencePrice: {
          amount: 24000,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-olive-native-1",
        referenceColor: {
          photo: "/api/reference-media/live-home-olive-native-1",
          swatch:
            'url("/api/reference-media/live-home-olive-native-1") center / contain no-repeat',
        },
      },
      {
        id: "live-home-olive-32581152505941",
        label: "Olive / Large",
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          Colour: "Olive",
          Size: "Large",
        },
        referencePrice: {
          amount: 26000,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-olive-native-1",
        referenceColor: {
          photo: "/api/reference-media/live-home-olive-native-1",
          swatch:
            'url("/api/reference-media/live-home-olive-native-1") center / contain no-repeat',
        },
      },
    ],
  },
  {
    id: "live-home-lexi",
    title: 'Lexi Small 5"',
    storeId: "live-home-store-cedar-moss",
    category: "Home",
    images: [
      "/api/reference-media/live-home-lexi-photo-8",
      "/api/reference-media/live-home-lexi-photo-1",
      "/api/reference-media/live-home-lexi-photo-2",
      "/api/reference-media/live-home-lexi-photo-3",
      "/api/reference-media/live-home-lexi-photo-4",
      "/api/reference-media/live-home-lexi-photo-5",
      "/api/reference-media/live-home-lexi-photo-6",
      "/api/reference-media/live-home-lexi-photo-7",
      "/api/reference-media/live-home-lexi-photo-9",
      "/api/reference-media/live-home-lexi-photo-10",
      "/api/reference-media/live-home-lexi-photo-11",
      "/api/reference-media/live-home-lexi-photo-12",
      "/api/reference-media/live-home-lexi-photo-13",
      "/api/reference-media/live-home-lexi-photo-14",
      "/api/reference-media/live-home-lexi-photo-15",
      "/api/reference-media/live-home-lexi-photo-16",
      "/api/reference-media/live-home-lexi-photo-17",
      "/api/reference-media/live-home-lexi-photo-18",
      "/api/reference-media/live-home-lexi-photo-19",
      "/api/reference-media/live-home-lexi-photo-20",
      "/api/reference-media/live-home-lexi-photo-21",
      "/api/reference-media/live-home-lexi-photo-22",
      "/api/reference-media/live-home-lexi-photo-23",
      "/api/reference-media/live-home-lexi-photo-24",
      "/api/reference-media/live-home-lexi-photo-25",
    ],
    referenceThumbnails: {
      shelf: "/api/reference-media/live-home-lexi-photo-8",
      grid: "/api/reference-media/live-home-lexi-photo-8",
    },
    price: {
      amount: 42900,
      currency: "USD",
    },
    ratingCount: "",
    description:
      "An updated version of our original 2013 Lucia light design featuring a 5” handblown glass globe for a more diffused light, a dimmable LED bulb, and a solid or perforated metal shade option available in nine colors.\n\nWith a constellation of stars visible through the perforated metal shade and bold bright colors, the Lexi references vintage MCM space inspired lighting and evokes a playful European modernist aesthetic.\n\nBrass finish available as solid shade only.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 1,
    referenceDefaultVariantId: "live-home-lexi-31764548354118",
    detail: {
      completeDescription: true,
      colorGallery: [
        "/api/reference-media/live-home-lexi-photo-1",
        "/api/reference-media/live-home-lexi-photo-2",
        "/api/reference-media/live-home-lexi-photo-3",
        "/api/reference-media/live-home-lexi-photo-4",
        "/api/reference-media/live-home-lexi-photo-5",
        "/api/reference-media/live-home-lexi-photo-6",
        "/api/reference-media/live-home-lexi-photo-7",
        "/api/reference-media/live-home-lexi-photo-8",
        "/api/reference-media/live-home-lexi-photo-9",
        "/api/reference-media/live-home-lexi-photo-10",
        "/api/reference-media/live-home-lexi-photo-11",
        "/api/reference-media/live-home-lexi-photo-12",
        "/api/reference-media/live-home-lexi-photo-13",
        "/api/reference-media/live-home-lexi-photo-14",
        "/api/reference-media/live-home-lexi-photo-15",
        "/api/reference-media/live-home-lexi-photo-16",
        "/api/reference-media/live-home-lexi-photo-17",
        "/api/reference-media/live-home-lexi-photo-18",
        "/api/reference-media/live-home-lexi-photo-19",
        "/api/reference-media/live-home-lexi-photo-20",
        "/api/reference-media/live-home-lexi-photo-21",
        "/api/reference-media/live-home-lexi-photo-22",
        "/api/reference-media/live-home-lexi-photo-23",
        "/api/reference-media/live-home-lexi-photo-24",
        "/api/reference-media/live-home-lexi-photo-25",
      ],
      optionGroups: [
        {
          name: "Solid or Perforated Shade",
          colors: false,
          showSelection: true,
        },
        {
          name: "Shade Finish",
          colors: false,
          showSelection: true,
          limit: 4,
        },
        {
          name: "Canopy Finish",
          colors: false,
          showSelection: true,
        },
      ],
    },
    variants: [
      {
        id: "live-home-lexi-31764548354118",
        label: 'Solid 8" Shade / Brass Solid Shade / Match Shade Finish',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Solid 8" Shade',
          "Shade Finish": "Brass Solid Shade",
          "Canopy Finish": "Match Shade Finish",
        },
        referencePrice: {
          amount: 42900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-8",
      },
      {
        id: "live-home-lexi-39434519838790",
        label: 'Solid 8" Shade / Brass Solid Shade / Walnut',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Solid 8" Shade',
          "Shade Finish": "Brass Solid Shade",
          "Canopy Finish": "Walnut",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-8",
      },
      {
        id: "live-home-lexi-39434520297542",
        label: 'Solid 8" Shade / Brass Solid Shade / Maple',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Solid 8" Shade',
          "Shade Finish": "Brass Solid Shade",
          "Canopy Finish": "Maple",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-8",
      },
      {
        id: "live-home-lexi-39434520789062",
        label: 'Solid 8" Shade / Brass Solid Shade / Black Stained',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Solid 8" Shade',
          "Shade Finish": "Brass Solid Shade",
          "Canopy Finish": "Black Stained",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-8",
      },
      {
        id: "live-home-lexi-40428124962886",
        label:
          'Solid 8" Shade / Heirloom Brass Solid Shade / Match Shade Finish',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Solid 8" Shade',
          "Shade Finish": "Heirloom Brass Solid Shade",
          "Canopy Finish": "Match Shade Finish",
        },
        referencePrice: {
          amount: 49900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-1",
      },
      {
        id: "live-home-lexi-40428124995654",
        label: 'Solid 8" Shade / Heirloom Brass Solid Shade / Walnut',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Solid 8" Shade',
          "Shade Finish": "Heirloom Brass Solid Shade",
          "Canopy Finish": "Walnut",
        },
        referencePrice: {
          amount: 52900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-1",
      },
      {
        id: "live-home-lexi-40428125028422",
        label: 'Solid 8" Shade / Heirloom Brass Solid Shade / Maple',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Solid 8" Shade',
          "Shade Finish": "Heirloom Brass Solid Shade",
          "Canopy Finish": "Maple",
        },
        referencePrice: {
          amount: 52900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-1",
      },
      {
        id: "live-home-lexi-40428125061190",
        label: 'Solid 8" Shade / Heirloom Brass Solid Shade / Black Stained',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Solid 8" Shade',
          "Shade Finish": "Heirloom Brass Solid Shade",
          "Canopy Finish": "Black Stained",
        },
        referencePrice: {
          amount: 52900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-1",
      },
      {
        id: "live-home-lexi-31764548616262",
        label: 'Solid 8" Shade / Matte Black / Match Shade Finish',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Solid 8" Shade',
          "Shade Finish": "Matte Black",
          "Canopy Finish": "Match Shade Finish",
        },
        referencePrice: {
          amount: 42900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-1",
      },
      {
        id: "live-home-lexi-39434519904326",
        label: 'Solid 8" Shade / Matte Black / Walnut',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Solid 8" Shade',
          "Shade Finish": "Matte Black",
          "Canopy Finish": "Walnut",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-10",
      },
      {
        id: "live-home-lexi-39434520363078",
        label: 'Solid 8" Shade / Matte Black / Maple',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Solid 8" Shade',
          "Shade Finish": "Matte Black",
          "Canopy Finish": "Maple",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-1",
      },
      {
        id: "live-home-lexi-39434520854598",
        label: 'Solid 8" Shade / Matte Black / Black Stained',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Solid 8" Shade',
          "Shade Finish": "Matte Black",
          "Canopy Finish": "Black Stained",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-1",
      },
      {
        id: "live-home-lexi-31764549009478",
        label: 'Solid 8" Shade / Ocean Blue / Match Shade Finish',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Solid 8" Shade',
          "Shade Finish": "Ocean Blue",
          "Canopy Finish": "Match Shade Finish",
        },
        referencePrice: {
          amount: 42900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-12",
      },
      {
        id: "live-home-lexi-39434520068166",
        label: 'Solid 8" Shade / Ocean Blue / Walnut',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Solid 8" Shade',
          "Shade Finish": "Ocean Blue",
          "Canopy Finish": "Walnut",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-14",
      },
      {
        id: "live-home-lexi-39434520494150",
        label: 'Solid 8" Shade / Ocean Blue / Maple',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Solid 8" Shade',
          "Shade Finish": "Ocean Blue",
          "Canopy Finish": "Maple",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-15",
      },
      {
        id: "live-home-lexi-39434520985670",
        label: 'Solid 8" Shade / Ocean Blue / Black Stained',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Solid 8" Shade',
          "Shade Finish": "Ocean Blue",
          "Canopy Finish": "Black Stained",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-12",
      },
      {
        id: "live-home-lexi-31764548878406",
        label: 'Solid 8" Shade / Persimmon / Match Shade Finish',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Solid 8" Shade',
          "Shade Finish": "Persimmon",
          "Canopy Finish": "Match Shade Finish",
        },
        referencePrice: {
          amount: 42900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-1",
      },
      {
        id: "live-home-lexi-39434520133702",
        label: 'Solid 8" Shade / Persimmon / Walnut',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Solid 8" Shade',
          "Shade Finish": "Persimmon",
          "Canopy Finish": "Walnut",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-1",
      },
      {
        id: "live-home-lexi-39434520559686",
        label: 'Solid 8" Shade / Persimmon / Maple',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Solid 8" Shade',
          "Shade Finish": "Persimmon",
          "Canopy Finish": "Maple",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-16",
      },
      {
        id: "live-home-lexi-39434521051206",
        label: 'Solid 8" Shade / Persimmon / Black Stained',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Solid 8" Shade',
          "Shade Finish": "Persimmon",
          "Canopy Finish": "Black Stained",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-1",
      },
      {
        id: "live-home-lexi-31764549140550",
        label: 'Solid 8" Shade / Secret Garden Green / Match Shade Finish',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Solid 8" Shade',
          "Shade Finish": "Secret Garden Green",
          "Canopy Finish": "Match Shade Finish",
        },
        referencePrice: {
          amount: 42900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-18",
      },
      {
        id: "live-home-lexi-39434520199238",
        label: 'Solid 8" Shade / Secret Garden Green / Walnut',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Solid 8" Shade',
          "Shade Finish": "Secret Garden Green",
          "Canopy Finish": "Walnut",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-18",
      },
      {
        id: "live-home-lexi-39434520625222",
        label: 'Solid 8" Shade / Secret Garden Green / Maple',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Solid 8" Shade',
          "Shade Finish": "Secret Garden Green",
          "Canopy Finish": "Maple",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-19",
      },
      {
        id: "live-home-lexi-39434521116742",
        label: 'Solid 8" Shade / Secret Garden Green / Black Stained',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Solid 8" Shade',
          "Shade Finish": "Secret Garden Green",
          "Canopy Finish": "Black Stained",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-18",
      },
      {
        id: "live-home-lexi-31764549435462",
        label: 'Solid 8" Shade / White / Match Shade Finish',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Solid 8" Shade',
          "Shade Finish": "White",
          "Canopy Finish": "Match Shade Finish",
        },
        referencePrice: {
          amount: 42900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-20",
      },
      {
        id: "live-home-lexi-39434520002630",
        label: 'Solid 8" Shade / White / Walnut',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Solid 8" Shade',
          "Shade Finish": "White",
          "Canopy Finish": "Walnut",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-22",
      },
      {
        id: "live-home-lexi-39434520428614",
        label: 'Solid 8" Shade / White / Maple',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Solid 8" Shade',
          "Shade Finish": "White",
          "Canopy Finish": "Maple",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-23",
      },
      {
        id: "live-home-lexi-39434520920134",
        label: 'Solid 8" Shade / White / Black Stained',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Solid 8" Shade',
          "Shade Finish": "White",
          "Canopy Finish": "Black Stained",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-20",
      },
      {
        id: "live-home-lexi-31764548681798",
        label: 'Perforated 8" Shade / Matte Black / Match Shade Finish',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Perforated 8" Shade',
          "Shade Finish": "Matte Black",
          "Canopy Finish": "Match Shade Finish",
        },
        referencePrice: {
          amount: 42900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-11",
      },
      {
        id: "live-home-lexi-39434519871558",
        label: 'Perforated 8" Shade / Matte Black / Walnut',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Perforated 8" Shade',
          "Shade Finish": "Matte Black",
          "Canopy Finish": "Walnut",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-11",
      },
      {
        id: "live-home-lexi-39434520330310",
        label: 'Perforated 8" Shade / Matte Black / Maple',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Perforated 8" Shade',
          "Shade Finish": "Matte Black",
          "Canopy Finish": "Maple",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-11",
      },
      {
        id: "live-home-lexi-39434520821830",
        label: 'Perforated 8" Shade / Matte Black / Black Stained',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Perforated 8" Shade',
          "Shade Finish": "Matte Black",
          "Canopy Finish": "Black Stained",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-11",
      },
      {
        id: "live-home-lexi-31764549075014",
        label: 'Perforated 8" Shade / Ocean Blue / Match Shade Finish',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Perforated 8" Shade',
          "Shade Finish": "Ocean Blue",
          "Canopy Finish": "Match Shade Finish",
        },
        referencePrice: {
          amount: 42900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-11",
      },
      {
        id: "live-home-lexi-39434520035398",
        label: 'Perforated 8" Shade / Ocean Blue / Walnut',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Perforated 8" Shade',
          "Shade Finish": "Ocean Blue",
          "Canopy Finish": "Walnut",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-12",
      },
      {
        id: "live-home-lexi-39434520461382",
        label: 'Perforated 8" Shade / Ocean Blue / Maple',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Perforated 8" Shade',
          "Shade Finish": "Ocean Blue",
          "Canopy Finish": "Maple",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-12",
      },
      {
        id: "live-home-lexi-39434520952902",
        label: 'Perforated 8" Shade / Ocean Blue / Black Stained',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Perforated 8" Shade',
          "Shade Finish": "Ocean Blue",
          "Canopy Finish": "Black Stained",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-12",
      },
      {
        id: "live-home-lexi-31764548943942",
        label: 'Perforated 8" Shade / Persimmon / Match Shade Finish',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Perforated 8" Shade',
          "Shade Finish": "Persimmon",
          "Canopy Finish": "Match Shade Finish",
        },
        referencePrice: {
          amount: 42900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-1",
      },
      {
        id: "live-home-lexi-39434520100934",
        label: 'Perforated 8" Shade / Persimmon / Walnut',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Perforated 8" Shade',
          "Shade Finish": "Persimmon",
          "Canopy Finish": "Walnut",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-1",
      },
      {
        id: "live-home-lexi-39434520526918",
        label: 'Perforated 8" Shade / Persimmon / Maple',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Perforated 8" Shade',
          "Shade Finish": "Persimmon",
          "Canopy Finish": "Maple",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-1",
      },
      {
        id: "live-home-lexi-39434521018438",
        label: 'Perforated 8" Shade / Persimmon / Black Stained',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Perforated 8" Shade',
          "Shade Finish": "Persimmon",
          "Canopy Finish": "Black Stained",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-1",
      },
      {
        id: "live-home-lexi-31764549206086",
        label: 'Perforated 8" Shade / Secret Garden Green / Match Shade Finish',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Perforated 8" Shade',
          "Shade Finish": "Secret Garden Green",
          "Canopy Finish": "Match Shade Finish",
        },
        referencePrice: {
          amount: 42900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-18",
      },
      {
        id: "live-home-lexi-39434520166470",
        label: 'Perforated 8" Shade / Secret Garden Green / Walnut',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Perforated 8" Shade',
          "Shade Finish": "Secret Garden Green",
          "Canopy Finish": "Walnut",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-18",
      },
      {
        id: "live-home-lexi-39434520592454",
        label: 'Perforated 8" Shade / Secret Garden Green / Maple',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Perforated 8" Shade',
          "Shade Finish": "Secret Garden Green",
          "Canopy Finish": "Maple",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-18",
      },
      {
        id: "live-home-lexi-39434521083974",
        label: 'Perforated 8" Shade / Secret Garden Green / Black Stained',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Perforated 8" Shade',
          "Shade Finish": "Secret Garden Green",
          "Canopy Finish": "Black Stained",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-18",
      },
      {
        id: "live-home-lexi-31764549500998",
        label: 'Perforated 8" Shade / White / Match Shade Finish',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Perforated 8" Shade',
          "Shade Finish": "White",
          "Canopy Finish": "Match Shade Finish",
        },
        referencePrice: {
          amount: 42900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-20",
      },
      {
        id: "live-home-lexi-39434519937094",
        label: 'Perforated 8" Shade / White / Walnut',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Perforated 8" Shade',
          "Shade Finish": "White",
          "Canopy Finish": "Walnut",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-20",
      },
      {
        id: "live-home-lexi-39434520395846",
        label: 'Perforated 8" Shade / White / Maple',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Perforated 8" Shade',
          "Shade Finish": "White",
          "Canopy Finish": "Maple",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-20",
      },
      {
        id: "live-home-lexi-39434520887366",
        label: 'Perforated 8" Shade / White / Black Stained',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          "Solid or Perforated Shade": 'Perforated 8" Shade',
          "Shade Finish": "White",
          "Canopy Finish": "Black Stained",
        },
        referencePrice: {
          amount: 45900,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-lexi-photo-20",
      },
    ],
  },
  {
    id: "live-home-tray",
    title: "Catchall Tray",
    storeId: "live-home-store-oakywood",
    category: "Home",
    images: [
      "/api/reference-media/live-home-tray-photo-7",
      "/api/reference-media/live-home-tray-photo-1",
      "/api/reference-media/live-home-tray-photo-2",
      "/api/reference-media/live-home-tray-photo-3",
      "/api/reference-media/live-home-tray-photo-4",
      "/api/reference-media/live-home-tray-photo-5",
      "/api/reference-media/live-home-tray-photo-6",
      "/api/reference-media/live-home-tray-photo-8",
      "/api/reference-media/live-home-tray-photo-9",
      "/api/reference-media/live-home-tray-photo-10",
      "/api/reference-media/live-home-tray-photo-11",
      "/api/reference-media/live-home-tray-photo-12",
      "/api/reference-media/live-home-tray-photo-13",
      "/api/reference-media/live-home-tray-photo-14",
      "/api/reference-media/live-home-tray-photo-15",
      "/api/reference-media/live-home-tray-photo-16",
      "/api/reference-media/live-home-tray-photo-17",
      "/api/reference-media/live-home-tray-photo-18",
      "/api/reference-media/live-home-tray-photo-19",
      "/api/reference-media/live-home-tray-photo-20",
      "/api/reference-media/live-home-tray-photo-21",
      "/api/reference-media/live-home-tray-photo-22",
      "/api/reference-media/live-home-tray-photo-23",
      "/api/reference-media/live-home-tray-photo-24",
      "/api/reference-media/live-home-tray-photo-25",
      "/api/reference-media/live-home-tray-photo-26",
      "/api/reference-media/live-home-tray-photo-27",
      "/api/reference-media/live-home-tray-photo-28",
      "/api/reference-media/live-home-tray-photo-29",
      "/api/reference-media/live-home-tray-photo-30",
      "/api/reference-media/live-home-tray-photo-31",
      "/api/reference-media/live-home-tray-photo-32",
      "/api/reference-media/live-home-tray-photo-33",
      "/api/reference-media/live-home-tray-photo-34",
      "/api/reference-media/live-home-tray-photo-35",
      "/api/reference-media/live-home-tray-photo-36",
      "/api/reference-media/live-home-tray-photo-37",
      "/api/reference-media/live-home-tray-photo-38",
      "/api/reference-media/live-home-tray-photo-39",
      "/api/reference-media/live-home-tray-photo-40",
      "/api/reference-media/live-home-tray-photo-41",
    ],
    referenceThumbnails: {
      shelf: "/api/reference-media/live-home-tray-photo-7",
      grid: "/api/reference-media/live-home-tray-photo-7",
    },
    price: {
      amount: 3900,
      currency: "EUR",
    },
    rating: 4.9,
    ratingCount: "39",
    description:
      "The Catchall Tray helps you organize miscellaneous items you don’t want to lose but don’t quite know where to store. Things like your watch, keys, a pen, some cords, smartphone, or favorite earrings for effective home and office organization.\n\n3 sizes\n\nAvailable in 3 sizes, the trays make it easy to customize your ideal organizer by arranging the trays in many ways.\n\nDesk Shelf compatibility\n\nThe organizers can be used as handy drawers for the Oakywood Desk Shelf, saving you space and adding structure to your workspace. 2 large, 3 medium, and 6 small will fit between the legs of the Desk Shelf.\n\nDamage protection\n\nNatural matte wax oil coating on the surface protects the tray without clogging the wood’s pores, while an ecological cork base prevents scratches.",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 1.3333333333333333,
    referenceDefaultVariantId: "live-home-tray-29517508575293",
    detail: {
      completeDescription: true,
      colorGallery: [
        "/api/reference-media/live-home-tray-photo-1",
        "/api/reference-media/live-home-tray-photo-2",
        "/api/reference-media/live-home-tray-photo-3",
        "/api/reference-media/live-home-tray-photo-4",
        "/api/reference-media/live-home-tray-photo-5",
        "/api/reference-media/live-home-tray-photo-6",
        "/api/reference-media/live-home-tray-photo-7",
        "/api/reference-media/live-home-tray-photo-8",
        "/api/reference-media/live-home-tray-photo-9",
        "/api/reference-media/live-home-tray-photo-10",
        "/api/reference-media/live-home-tray-photo-11",
        "/api/reference-media/live-home-tray-photo-12",
        "/api/reference-media/live-home-tray-photo-13",
        "/api/reference-media/live-home-tray-photo-14",
        "/api/reference-media/live-home-tray-photo-15",
        "/api/reference-media/live-home-tray-photo-16",
        "/api/reference-media/live-home-tray-photo-17",
        "/api/reference-media/live-home-tray-photo-18",
        "/api/reference-media/live-home-tray-photo-19",
        "/api/reference-media/live-home-tray-photo-20",
        "/api/reference-media/live-home-tray-photo-21",
        "/api/reference-media/live-home-tray-photo-22",
        "/api/reference-media/live-home-tray-photo-23",
        "/api/reference-media/live-home-tray-photo-24",
        "/api/reference-media/live-home-tray-photo-25",
        "/api/reference-media/live-home-tray-photo-26",
        "/api/reference-media/live-home-tray-photo-27",
        "/api/reference-media/live-home-tray-photo-28",
        "/api/reference-media/live-home-tray-photo-29",
        "/api/reference-media/live-home-tray-photo-30",
        "/api/reference-media/live-home-tray-photo-31",
        "/api/reference-media/live-home-tray-photo-32",
        "/api/reference-media/live-home-tray-photo-33",
        "/api/reference-media/live-home-tray-photo-34",
        "/api/reference-media/live-home-tray-photo-35",
        "/api/reference-media/live-home-tray-photo-36",
        "/api/reference-media/live-home-tray-photo-37",
        "/api/reference-media/live-home-tray-photo-38",
        "/api/reference-media/live-home-tray-photo-39",
        "/api/reference-media/live-home-tray-photo-40",
        "/api/reference-media/live-home-tray-photo-41",
      ],
      optionGroups: [
        {
          name: "Color",
          colors: true,
          showSelection: true,
        },
        {
          name: "Size",
          colors: false,
          showSelection: false,
        },
      ],
      referenceBadge: "25+ bought in past month",
      referenceBadgeTone: "neutral",
      arrivalLabel: "Arrives as soon as Mon, Oct 5",
    },
    variants: [
      {
        id: "live-home-tray-40335646425149",
        label: "Oak / Large",
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          Color: "Oak",
          Size: "Large",
        },
        referencePrice: {
          amount: 6900,
          currency: "EUR",
        },
        referenceImage: "/api/reference-media/live-home-tray-photo-1",
        referenceColor: {
          photo: "/api/reference-media/live-home-tray-photo-1",
          swatch:
            'url("/api/reference-media/live-home-tray-photo-1") center / contain no-repeat',
        },
      },
      {
        id: "live-home-tray-40335646392381",
        label: "Oak / Medium",
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          Color: "Oak",
          Size: "Medium",
        },
        referencePrice: {
          amount: 5900,
          currency: "EUR",
        },
        referenceImage: "/api/reference-media/live-home-tray-photo-4",
        referenceColor: {
          photo: "/api/reference-media/live-home-tray-photo-4",
          swatch:
            'url("/api/reference-media/live-home-tray-photo-4") center / contain no-repeat',
        },
      },
      {
        id: "live-home-tray-29517508575293",
        label: "Oak / Small",
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          Color: "Oak",
          Size: "Small",
        },
        referencePrice: {
          amount: 3900,
          currency: "EUR",
        },
        referenceImage: "/api/reference-media/live-home-tray-photo-7",
        referenceColor: {
          photo: "/api/reference-media/live-home-tray-photo-7",
          swatch:
            'url("/api/reference-media/live-home-tray-photo-7") center / contain no-repeat',
        },
      },
      {
        id: "live-home-tray-40335646490685",
        label: "Walnut / Large",
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          Color: "Walnut",
          Size: "Large",
        },
        referencePrice: {
          amount: 7900,
          currency: "EUR",
        },
        referenceImage: "/api/reference-media/live-home-tray-photo-13",
        referenceColor: {
          photo: "/api/reference-media/live-home-tray-photo-13",
          swatch:
            'url("/api/reference-media/live-home-tray-photo-13") center / contain no-repeat',
        },
      },
      {
        id: "live-home-tray-40335646457917",
        label: "Walnut / Medium",
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          Color: "Walnut",
          Size: "Medium",
        },
        referencePrice: {
          amount: 6900,
          currency: "EUR",
        },
        referenceImage: "/api/reference-media/live-home-tray-photo-16",
        referenceColor: {
          photo: "/api/reference-media/live-home-tray-photo-16",
          swatch:
            'url("/api/reference-media/live-home-tray-photo-16") center / contain no-repeat',
        },
      },
      {
        id: "live-home-tray-29517508608061",
        label: "Walnut / Small",
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          Color: "Walnut",
          Size: "Small",
        },
        referencePrice: {
          amount: 4900,
          currency: "EUR",
        },
        referenceImage: "/api/reference-media/live-home-tray-photo-19",
        referenceColor: {
          photo: "/api/reference-media/live-home-tray-photo-19",
          swatch:
            'url("/api/reference-media/live-home-tray-photo-19") center / contain no-repeat',
        },
      },
      {
        id: "live-home-tray-40335646588989",
        label: "Black / Large",
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          Color: "Black",
          Size: "Large",
        },
        referencePrice: {
          amount: 7900,
          currency: "EUR",
        },
        referenceImage: "/api/reference-media/live-home-tray-photo-25",
        referenceColor: {
          photo: "/api/reference-media/live-home-tray-photo-25",
          swatch:
            'url("/api/reference-media/live-home-tray-photo-25") center / contain no-repeat',
        },
      },
      {
        id: "live-home-tray-40335646556221",
        label: "Black / Medium",
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          Color: "Black",
          Size: "Medium",
        },
        referencePrice: {
          amount: 6900,
          currency: "EUR",
        },
        referenceImage: "/api/reference-media/live-home-tray-photo-28",
        referenceColor: {
          photo: "/api/reference-media/live-home-tray-photo-28",
          swatch:
            'url("/api/reference-media/live-home-tray-photo-28") center / contain no-repeat',
        },
      },
      {
        id: "live-home-tray-40335646523453",
        label: "Black / Small",
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          Color: "Black",
          Size: "Small",
        },
        referencePrice: {
          amount: 4900,
          currency: "EUR",
        },
        referenceImage: "/api/reference-media/live-home-tray-photo-31",
        referenceColor: {
          photo: "/api/reference-media/live-home-tray-photo-31",
          swatch:
            'url("/api/reference-media/live-home-tray-photo-31") center / contain no-repeat',
        },
      },
    ],
  },
  {
    id: "live-home-cushion",
    title: "Amber Bronze Stripes Linen Cushion Cover",
    storeId: "live-home-store-linen-tales",
    category: "Home",
    images: [
      "/api/reference-media/live-home-cushion-photo-1",
      "/api/reference-media/live-home-cushion-photo-2",
      "/api/reference-media/live-home-cushion-photo-3",
    ],
    referenceThumbnails: {
      shelf: "/api/reference-media/live-home-cushion-photo-1",
      grid: "/api/reference-media/live-home-cushion-photo-1",
    },
    price: {
      amount: 2900,
      currency: "EUR",
    },
    rating: 5,
    ratingCount: "2",
    description:
      "Transform your home in a blink of an eye with beautiful Linen Cushion Cover. This fantastic linen fabric will bring a gentle touch of comfort to any room in your house, and you can spend your free time feeling most relaxed while reading, lounging, or taking a nap. - Convenient closing with zipper to keep your cover in place- The zipper for the rectangular cushion cover will be sewn in a shorter side- 100% linen, 215 g/m2 - Stone washed for extra softness- Handmade with love in Lithuania- OEKO-TEX® and EUROPEAN FLAX® certified linen",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 1,
    referenceDefaultVariantId: "live-home-cushion-56135458390365",
    detail: {
      completeDescription: true,
      colorGallery: [
        "/api/reference-media/live-home-cushion-photo-1",
        "/api/reference-media/live-home-cushion-photo-2",
        "/api/reference-media/live-home-cushion-photo-3",
      ],
      optionGroups: [
        {
          name: "Size",
          colors: false,
          showSelection: false,
          limit: 3,
        },
        {
          name: "Color option",
          colors: false,
          showSelection: true,
        },
      ],
    },
    variants: [
      {
        id: "live-home-cushion-56135458390365",
        label: '40x40 cm | 16"x16" / Color options',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          Size: '40x40 cm | 16"x16"',
          "Color option": "Color options",
        },
        referencePrice: {
          amount: 2900,
          currency: "EUR",
        },
        referenceImage: "/api/reference-media/live-home-cushion-photo-1",
      },
      {
        id: "live-home-cushion-56135458423133",
        label: '40x60 cm | 16"x24" / Color options',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          Size: '40x60 cm | 16"x24"',
          "Color option": "Color options",
        },
        referencePrice: {
          amount: 3700,
          currency: "EUR",
        },
        referenceImage: "/api/reference-media/live-home-cushion-photo-1",
      },
      {
        id: "live-home-cushion-56135458455901",
        label: '40x80 cm | 16"x31" / Color options',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          Size: '40x80 cm | 16"x31"',
          "Color option": "Color options",
        },
        referencePrice: {
          amount: 4300,
          currency: "EUR",
        },
        referenceImage: "/api/reference-media/live-home-cushion-photo-1",
      },
      {
        id: "live-home-cushion-56135458488669",
        label: '45x45 cm | 18"x18" / Color options',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          Size: '45x45 cm | 18"x18"',
          "Color option": "Color options",
        },
        referencePrice: {
          amount: 3600,
          currency: "EUR",
        },
        referenceImage: "/api/reference-media/live-home-cushion-photo-1",
      },
      {
        id: "live-home-cushion-56135458521437",
        label: '50x50 cm | 20"x20" / Color options',
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          Size: '50x50 cm | 20"x20"',
          "Color option": "Color options",
        },
        referencePrice: {
          amount: 3800,
          currency: "EUR",
        },
        referenceImage: "/api/reference-media/live-home-cushion-photo-1",
      },
    ],
  },
  {
    id: "live-home-jupiter",
    title: "Jupiter V1 Rechargeable Cordless Table Lamp - Glass",
    storeId: "live-home-store-insight-cordless-lighting",
    category: "Home",
    images: [
      "/api/reference-media/live-home-jupiter-photo-1",
      "/api/reference-media/live-home-jupiter-photo-2",
      "/api/reference-media/live-home-jupiter-photo-3",
      "/api/reference-media/live-home-jupiter-photo-4",
      "/api/reference-media/live-home-jupiter-photo-5",
      "/api/reference-media/live-home-jupiter-photo-6",
    ],
    referenceThumbnails: {
      shelf: "/api/reference-media/live-home-jupiter-photo-1",
      grid: "/api/reference-media/live-home-jupiter-photo-1",
    },
    price: {
      amount: 4083,
      currency: "GBP",
    },
    rating: 4.8,
    ratingCount: "146",
    description:
      "Elegant, atmospheric, and beautifully sculptural — the Jupiter Glass Rechargeable Table Lamp is designed to create a captivating sense of warmth and sophistication within luxury hospitality and contemporary residential interiors. Inspired by the timeless beauty of decorative glass lighting, this premium wireless table lamp combines artistic detailing with advanced cordless technology to deliver both ambience and functionality in equal measure.\n\nCrafted with a delicately textured glass-effect diffuser, the Jupiter softly refracts light to create a warm, inviting glow with subtle depth and sparkle. Its rounded silhouette and intricate surface pattern evoke the elegance of hand-cut crystal, transforming the lamp into both a practical light source and a decorative statement piece.\n\nWhether placed within intimate restaurant settings, luxury hotel suites, elegant cocktail bars, spa lounges, or sophisticated residential spaces, the Jupiter creates a refined atmosphere that feels warm, calming, and effortlessly luxurious. The soft illumination flatters surrounding materials and enhances interior mood without overpowering the space.\n\nCompletely cordless and portable, this rechargeable table lamp allows complete freedom in table arrangement and styling without visible cables or fixed power sources. Compact yet visually impactful, the Jupiter is ideal for creating atmospheric table lighting where aesthetics and flexibility are equally important.\n\nDesigned for professional hospitality environments, the Jupiter Glass Wireless Table Lamp combines decorative elegance with intelligent lighting technology. Multiple warm white colour temperatures, ambient light colour selection, stepless dimming, and programmable lighting controls allow the ambience to be tailored perfectly throughout the day and evening.\n\nSophisticated yet playful, decorative yet highly practical — the Jupiter Glass Rechargeable Table Lamp is designed for interiors where lighting becomes part of the experience.\n\nKey Features\n\nPremium rechargeable table lamp with decorative glass-effect diffuser\n\nElegant wireless table lamp design with sculptural rounded silhouette\n\nLong-lasting rechargeable battery with 18–75 hours runtime\n\nReplaceable professional-grade rechargeable battery system\n\nQi wireless charging compatible (chargers sold separately)\n\nRemote control compatible for seamless lighting management (remotes sold separately)\n\n2200K, 2400K, and 2700K warm white colour temperature settings\n\n12 selectable ambient light colours for versatile mood lighting\n\nStepless brightness dimming for precise ambience control\n\nLighting zone functionality for grouped lighting management\n\nEco Smart Mode (“Lighting Auto Pilot”) for automated lighting schedules and battery optimisation\n\nLock function to prevent accidental setting changes\n\nIP65-rated water and dust resistant construction for indoor and outdoor use\n\nTextured diffuser softly refracts light to create warm atmospheric illumination\n\nIdeal for restaurants, cocktail bars, boutique hotels, lounges, spas, and elegant homes\n\nPortable cordless design for flexible table placement and effortless styling\n\nCombines decorative glass-inspired aesthetics with professional hospitality performance",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 1,
    referenceDefaultVariantId: "live-home-jupiter-57611523785078",
    detail: {
      completeDescription: true,
      colorGallery: [
        "/api/reference-media/live-home-jupiter-photo-1",
        "/api/reference-media/live-home-jupiter-photo-2",
        "/api/reference-media/live-home-jupiter-photo-3",
        "/api/reference-media/live-home-jupiter-photo-4",
        "/api/reference-media/live-home-jupiter-photo-5",
        "/api/reference-media/live-home-jupiter-photo-6",
      ],
      optionGroups: [],
    },
    variants: [
      {
        id: "live-home-jupiter-57611523785078",
        label: "Default Title",
        availableQuantity: null,
        referenceSelectable: true,
        referencePrice: {
          amount: 4083,
          currency: "GBP",
        },
        referenceImage: "/api/reference-media/live-home-jupiter-photo-1",
      },
    ],
  },
  {
    id: "live-home-bin",
    title: "Merino Wool Large Bin",
    storeId: "live-home-store-graf-lantz",
    category: "Home",
    images: [
      "/api/reference-media/live-home-bin-photo-1",
      "/api/reference-media/live-home-bin-photo-2",
      "/api/reference-media/live-home-bin-photo-3",
      "/api/reference-media/live-home-bin-photo-4",
      "/api/reference-media/live-home-bin-photo-5",
    ],
    referenceThumbnails: {
      shelf: "/api/reference-media/live-home-bin-photo-1",
      grid: "/api/reference-media/live-home-bin-photo-1",
    },
    price: {
      amount: 16800,
      currency: "USD",
    },
    rating: 5,
    ratingCount: "2",
    description:
      "The Merino Wool Large Bin thrives in a space where organization isn’t always neat or perfect. It welcomes the misfits, the odds and ends—whether toys, towels, or cozy throws—giving everything a place to call home. With its generous size, this versatile bin is ready to house whatever you need to store, helping keep your space stylishly organized without sacrificing ease or comfort.\n\n \n\nBenefits of Merino Wool \n\nSustainable, biodegradable, and renewable\n\nOdor, stain, heat, and dirt-resistant\n\nOeko-Tex® Certified\n\nSee all the benefits of our Merino wool\n\nHow to clean and care for your fabric\n\n---",
    saleUnit: "piece",
    referenceStyle: "android",
    referenceImageRatio: 0.8199445983379502,
    referenceDefaultVariantId: "live-home-bin-43265087209581",
    detail: {
      completeDescription: true,
      colorGallery: [
        "/api/reference-media/live-home-bin-photo-1",
        "/api/reference-media/live-home-bin-photo-2",
        "/api/reference-media/live-home-bin-photo-3",
        "/api/reference-media/live-home-bin-photo-4",
        "/api/reference-media/live-home-bin-photo-5",
      ],
      optionGroups: [
        {
          name: "Color",
          colors: true,
          showSelection: true,
        },
      ],
    },
    variants: [
      {
        id: "live-home-bin-43265087209581",
        label: "Charcoal",
        availableQuantity: null,
        referenceSelectable: true,
        referenceOptions: {
          Color: "Charcoal",
        },
        referencePrice: {
          amount: 16800,
          currency: "USD",
        },
        referenceImage: "/api/reference-media/live-home-bin-photo-1",
        referenceColor: {
          photo: "/api/reference-media/live-home-bin-photo-1",
          swatch:
            'url("/api/reference-media/live-home-bin-photo-1") center / contain no-repeat',
        },
      },
    ],
  },
];
export const livingRoomProductIds: readonly string[] = [
  "live-home-silque",
  "live-home-barts",
  "live-home-papasan",
  "live-home-kobon",
  "live-home-olive",
  "live-home-lexi",
  "live-home-tray",
  "live-home-cushion",
  "live-home-jupiter",
  "live-home-bin",
];
const collectionPrices: Readonly<Record<string, Money>> = {
  "live-home-silque": {
    amount: 23500,
    currency: "USD",
  },
  "live-home-barts": {
    amount: 13260,
    currency: "USD",
  },
  "live-home-papasan": {
    amount: 20045,
    currency: "EUR",
  },
  "live-home-kobon": {
    amount: 10200,
    currency: "USD",
  },
  "live-home-olive": {
    amount: 24000,
    currency: "USD",
  },
  "live-home-lexi": {
    amount: 42900,
    currency: "USD",
  },
  "live-home-tray": {
    amount: 3900,
    currency: "EUR",
  },
  "live-home-cushion": {
    amount: 2900,
    currency: "EUR",
  },
  "live-home-jupiter": {
    amount: 4083,
    currency: "GBP",
  },
  "live-home-bin": {
    amount: 16800,
    currency: "USD",
  },
};
export function projectLivingRoom(products: readonly Product[]): Product[] {
  return livingRoomProductIds.flatMap((id) => {
    const product = products.find((item) => item.id === id);
    return product ? [{ ...product, price: collectionPrices[id] }] : [];
  });
}
