export type SellingLocale = "bg" | "en";

export const sellingCopy = {
  bg: {
    title: "Продай вещ",
    profile: "Профил",
    category: "Категория",
    details: "Характеристики",
    review: "Преглед",
    intro: "Избери най-точната категория за твоята вещ.",
    search: "Търси категория",
    searchHint: "Например телефон, диван или книги",
    allCategories: "Всички категории",
    subcategories: "Подкатегории",
    noResults: "Няма намерени категории. Опитай с друга дума.",
    searchLimit:
      "Показани са първите 48 съвпадения. Уточни търсенето, ако не виждаш своята категория.",
    changeCategory: "Промени категорията",
    back: "Назад",
    continue: "Прегледай характеристиките",
    edit: "Редактирай",
    condition: "Състояние на вещта",
    choose: "Избери",
    optional: "незадължително",
    moreDetails: "Още характеристики",
    moreDetailsHint:
      "Незадължителни детайли, които помагат на купувачите да изберат.",
    required: "задължително",
    yes: "Да",
    no: "Не",
    fieldError: "Провери тази стойност.",
    requiredError: "Попълни това поле.",
    fixErrors: "Провери отбелязаните полета, за да продължиш.",
    conditionError: "Избери допустимо състояние за тази категория.",
    characterLimit: "Максимален брой символи:",
    wholeNumber: "Цяло число от",
    to: "до",
    positiveDimensions:
      "Въведи ширина, височина и дълбочина. Максимум 100 m за всяка страна.",
    width: "Ширина",
    height: "Височина",
    depth: "Дълбочина",
    unit: "Мерна единица",
    maxChoices: "Максимален брой избори:",
    sealedHint: "В тази категория се приемат само фабрично запечатани вещи.",
    decimalHint: "Число от 0,01 до 10 000 kg; до 2 знака след запетаята.",
    carrierHint: "Посочи оператора, ако устройството е заключено към него.",
    fitmentHint:
      "Посочи източника, когато въвеждаш съвместимо превозно средство.",
    scopeNote:
      "Тук подготвяш категорията и характеристиките. Снимки, цена и запазване в акаунт предстоят в следващите стъпки.",
    save: "Запази на това устройство",
    saved:
      "Запазено на това устройство. Можеш да възстановиш подготовката при следващо посещение.",
    saveFailed:
      "Браузърът не позволи запазване. Данните остават в тази отворена страница.",
    restore: "Възстанови",
    discard: "Изтрий запазеното",
    savedAvailable: "Имаш запазена подготовка на това устройство.",
    invalidSaved:
      "Запазените данни са невалидни или използват стара версия на категориите. Изтрий ги и избери категория отново.",
    discarded: "Запазената подготовка е изтрита от това устройство.",
    publish: "Публикувай",
    publishPending:
      "Тази категория още не е отворена за публикуване. Подготовката не създава публична обява.",
    reviewIntro:
      "Провери категорията и характеристиките, преди да запазиш подготовката.",
    nothingOptional: "Няма други попълнени характеристики.",
  },
  en: {
    title: "Sell an item",
    profile: "Profile",
    category: "Category",
    details: "Details",
    review: "Review",
    intro: "Choose the most specific category for your item.",
    search: "Search categories",
    searchHint: "For example, phone, sofa or books",
    allCategories: "All categories",
    subcategories: "Subcategories",
    noResults: "No categories found. Try a different word.",
    searchLimit:
      "Showing the first 48 matches. Refine your search if you cannot see your category.",
    changeCategory: "Change category",
    back: "Back",
    continue: "Review details",
    edit: "Edit",
    condition: "Item condition",
    choose: "Choose",
    optional: "optional",
    moreDetails: "More details",
    moreDetailsHint: "Optional details that help buyers choose.",
    required: "required",
    yes: "Yes",
    no: "No",
    fieldError: "Check this value.",
    requiredError: "Complete this field.",
    fixErrors: "Check the highlighted fields to continue.",
    conditionError: "Choose an allowed condition for this category.",
    characterLimit: "Maximum characters:",
    wholeNumber: "Whole number from",
    to: "to",
    positiveDimensions:
      "Enter width, height and depth. Maximum 100 m for each side.",
    width: "Width",
    height: "Height",
    depth: "Depth",
    unit: "Unit",
    maxChoices: "Maximum selections:",
    sealedHint: "Only factory-sealed items are accepted in this category.",
    decimalHint:
      "A number from 0.01 to 10,000 kg, with up to 2 decimal places.",
    carrierHint: "Specify the carrier if the device is locked to it.",
    fitmentHint:
      "Specify your source when entering compatible vehicle details.",
    scopeNote:
      "Prepare the category and details here. Photos, pricing and saving to your account come in the next steps.",
    save: "Save on this device",
    saved:
      "Saved on this device. You can restore this preparation on your next visit.",
    saveFailed:
      "Your browser did not allow saving. Your details remain in this open page.",
    restore: "Restore",
    discard: "Delete saved preparation",
    savedAvailable: "You have saved preparation on this device.",
    invalidSaved:
      "The saved details are invalid or use an older category version. Delete them and choose a category again.",
    discarded: "Saved preparation deleted from this device.",
    publish: "Publish",
    publishPending:
      "This category is not open for publication yet. Preparing these details does not create a public listing.",
    reviewIntro:
      "Check the category and details before saving your preparation.",
    nothingOptional: "No other details entered.",
  },
} as const;

const optionLabels: Record<string, readonly [string, string]> = {
  new: ["Ново", "New"],
  new_other: ["Ново, с отворена опаковка", "New, open box"],
  like_new: ["Като ново", "Like new"],
  good: ["Добро", "Good"],
  fair: ["Задоволително", "Fair"],
  for_parts: ["За части или ремонт", "For parts or repair"],
  refurbished: ["Обновено", "Refurbished"],
  women: ["Жени", "Women"],
  men: ["Мъже", "Men"],
  unisex: ["Унисекс", "Unisex"],
  girls: ["Момичета", "Girls"],
  boys: ["Момчета", "Boys"],
  letter: ["Буквен размер (S, M, L)", "Letter size (S, M, L)"],
  one_size: ["Универсален размер", "One size"],
  other: ["Друго", "Other"],
  working: ["Работи", "Working"],
  partly_working: ["Работи частично", "Partly working"],
  not_working: ["Не работи", "Not working"],
  unknown: ["Не е известно", "Unknown"],
  normal: ["Нормално", "Normal"],
  reduced: ["Намален капацитет", "Reduced capacity"],
  needs_replacement: ["За смяна", "Needs replacement"],
  charger: ["Зарядно", "Charger"],
  cable: ["Кабел", "Cable"],
  case: ["Калъф", "Case"],
  box: ["Кутия", "Box"],
  manual: ["Упътване", "Manual"],
  battery: ["Батерия", "Battery"],
  stand: ["Стойка", "Stand"],
  pickup_only: ["Само лично предаване", "Pickup only"],
  shipping_possible: ["Възможна е доставка", "Shipping possible"],
  fitness: ["Фитнес", "Fitness"],
  cycling: ["Колоездене", "Cycling"],
  camping: ["Къмпинг", "Camping"],
  hiking: ["Туризъм", "Hiking"],
  football: ["Футбол", "Football"],
  basketball: ["Баскетбол", "Basketball"],
  volleyball: ["Волейбол", "Volleyball"],
  tennis: ["Тенис", "Tennis"],
  badminton: ["Бадминтон", "Badminton"],
  swimming: ["Плуване", "Swimming"],
  skiing: ["Ски", "Skiing"],
  snowboarding: ["Сноуборд", "Snowboarding"],
  fishing: ["Риболов", "Fishing"],
  skating: ["Кънки", "Skating"],
  baby: ["Бебе", "Baby"],
  toddler: ["Малко дете", "Toddler"],
  child: ["Дете", "Child"],
  teen: ["Тийнейджър", "Teen"],
  adult: ["Възрастен", "Adult"],
  all_ages: ["Всички възрасти", "All ages"],
  not_recalled: ["Не е изтеглен от продажба", "Not recalled"],
  recalled: ["Изтеглен от продажба", "Recalled"],
  bg: ["Български", "Bulgarian"],
  en: ["Английски", "English"],
  de: ["Немски", "German"],
  fr: ["Френски", "French"],
  es: ["Испански", "Spanish"],
  it: ["Италиански", "Italian"],
  ru: ["Руски", "Russian"],
  not_applicable: ["Не е приложимо", "Not applicable"],
  hardback: ["Твърди корици", "Hardback"],
  paperback: ["Меки корици", "Paperback"],
  magazine: ["Списание", "Magazine"],
  vinyl: ["Грамофонна плоча", "Vinyl"],
  cd: ["CD", "CD"],
  dvd: ["DVD", "DVD"],
  blu_ray: ["Blu-ray", "Blu-ray"],
  manufacturer: ["Производител", "Manufacturer"],
  catalogue: ["Каталог", "Catalogue"],
  seller_declared: ["Посочено от продавача", "Seller declared"],
  documented: ["Документиран", "Documented"],
};

export function optionLabel(value: string, locale: SellingLocale): string {
  return optionLabels[value]?.[locale === "bg" ? 0 : 1] ?? value;
}
